table Geography
	lineageTag: 0752bdbe-4c43-4568-a725-a28d2d4c4a28

	column Geo_ID
		dataType: int64
		formatString: 0
		lineageTag: 4576bf89-370b-4199-bd42-c9c64fa43830
		summarizeBy: none
		sourceColumn: Geo_ID

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: b852439c-016d-427a-9f4d-357c439fac7b
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column City
		dataType: string
		lineageTag: 893055c2-3bea-4bd8-9266-f7bb435b72a7
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Zip
		dataType: int64
		formatString: 0
		lineageTag: 59f10647-ebf8-4984-afea-d0fb36f938a3
		summarizeBy: none
		sourceColumn: Zip

		annotation SummarizationSetBy = Automatic

	column Latitude
		dataType: double
		lineageTag: ea228d0d-6a87-468c-8d23-9061e897e7c8
		summarizeBy: none
		sourceColumn: Latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Longitude
		dataType: double
		lineageTag: e7db8569-294a-4ffb-bead-af4be337cc63
		summarizeBy: none
		sourceColumn: Longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Geography-5c2ef268-856f-4057-aa53-ccdcd82e936b = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\seanc\OneDrive\Desktop\Udacity\Course\2020_12_09_Course_Datasets.xlsx"), null, true),
				    Geography_Sheet = Source{[Item="Geography",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Geography_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Geo_ID", Int64.Type}, {"State", type text}, {"City", type text}, {"Zip", Int64.Type}, {"Latitude", type number}, {"Longitude", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

