{%- set trimmed_source_name = model.name | replace("ERP_STAGE_","") -%}

{{
    config(
        alias= trimmed_source_name,
        materialized = 'table'
    )
}}




SELECT
PAYMENT_SCHEDULE_ID,
ACCOUNT_NUMBER,
PARTY_NAME,
CUSTOMER_TRX_ID,
CLASS,
TRANS_TYPE,
TRANS_TYPE_NAME,
CUST_TRX_TYPE_ID,
INVOICE_CURRENCY_CODE,
LOCATION_CODE,
TRANSACTION_NUMBER,
TRANS_DATE,
GL_DATE_PS,
DUE_DATE,
AMOUNT_DUE_ORIGINAL,
AMOUNT_DUE_ORIGINAL_EXCH,
EXCHANGE_RATE,
AMOUNT_DUE_REMAINING,
ACCTD_AMOUNT_DUE_REMAINING,
RECEIVABLE_APPLICATION_ID,
GL_DATE_AR,
RECEIPT_DATE,
AMOUNT_APPLIED,
DISPLAY_AR,
LAST_UPDATE_DATE,
BU_NAME,
APPLICATION_TYPE, 
STATUS
FROM
(

SELECT 
AR_TAB.PAYMENT_SCHEDULE_ID,
AR_TAB.ACCOUNT_NUMBER ,
AR_TAB.PARTY_NAME,
AR_TAB.CUSTOMER_TRX_ID,
AR_TAB.CLASS,
AR_TAB.TRANS_TYPE,
AR_TAB.TRANS_TYPE_NAME,
AR_TAB.CUST_TRX_TYPE_ID,
AR_TAB.INVOICE_CURRENCY_CODE,
AR_TAB.LOCATION_CODE,
AR_TAB.TRANSACTION_NUMBER,
to_char(AR_TAB.TRANS_DATE,'YYYY-MM-DD HH24:MI:SS') as TRANS_DATE,
to_char(AR_TAB.GL_DATE_PS,'YYYY-MM-DD HH24:MI:SS') as GL_DATE_PS,
to_char(AR_TAB.DUE_DATE,'YYYY-MM-DD HH24:MI:SS') as DUE_DATE,
AR_TAB.AMOUNT_DUE_ORIGINAL,
AR_TAB.AMOUNT_DUE_ORIGINAL_EXCH,
AR_TAB.EXCHANGE_RATE,
AR_TAB.AMOUNT_DUE_REMAINING,
AR_TAB.ACCTD_AMOUNT_DUE_REMAINING,
NVL(AR_TAB.RECEIVABLE_APPLICATION_ID,0) RECEIVABLE_APPLICATION_ID,
AR_TAB.PAYMENT_SCHEDULE_ID_AR,
NVL(to_char(AR_TAB.GL_DATE_AR,'YYYY-MM-DD HH24:MI:SS'),'2900-01-01 00:00:00') as GL_DATE_AR,
to_char(AR_TAB.RECEIPT_DATE,'YYYY-MM-DD HH24:MI:SS') as RECEIPT_DATE,
AR_TAB.AMOUNT_APPLIED,
AR_TAB.DISPLAY_AR,
AR_TAB.APPLICATION_TYPE, 
AR_TAB.STATUS,
(CASE WHEN AR_TAB.LAST_UPDATE_DATE > NVL(AR_TAB.LAST_UPDATE_DATE_AR, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) THEN 
to_char(AR_TAB.LAST_UPDATE_DATE,'YYYY-MM-DD HH24:MI:SS') ELSE 
to_char(AR_TAB.LAST_UPDATE_DATE_AR,'YYYY-MM-DD HH24:MI:SS') END)  LAST_UPDATE_DATE,
AR_TAB.BU_NAME
FROM
(
    SELECT
    PS.AR_PAYMENT_SCHEDULE_PAYMENT_SCHEDULE_ID as PAYMENT_SCHEDULE_ID,
    HP.CUSTOMER_ACCOUNT_ACCOUNT_NUMBER as ACCOUNT_NUMBER,
    HP.PARTY_PARTY_NAME as PARTY_NAME,
    CTA.RA_CUSTOMER_TRX_CUSTOMER_TRX_ID as CUSTOMER_TRX_ID,
    PS.AR_PAYMENT_SCHEDULE_PAYMENT_SCHEDULE_CLASS_1 as CLASS,
    DECODE(PS.AR_PAYMENT_SCHEDULE_PAYMENT_SCHEDULE_CLASS_1,'INV', 'INVOICE', 'DM', 'DEBIT MEMO','CM','CREDIT MEMO') TRANS_TYPE,
    RCTT.RA_CUST_TRX_TYPE_NAME TRANS_TYPE_NAME,
    RCTT.RA_CUST_TRX_TYPE_CUST_TRX_TYPE_ID as CUST_TRX_TYPE_ID,
    CTA.RA_CUSTOMER_TRX_INVOICE_CURRENCY_CODE as INVOICE_CURRENCY_CODE,
    HOU.LOCATION_CODE,
    PS.AR_PAYMENT_SCHEDULE_TRX_NUMBER TRANSACTION_NUMBER,
    PS.AR_PAYMENT_SCHEDULE_TRX_DATE TRANS_DATE,
    PS.AR_PAYMENT_SCHEDULE_GL_DATE GL_DATE_PS,
    PS.AR_PAYMENT_SCHEDULE_DUE_DATE as DUE_DATE,
    PS.AR_PAYMENT_SCHEDULE_AMOUNT_DUE_ORIGINAL as AMOUNT_DUE_ORIGINAL,
    ROUND((PS.AR_PAYMENT_SCHEDULE_AMOUNT_DUE_ORIGINAL * NVL(PS.AR_PAYMENT_SCHEDULE_EXCHANGE_RATE,1)),2) AMOUNT_DUE_ORIGINAL_EXCH,
    NVL(PS.AR_PAYMENT_SCHEDULE_EXCHANGE_RATE,1) EXCHANGE_RATE,
    PS.AR_PAYMENT_SCHEDULE_AMOUNT_DUE_REMAINING as AMOUNT_DUE_REMAINING,
    PS.AR_PAYMENT_SCHEDULE_ACCTD_AMOUNT_DUE_REMAINING as ACCTD_AMOUNT_DUE_REMAINING,
    AR_REC_APP_ALL.RECEIVABLE_APPLICATION_ID,
    AR_REC_APP_ALL.APPLIED_PAYMENT_SCHEDULE_ID PAYMENT_SCHEDULE_ID_AR,
    AR_REC_APP_ALL.GL_DATE GL_DATE_AR,
    AR_REC_APP_ALL.RECEIPT_DATE,
    AR_REC_APP_ALL.AMOUNT_APPLIED,
    AR_REC_APP_ALL.DISPLAY DISPLAY_AR,
    AR_REC_APP_ALL.APPLICATION_TYPE, 
    AR_REC_APP_ALL.STATUS,    
    AR_REC_APP_ALL.LAST_UPDATE_DATE LAST_UPDATE_DATE_AR,    
    PS.AR_PAYMENT_SCHEDULE_LAST_UPDATE_DATE as LAST_UPDATE_DATE,    
    BU.FUN_BU_PERF_PEONAME as BU_NAME
    FROM CES_ERP.FSCM_PROD_FINEXTRACT_ARBICCEXTRACT.PAYMENT_SCHEDULE_EXTRACT_PVO PS --FscmTopModelAM.FinExtractAM.ArBiccExtractAM.PaymentScheduleExtractPVO
    --,CES_ERP.FSCM_PROD_PARTIESANALYTICS.CUSTOMER_ACCOUNT HCA --FscmTopModelAM.PartiesAnalyticsAM.CustomerAccount
    ,CES_ERP.FSCM_PROD_CONTRACTSCORE.CONTRACT_CUSTOMER_ACCOUNT_P HP
    --,CES_ERP.FSCM_PROD_PRCPOZPUBLICVIEW.SUPPLIER_PVO HP --FscmTopModelAM.PrcPozPublicViewAM.SupplierPVO
    ,CES_ERP.FSCM_PROD_FINEXTRACT_ARBICCEXTRACT.TRANSACTION_HEADER_EXTRACT_PVO CTA --FscmTopModelAM.FinExtractAM.ArBiccExtractAM.TransactionHeaderExtractPVO
    ,CES_ERP.FSCM_PROD_FINEXTRACT_ARBICCEXTRACT.TRANSACTION_TYPE_EXTRACT_PVO RCTT --FscmTopModelAM.FinExtractAM.ArBiccExtractAM.TransactionTypeExtractPVO
    ,(SELECT
    hao.ORGANIZATION_ID as organization_id,
    hc.LOCATION_DETAILS_TRANSLATION_PEOLOCATION_CODE as location_code
    FROM
        CES_ERP.FSCM_PROD_ORGANIZATION.ORGANIZATION_UNIT_TRANSLATION_PVO   hao, 
        CES_ERP.FSCM_PROD_FINFUNBUSINESSUNITS.BUSINESS_UNIT_PVO hoi,
        CES_ERP.FSCM_PROD_LOCATION.LOCATION_DETAILS_TRANSLATION_PVOVIEW_ALL hc
    WHERE
        hao.ORGANIZATION_ID = hoi.ORGANIZATION_INFORMATION_ORGANIZATION_ID
    AND hao.ORGANIZATION_UNIT_PEOLOCATION_ID = hc.LOCATION_DETAILS_PEOLOCATION_ID) HOU
    
    ,(SELECT
    receivable_application_id,
    applied_payment_schedule_id,
    gl_date,
    receipt_date,
    display,
    last_update_date,
    application_type,
    status,
    SUM(amount_applied) amount_applied
    FROM
        (  SELECT
                MAX(a.AR_RECEIVABLE_APPLICATION_RECEIVABLE_APPLICATION_ID)
                OVER(PARTITION BY AR_RECEIVABLE_APPLICATION_APPLIED_PAYMENT_SCHEDULE_ID, AR_RECEIVABLE_APPLICATION_GL_DATE, AR_CASH_RECEIPT_RECEIPT_DATE, AR_RECEIVABLE_APPLICATION_DISPLAY, a.AR_RECEIVABLE_APPLICATION_APPLICATION_TYPE,
                                  a.AR_RECEIVABLE_APPLICATION_STATUS) receivable_application_id,
                AR_RECEIVABLE_APPLICATION_APPLIED_PAYMENT_SCHEDULE_ID as applied_payment_schedule_id,
                AR_RECEIVABLE_APPLICATION_GL_DATE as gl_date,
                AR_CASH_RECEIPT_RECEIPT_DATE as receipt_date,
                AR_RECEIVABLE_APPLICATION_DISPLAY as display,
                MAX(a.AR_RECEIVABLE_APPLICATION_LAST_UPDATE_DATE)
                OVER(PARTITION BY AR_RECEIVABLE_APPLICATION_APPLIED_PAYMENT_SCHEDULE_ID, AR_RECEIVABLE_APPLICATION_GL_DATE, AR_CASH_RECEIPT_RECEIPT_DATE, AR_RECEIVABLE_APPLICATION_DISPLAY, a.AR_RECEIVABLE_APPLICATION_APPLICATION_TYPE,
                                  a.AR_RECEIVABLE_APPLICATION_STATUS) last_update_date,
                a.AR_RECEIVABLE_APPLICATION_APPLICATION_TYPE as application_type,
                a.AR_RECEIVABLE_APPLICATION_STATUS as status,
                AR_RECEIVABLE_APPLICATION_AMOUNT_APPLIED as amount_applied
            FROM
                CES_ERP.FSCM_PROD_FINEXTRACT_ARBICCEXTRACT.RECEIVABLE_APPLICATION_EXTRACT_PVO a --FscmTopModelAM.FinExtractAM.ArBiccExtractAM.ReceivableApplicationExtractPVO
                LEFT JOIN CES_ERP.FSCM_PROD_FINEXTRACT_ARBICCEXTRACT.RECEIPT_HEADER_EXTRACT_PVO cr  --FscmTopModelAM.FinExtractAM.ArBiccExtractAM.ReceiptHeaderExtractPVO
                 ON cr.AR_CASH_RECEIPT_CASH_RECEIPT_ID = a.AR_RECEIVABLE_APPLICATION_CASH_RECEIPT_ID
        )
    GROUP BY
        receivable_application_id,
        applied_payment_schedule_id,
        gl_date,
        receipt_date,
        display,
        last_update_date,
        application_type,
        status) AR_REC_APP_ALL
        
    ,CES_ERP.FSCM_PROD_FINEXTRACT_FUNBICCEXTRACT.BUSINESS_UNIT_EXTRACT_PVO BU --FscmTopModelAM.FinExtractAM.FunBiccExtractAM.BusinessUnitExtractPVO
    WHERE 
    CTA.RA_CUSTOMER_TRX_ORG_ID = BU.FUN_BU_PERF_PEOBUSINESS_UNIT_ID
    AND AR_REC_APP_ALL.APPLIED_PAYMENT_SCHEDULE_ID(+) = PS.AR_PAYMENT_SCHEDULE_PAYMENT_SCHEDULE_ID
    AND HP.CUSTOMER_ACCOUNT_CUST_ACCOUNT_ID = PS.AR_PAYMENT_SCHEDULE_CUSTOMER_ID
    AND PS.AR_PAYMENT_SCHEDULE_CUSTOMER_TRX_ID=CTA.RA_CUSTOMER_TRX_CUSTOMER_TRX_ID
    AND CTA.RA_CUSTOMER_TRX_CUST_TRX_TYPE_SEQ_ID = RCTT.RA_CUST_TRX_TYPE_CUST_TRX_TYPE_SEQ_ID
    AND HOU.ORGANIZATION_ID=CTA.RA_CUSTOMER_TRX_ORG_ID
    --AND HP.PARTY_PARTY_ID=HCA.PARTY_ID
    AND PS.AR_PAYMENT_SCHEDULE_PAYMENT_SCHEDULE_CLASS_1 IN ('INV','DM')
) AR_TAB
WHERE (1=1)
AND AR_TAB.AMOUNT_DUE_ORIGINAL<>0

UNION ALL /*FOR CREDIT MEMO*/

SELECT 
AR_TAB.PAYMENT_SCHEDULE_ID,
AR_TAB.ACCOUNT_NUMBER ,
AR_TAB.PARTY_NAME,
AR_TAB.CUSTOMER_TRX_ID,
AR_TAB.CLASS,
AR_TAB.TRANS_TYPE,
AR_TAB.TRANS_TYPE_NAME,
AR_TAB.CUST_TRX_TYPE_ID,
AR_TAB.INVOICE_CURRENCY_CODE,
AR_TAB.LOCATION_CODE,
AR_TAB.TRANSACTION_NUMBER,
to_char(AR_TAB.TRANS_DATE,'YYYY-MM-DD HH24:MI:SS') as TRANS_DATE,
to_char(AR_TAB.GL_DATE_PS,'YYYY-MM-DD HH24:MI:SS') as GL_DATE_PS,
to_char(AR_TAB.DUE_DATE,'YYYY-MM-DD HH24:MI:SS') as DUE_DATE,
AR_TAB.AMOUNT_DUE_ORIGINAL,
AR_TAB.AMOUNT_DUE_ORIGINAL_EXCH,
AR_TAB.EXCHANGE_RATE,
AR_TAB.AMOUNT_DUE_REMAINING,
AR_TAB.ACCTD_AMOUNT_DUE_REMAINING,
NVL(AR_TAB.RECEIVABLE_APPLICATION_ID,0) RECEIVABLE_APPLICATION_ID,
AR_TAB.PAYMENT_SCHEDULE_ID_AR,
NVL(to_char(AR_TAB.GL_DATE_AR,'YYYY-MM-DD HH24:MI:SS'),'2900-01-01 00:00:00') as GL_DATE_AR,
to_char(AR_TAB.RECEIPT_DATE,'YYYY-MM-DD HH24:MI:SS') as RECEIPT_DATE,
AR_TAB.AMOUNT_APPLIED,
AR_TAB.DISPLAY_AR,
AR_TAB.APPLICATION_TYPE, 
AR_TAB.STATUS,
(CASE WHEN AR_TAB.LAST_UPDATE_DATE > NVL(AR_TAB.LAST_UPDATE_DATE_AR, TO_TIMESTAMP('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')) THEN 
to_char(AR_TAB.LAST_UPDATE_DATE,'YYYY-MM-DD HH24:MI:SS') ELSE 
to_char(AR_TAB.LAST_UPDATE_DATE_AR,'YYYY-MM-DD HH24:MI:SS') END)  LAST_UPDATE_DATE,
AR_TAB.BU_NAME
FROM
(
    SELECT    
    PS.AR_PAYMENT_SCHEDULE_PAYMENT_SCHEDULE_ID as PAYMENT_SCHEDULE_ID,
    HP.CUSTOMER_ACCOUNT_ACCOUNT_NUMBER as ACCOUNT_NUMBER,
    HP.PARTY_PARTY_NAME as PARTY_NAME,
    CTA.RA_CUSTOMER_TRX_CUSTOMER_TRX_ID as CUSTOMER_TRX_ID,
    PS.AR_PAYMENT_SCHEDULE_PAYMENT_SCHEDULE_CLASS_1 as CLASS,
    DECODE(PS.AR_PAYMENT_SCHEDULE_PAYMENT_SCHEDULE_CLASS_1,'INV', 'INVOICE', 'DM', 'DEBIT MEMO','CM','CREDIT MEMO') TRANS_TYPE,
    RCTT.RA_CUST_TRX_TYPE_NAME TRANS_TYPE_NAME,
    RCTT.RA_CUST_TRX_TYPE_CUST_TRX_TYPE_ID as CUST_TRX_TYPE_ID,
    CTA.RA_CUSTOMER_TRX_INVOICE_CURRENCY_CODE as INVOICE_CURRENCY_CODE,
    HOU.LOCATION_CODE,
    PS.AR_PAYMENT_SCHEDULE_TRX_NUMBER TRANSACTION_NUMBER,
    PS.AR_PAYMENT_SCHEDULE_TRX_DATE TRANS_DATE,
    PS.AR_PAYMENT_SCHEDULE_GL_DATE GL_DATE_PS,
    PS.AR_PAYMENT_SCHEDULE_DUE_DATE as DUE_DATE,
    PS.AR_PAYMENT_SCHEDULE_AMOUNT_DUE_ORIGINAL as AMOUNT_DUE_ORIGINAL,
    ROUND((PS.AR_PAYMENT_SCHEDULE_AMOUNT_DUE_ORIGINAL * NVL(PS.AR_PAYMENT_SCHEDULE_EXCHANGE_RATE,1)),2) AMOUNT_DUE_ORIGINAL_EXCH,
    NVL(PS.AR_PAYMENT_SCHEDULE_EXCHANGE_RATE,1) EXCHANGE_RATE,
    PS.AR_PAYMENT_SCHEDULE_AMOUNT_DUE_REMAINING as AMOUNT_DUE_REMAINING,
    PS.AR_PAYMENT_SCHEDULE_ACCTD_AMOUNT_DUE_REMAINING as ACCTD_AMOUNT_DUE_REMAINING,
    AR_REC_APP_ALL.RECEIVABLE_APPLICATION_ID,
    AR_REC_APP_ALL.PAY_SCHED_ID PAYMENT_SCHEDULE_ID_AR,
    AR_REC_APP_ALL.GL_DATE GL_DATE_AR,
    AR_REC_APP_ALL.RECEIPT_DATE,
    AR_REC_APP_ALL.AMOUNT_APPLIED,
    AR_REC_APP_ALL.DISPLAY DISPLAY_AR,
    AR_REC_APP_ALL.APPLICATION_TYPE, 
    AR_REC_APP_ALL.STATUS,    
    AR_REC_APP_ALL.LAST_UPDATE_DATE LAST_UPDATE_DATE_AR,
    PS.AR_PAYMENT_SCHEDULE_LAST_UPDATE_DATE as LAST_UPDATE_DATE,   
    BU.FUN_BU_PERF_PEONAME as BU_NAME
    FROM CES_ERP.FSCM_PROD_FINEXTRACT_ARBICCEXTRACT.PAYMENT_SCHEDULE_EXTRACT_PVO PS --FscmTopModelAM.FinExtractAM.ArBiccExtractAM.PaymentScheduleExtractPVO
    --,CES_ERP.FSCM_PROD_PARTIESANALYTICS.CUSTOMER_ACCOUNT HCA --FscmTopModelAM.PartiesAnalyticsAM.CustomerAccount
    ,CES_ERP.FSCM_PROD_CONTRACTSCORE.CONTRACT_CUSTOMER_ACCOUNT_P HP
    --,CES_ERP.FSCM_PROD_PRCPOZPUBLICVIEW.SUPPLIER_PVO HP --FscmTopModelAM.PrcPozPublicViewAM.SupplierPVO
    ,CES_ERP.FSCM_PROD_FINEXTRACT_ARBICCEXTRACT.TRANSACTION_HEADER_EXTRACT_PVO CTA --FscmTopModelAM.FinExtractAM.ArBiccExtractAM.TransactionHeaderExtractPVO
    ,CES_ERP.FSCM_PROD_FINEXTRACT_ARBICCEXTRACT.TRANSACTION_TYPE_EXTRACT_PVO RCTT --FscmTopModelAM.FinExtractAM.ArBiccExtractAM.TransactionTypeExtractPVO
    ,(SELECT
    hao.ORGANIZATION_ID as organization_id,
    hc.LOCATION_DETAILS_TRANSLATION_PEOLOCATION_CODE as location_code
    FROM
        CES_ERP.FSCM_PROD_ORGANIZATION.ORGANIZATION_UNIT_TRANSLATION_PVO   hao, 
        CES_ERP.FSCM_PROD_FINFUNBUSINESSUNITS.BUSINESS_UNIT_PVO hoi,
        CES_ERP.FSCM_PROD_LOCATION.LOCATION_DETAILS_TRANSLATION_PVOVIEW_ALL hc
    WHERE
        hao.ORGANIZATION_ID = hoi.ORGANIZATION_INFORMATION_ORGANIZATION_ID
    AND hao.ORGANIZATION_UNIT_PEOLOCATION_ID = hc.LOCATION_DETAILS_PEOLOCATION_ID) HOU

    ,(select * from (
    
        SELECT
            receivable_application_id,    pay_sched_id,    payment_schedule_id,    applied_payment_schedule_id,    gl_date,    receipt_date,    display,
            last_update_date,    record_type,    application_type,    status,    SUM(amount_applied) amount_applied
        FROM
            (
                SELECT
                    MAX(a.AR_RECEIVABLE_APPLICATION_RECEIVABLE_APPLICATION_ID)
                    OVER(PARTITION BY a.AR_RECEIVABLE_APPLICATION_PAYMENT_SCHEDULE_ID, a.AR_RECEIVABLE_APPLICATION_APPLIED_PAYMENT_SCHEDULE_ID, a.AR_RECEIVABLE_APPLICATION_GL_DATE, cr.AR_CASH_RECEIPT_RECEIPT_DATE, a.AR_RECEIVABLE_APPLICATION_DISPLAY,
                                      a.AR_RECEIVABLE_APPLICATION_APPLICATION_TYPE, a.AR_RECEIVABLE_APPLICATION_STATUS) receivable_application_id,
                    a.AR_RECEIVABLE_APPLICATION_PAYMENT_SCHEDULE_ID             AS pay_sched_id,
                    a.AR_RECEIVABLE_APPLICATION_PAYMENT_SCHEDULE_ID as payment_schedule_id,
                    a.AR_RECEIVABLE_APPLICATION_APPLIED_PAYMENT_SCHEDULE_ID as applied_payment_schedule_id,
                    a.AR_RECEIVABLE_APPLICATION_GL_DATE as gl_date,
                    cr.AR_CASH_RECEIPT_RECEIPT_DATE as receipt_date,
                    a.AR_RECEIVABLE_APPLICATION_DISPLAY as display,
                    a.AR_RECEIVABLE_APPLICATION_APPLICATION_TYPE as application_type,
                    a.AR_RECEIVABLE_APPLICATION_STATUS as status,
                    a.AR_RECEIVABLE_APPLICATION_AMOUNT_APPLIED as amount_applied,
                    MAX(a.AR_RECEIVABLE_APPLICATION_LAST_UPDATE_DATE)
                    OVER(PARTITION BY a.AR_RECEIVABLE_APPLICATION_PAYMENT_SCHEDULE_ID, a.AR_RECEIVABLE_APPLICATION_APPLIED_PAYMENT_SCHEDULE_ID, a.AR_RECEIVABLE_APPLICATION_GL_DATE, cr.AR_CASH_RECEIPT_RECEIPT_DATE, a.AR_RECEIVABLE_APPLICATION_DISPLAY,
                                      a.AR_RECEIVABLE_APPLICATION_APPLICATION_TYPE, a.AR_RECEIVABLE_APPLICATION_STATUS) last_update_date,
                    'PAYMENT_SCHEDULE_ID' record_type
                FROM
                    CES_ERP.FSCM_PROD_FINEXTRACT_ARBICCEXTRACT.RECEIVABLE_APPLICATION_EXTRACT_PVO a --FscmTopModelAM.FinExtractAM.ArBiccExtractAM.ReceivableApplicationExtractPVO
                    INNER JOIN CES_ERP.FSCM_PROD_FINEXTRACT_ARBICCEXTRACT.PAYMENT_SCHEDULE_EXTRACT_PVO ps ON a.AR_RECEIVABLE_APPLICATION_PAYMENT_SCHEDULE_ID = ps.AR_PAYMENT_SCHEDULE_PAYMENT_SCHEDULE_ID --FscmTopModelAM.FinExtractAM.ArBiccExtractAM.PaymentScheduleExtractPVO
                    LEFT JOIN CES_ERP.FSCM_PROD_FINEXTRACT_ARBICCEXTRACT.RECEIPT_HEADER_EXTRACT_PVO     cr ON cr.AR_CASH_RECEIPT_CASH_RECEIPT_ID = a.AR_RECEIVABLE_APPLICATION_CASH_RECEIPT_ID --FscmTopModelAM.FinExtractAM.ArBiccExtractAM.ReceiptHeaderExtractPVO
                WHERE
                    ps.AR_PAYMENT_SCHEDULE_PAYMENT_SCHEDULE_CLASS_1 = 'CM'
            )
        GROUP BY
            receivable_application_id,    pay_sched_id,    payment_schedule_id,    applied_payment_schedule_id,    gl_date,    receipt_date,
            display,    last_update_date,    record_type,    application_type,    status
      
      UNION

        SELECT
            receivable_application_id,    pay_sched_id,    payment_schedule_id,    applied_payment_schedule_id,    gl_date,    receipt_date,    display,
            last_update_date,    record_type,    application_type,    status,    SUM(amount_applied) amount_applied
        FROM
            (
                SELECT
                    MAX(a.AR_RECEIVABLE_APPLICATION_RECEIVABLE_APPLICATION_ID)
                    OVER(PARTITION BY a.AR_RECEIVABLE_APPLICATION_PAYMENT_SCHEDULE_ID, a.AR_RECEIVABLE_APPLICATION_APPLIED_PAYMENT_SCHEDULE_ID, a.AR_RECEIVABLE_APPLICATION_GL_DATE, cr.AR_CASH_RECEIPT_RECEIPT_DATE, a.AR_RECEIVABLE_APPLICATION_DISPLAY,
                                      a.AR_RECEIVABLE_APPLICATION_APPLICATION_TYPE, a.AR_RECEIVABLE_APPLICATION_STATUS) receivable_application_id,
                    a.AR_RECEIVABLE_APPLICATION_APPLIED_PAYMENT_SCHEDULE_ID     AS pay_sched_id,
                    a.AR_RECEIVABLE_APPLICATION_PAYMENT_SCHEDULE_ID as payment_schedule_id,
                    a.AR_RECEIVABLE_APPLICATION_APPLIED_PAYMENT_SCHEDULE_ID as applied_payment_schedule_id,
                    a.AR_RECEIVABLE_APPLICATION_GL_DATE as gl_date,
                    cr.AR_CASH_RECEIPT_RECEIPT_DATE as receipt_date,
                    a.AR_RECEIVABLE_APPLICATION_DISPLAY as display,
                    a.AR_RECEIVABLE_APPLICATION_APPLICATION_TYPE as application_type,
                    a.AR_RECEIVABLE_APPLICATION_STATUS as status,
                    a.AR_RECEIVABLE_APPLICATION_AMOUNT_APPLIED as amount_applied,
                    MAX(a.AR_RECEIVABLE_APPLICATION_LAST_UPDATE_DATE)
                    OVER(PARTITION BY a.AR_RECEIVABLE_APPLICATION_PAYMENT_SCHEDULE_ID, a.AR_RECEIVABLE_APPLICATION_APPLIED_PAYMENT_SCHEDULE_ID, a.AR_RECEIVABLE_APPLICATION_GL_DATE, cr.AR_CASH_RECEIPT_RECEIPT_DATE, a.AR_RECEIVABLE_APPLICATION_DISPLAY,
                                      a.AR_RECEIVABLE_APPLICATION_APPLICATION_TYPE, a.AR_RECEIVABLE_APPLICATION_STATUS) last_update_date,
                    'APPLIED_PAYMENT_SCHEDULE_ID'     record_type
                FROM
                    CES_ERP.FSCM_PROD_FINEXTRACT_ARBICCEXTRACT.RECEIVABLE_APPLICATION_EXTRACT_PVO a --FscmTopModelAM.FinExtractAM.ArBiccExtractAM.ReceivableApplicationExtractPVO
                    INNER JOIN CES_ERP.FSCM_PROD_FINEXTRACT_ARBICCEXTRACT.PAYMENT_SCHEDULE_EXTRACT_PVO ps ON a.AR_RECEIVABLE_APPLICATION_APPLIED_PAYMENT_SCHEDULE_ID = ps.AR_PAYMENT_SCHEDULE_PAYMENT_SCHEDULE_ID --FscmTopModelAM.FinExtractAM.ArBiccExtractAM.PaymentScheduleExtractPVO
                    LEFT JOIN CES_ERP.FSCM_PROD_FINEXTRACT_ARBICCEXTRACT.RECEIPT_HEADER_EXTRACT_PVO     cr ON cr.AR_CASH_RECEIPT_CASH_RECEIPT_ID = a.AR_RECEIVABLE_APPLICATION_CASH_RECEIPT_ID --FscmTopModelAM.FinExtractAM.ArBiccExtractAM.ReceiptHeaderExtractPVO
                WHERE 
                    ps.AR_PAYMENT_SCHEDULE_PAYMENT_SCHEDULE_CLASS_1 = 'CM'
            )
        GROUP BY
            receivable_application_id,    pay_sched_id,    payment_schedule_id,    applied_payment_schedule_id,    gl_date,    receipt_date,    display,
            last_update_date,    record_type,    application_type,    status
      )
      
      ) AR_REC_APP_ALL 
    ,CES_ERP.FSCM_PROD_FINEXTRACT_FUNBICCEXTRACT.BUSINESS_UNIT_EXTRACT_PVO BU --FscmTopModelAM.FinExtractAM.FunBiccExtractAM.BusinessUnitExtractPVO
    
    WHERE 
    CTA.RA_CUSTOMER_TRX_ORG_ID = BU.FUN_BU_PERF_PEOBUSINESS_UNIT_ID
    AND AR_REC_APP_ALL.PAY_SCHED_ID(+) = PS.AR_PAYMENT_SCHEDULE_PAYMENT_SCHEDULE_ID
    AND HP.CUSTOMER_ACCOUNT_CUST_ACCOUNT_ID = PS.AR_PAYMENT_SCHEDULE_CUSTOMER_ID
    AND PS.AR_PAYMENT_SCHEDULE_CUSTOMER_TRX_ID=CTA.RA_CUSTOMER_TRX_CUSTOMER_TRX_ID
    AND CTA.RA_CUSTOMER_TRX_CUST_TRX_TYPE_SEQ_ID = RCTT.RA_CUST_TRX_TYPE_CUST_TRX_TYPE_SEQ_ID
    AND HOU.ORGANIZATION_ID=CTA.RA_CUSTOMER_TRX_ORG_ID
    --AND HP.PARTY_PARTY_ID=HCA.PARTY_ID
    AND PS.AR_PAYMENT_SCHEDULE_PAYMENT_SCHEDULE_CLASS_1 = 'CM'
    
) AR_TAB
WHERE (1=1)
AND AR_TAB.AMOUNT_DUE_ORIGINAL<>0
) MAIN_TAB
ORDER BY 
PAYMENT_SCHEDULE_ID,
CUSTOMER_TRX_ID,
GL_DATE_PS,
GL_DATE_AR