{%- set trimmed_source_name = model.name | replace("ERP_STAGE_","") -%}

{{
    config(
        alias= trimmed_source_name,
        materialized = 'incremental',
        incremental_strategy = 'merge',
        unique_key = 'ID',
        post_hook=[
         "UPDATE COMMON_{{target.name.upper()}}.ERP.CONTROL_TIME_INCREMENTAL_LOAD
            SET LAST_UPDATED_TIMESTAMP = CAST(CONVERT_TIMEZONE('Australia/Sydney', CURRENT_TIMESTAMP()) AS TIMESTAMP_NTZ)
            WHERE TABLE_NAME = '{{( model.name | replace('ERP_STAGE_',''))}}'"
                  ]
    )
}}


WITH 
{% if is_incremental() %} 
max_date AS (
    SELECT MAX(INCREMENTAL_LATEST_DATE) as latest_date 
    FROM {{this}}
),  {% endif %}
organizationunit AS (
SELECT 
            organizationunit.ORGANIZATION_ID      AS organization_id_1,
            organizationunit.EFFECTIVE_START_DATE AS effective_start_date_1,
            organizationunit.EFFECTIVE_END_DATE   AS effective_end_date_1,
            organizationunit.ORG_INFO_BUPEOORG_INFORMATION_ID as org_information_id,
            organizationunit.ORGANIZATION_UNIT_TRANSLATION_PEONAME as name,
            organizationunit.ORGANIZATION_UNIT_TRANSLATION_PEOORGANIZATION_ID as organization_id,
            organizationunit.ORGANIZATION_UNIT_TRANSLATION_PEOEFFECTIVE_START_DATE as effective_start_date,
            organizationunit.ORGANIZATION_UNIT_TRANSLATION_PEOEFFECTIVE_END_DATE as effective_end_date,
            organizationunit.ORGANIZATION_UNIT_TRANSLATION_PEOLANGUAGE as language
        FROM CES_ERP.FSCM_PROD_ORGANIZATION.ORGANIZATION_UNIT_PVO organizationunit
        WHERE ( ( DATE_TRUNC('DAY',  CAST(CONVERT_TIMEZONE('Australia/Sydney', CURRENT_TIMESTAMP) AS TIMESTAMP))) BETWEEN     
        organizationunit.EFFECTIVE_START_DATE AND organizationunit.EFFECTIVE_END_DATE )
        AND (( DATE_TRUNC('DAY',  CAST(CONVERT_TIMEZONE('Australia/Sydney', CURRENT_TIMESTAMP) AS TIMESTAMP))) BETWEEN 
        organizationunit.ORG_INFO_BUPEOEFFECTIVE_START_DATE AND organizationunit.ORG_INFO_BUPEOEFFECTIVE_END_DATE )
        AND ((DATE_TRUNC('DAY',  CAST(CONVERT_TIMEZONE('Australia/Sydney', CURRENT_TIMESTAMP) AS TIMESTAMP))) BETWEEN 
        organizationunit.ORGANIZATION_UNIT_TRANSLATION_PEOEFFECTIVE_START_DATE AND organizationunit.ORGANIZATION_UNIT_TRANSLATION_PEOEFFECTIVE_END_DATE)
),
purchaseorder AS (
   SELECT *
    FROM (
        SELECT *,
               ROW_NUMBER() OVER (PARTITION BY PURCHASING_DOCUMENT_HEADER_PO_HEADER_ID ORDER BY SEQUENCE_NUM DESC) AS rn
        FROM CES_ERP.FSCM_PROD_PRCPOPUBLICVIEW.PURCHASE_ORDER_HISTORY_PVO
    ) AS po
    WHERE 
    rn = 1
),
biflexfieldeo_b AS (
    SELECT 
    biflexfieldeo.AP_INVOICES_INVOICE_ID AS s_k_5000,
    CASE 
        WHEN biflexfieldeo.AP_INVOICES_GLOBAL_ATTRIBUTE_CATEGORY = 'JExESOnlineVatReporting' THEN biflexfieldeo.AP_INVOICES_GLOBAL_ATTRIBUTE_DATE_1
        ELSE NULL 
    END AS datelastupdated_,
    CASE 
        WHEN biflexfieldeo.AP_INVOICES_GLOBAL_ATTRIBUTE_CATEGORY = 'JExRUInvoices' THEN biflexfieldeo.AP_INVOICES_GLOBAL_ATTRIBUTE_DATE_3
        ELSE NULL 
    END AS revisiondate_,
    CASE 
        WHEN biflexfieldeo.AP_INVOICES_GLOBAL_ATTRIBUTE_CATEGORY = 'JExRUInvoices' THEN biflexfieldeo.AP_INVOICES_GLOBAL_ATTRIBUTE_8
        ELSE NULL 
    END AS revisionnumber_,
    CASE 
        WHEN biflexfieldeo.AP_INVOICES_GLOBAL_ATTRIBUTE_CATEGORY = 'JL_BR_APXINWKB_AP_INVOICES' THEN biflexfieldeo.AP_INVOICES_GLOBAL_ATTRIBUTE_NUMBER_1
        ELSE NULL 
    END AS withheld_tax_amount_
    FROM
    CES_ERP.FSCM_PROD_FINEXTRACT_APBICCEXTRACT.INVOICE_HEADER_EXTRACT_PVO biflexfieldeo
    )
    ,VIEW_A AS (
    SELECT  
    CONCATENATED_SEGMENTS,
    ENTITY_CODE,
    COST_CENTRE_CODE,
    ACCOUNT_CODE,
    INTERCOMPANY_CODE,
    MATERIAL_TYPE_CODE,
    SCHEME_CODE,
    PROJECT_CODE,
    IDENTIFYING_PO,
    INVOICE_DATE,
    INVOICE_ID,
    INVOICE_NUM,
    INVOICE_TYPE_CODE,
    INVOICE_TYPE_NAME,
    INVOICES_DATE_LAST_UPDATED,
    INVOICES_REVISION_DATE,
    INVOICES_REVISION_NUMBER,
    INVOICES_WITHHELD_TAX_AMOUNT,
    TERMS_DATE,
    INV_DIST_ACCOUNTING_DATE,
    DISTRIBUTION_DESC,
    DISTRIBUTION_LINE_NUM,
    DISTRIBUTION_UNIT_PRICE,
    INV_DIST_POSTING_STATUS,
    INV_DIST_REVERSAL_STATUS,
    MATCH_STATUS,
    INVOICE_CURRENCY,
    INV_LINE_LAST_UPDATE_DATE,
    LINE_NUMBER,
    MATCH_TYPE,
    QUANTITY_INVOICED,
    UNIT_PRICE,
    BUSINESS_UNIT_NAME,
    FISCAL_PERIOD,
    LEDGER_NAME,
    LEGAL_ENTITY_NAME,
    SUPPLIER_SITE_CODE,
    SUPPLIER_NUMBER,
    MATCH_STATUS_CODE,
    MATCH_TYPE_CODE,
    INVOICE_AMOUNT,
    SUM( TOTAL_DISTRIBUTION_AMOUNT)  TOTAL_DISTRIBUTION_AMOUNT,
    SUPPLIER_NAME,
    INVOICE_SOURCE_NAME,
    PAY_GROUP,
    ACCOUNTING_DATE,
    INVOICE_DESC,
    PAYMENT_TERMS,
    INV_CREATION_DATE,
    TERM_ID,
    ORG_ID,
    LEGAL_ENT_ID,
    LEDGER_ID,
    FISCAL_YEAR_ID_1, 
    FISCAL_YEAR_ID_2,
    POSTED_FLAG,
    REVERSAL_FLAG,
    AP_INVOICES_LAST_UPDATE_DATE,
    INV_DIST_LAST_UPDATE_DATE,
    SUPPLIER_LATEST_DATE,
    INCREMENTAL_LATEST_DATE,
    SUPPLIER_DIST_VENDOR_ID
FROM
(
SELECT 
    biflexfieldeo_a.concat_values            AS CONCATENATED_SEGMENTS,
    biflexfieldeo_a.gl_balancing_            AS ENTITY_CODE,
    biflexfieldeo_a.fa_cost_ctr_             AS COST_CENTRE_CODE,
    biflexfieldeo_a.gl_account_              AS ACCOUNT_CODE,
    biflexfieldeo_a.gl_mat_type_             AS INTERCOMPANY_CODE,
    biflexfieldeo_a.gl_intercompany_         AS MATERIAL_TYPE_CODE,
    biflexfieldeo_a.gl_scheme_               AS SCHEME_CODE,
    biflexfieldeo_a.gl_scheme_              AS PROJECT_CODE,
    purchaseorder.PURCHASING_DOCUMENT_HEADER_SEGMENT_1 AS IDENTIFYING_PO,
    invoiceheader.AP_INVOICES_INVOICE_DATE AS INVOICE_DATE,
    invoiceline.AP_INVOICE_LINES_ALL_INVOICE_ID AS INVOICE_ID,  --  CAST(invoiceheader.AP_INVOICES_INVOICE_ID as  VARCHAR ( 100 ) ) 
    invoiceheader.AP_INVOICES_INVOICE_NUM AS INVOICE_NUM,
    invoiceheader.AP_INVOICES_INVOICE_TYPE_LOOKUP_CODE AS INVOICE_TYPE_CODE,
    invpayableslookup.DISPLAYED_FIELD as INVOICE_TYPE_NAME,
    biflexfieldeo_b.datelastupdated_   as  INVOICES_DATE_LAST_UPDATED,   
    biflexfieldeo_b.revisiondate_            AS INVOICES_REVISION_DATE,	
    biflexfieldeo_b.revisionnumber_          AS INVOICES_REVISION_NUMBER,	
    biflexfieldeo_b.withheld_tax_amount_     AS INVOICES_WITHHELD_TAX_AMOUNT,
    invoiceheader.AP_INVOICES_TERMS_DATE AS TERMS_DATE,
    invoicedistribution.AP_INVOICE_DISTRIBUTIONS_ACCOUNTING_DATE  INV_DIST_ACCOUNTING_DATE,
    invoicedistribution.AP_INVOICE_DISTRIBUTIONS_DESCRIPTION AS DISTRIBUTION_DESC,
    invoicedistribution.AP_INVOICE_DISTRIBUTIONS_DISTRIBUTION_LINE_NUMBER AS DISTRIBUTION_LINE_NUM,
    invoicedistribution.AP_INVOICE_DISTRIBUTIONS_UNIT_PRICE AS DISTRIBUTION_UNIT_PRICE,
    invoicedistribution.AP_INVOICE_DISTRIBUTIONS_LAST_UPDATE_DATE AS INV_DIST_LAST_UPDATE_DATE,   
    nvl(posted_flag_code.MEANING, invoicedistribution.AP_INVOICE_DISTRIBUTIONS_POSTED_FLAG) as INV_DIST_POSTING_STATUS, --posted
    nvl(reversal_flag_code.MEANING, invoicedistribution.AP_INVOICE_DISTRIBUTIONS_REVERSAL_FLAG) as INV_DIST_REVERSAL_STATUS, --reversal 
    inv_dist_match.MEANING AS MATCH_STATUS, -- AP_INVOICE_DISTRIBUTIONS_MATCH_STATUS_FLAG as MATCH_STATUS,   --- A  inv_dist_match.MEANING
    invoiceheader.AP_INVOICES_INVOICE_CURRENCY_CODE AS INVOICE_CURRENCY,
    invoiceline.AP_INVOICE_LINES_ALL_LAST_UPDATE_DATE AS INV_LINE_LAST_UPDATE_DATE,
    invoiceline.AP_INVOICE_LINES_ALL_LINE_NUMBER AS LINE_NUMBER,
    case  when not  invoiceline.AP_INVOICE_LINES_ALL_MATCH_TYPE like '%CORR%' then nvl(match_type.MEANING, invoiceline.AP_INVOICE_LINES_ALL_MATCH_TYPE) end  as MATCH_TYPE,
    invoiceline.AP_INVOICE_LINES_ALL_QUANTITY_INVOICED AS QUANTITY_INVOICED,
    invoiceline.AP_INVOICE_LINES_ALL_UNIT_PRICE AS UNIT_PRICE,
    organizationunit.name  AS BUSINESS_UNIT_NAME,  
    fiscalday.FISCAL_PERIOD_NAME as FISCAL_PERIOD,
    ledger.LEDGER_NAME AS LEDGER_NAME, 
    legalentity.LEGAL_ENTITY_NAME LEGAL_ENTITY_NAME,
    suppliersite.SUPPLIER_SITE_VENDOR_SITE_CODE AS SUPPLIER_SITE_CODE,
    supplier.SUPPLIER_SEGMENT_1  AS SUPPLIER_NUMBER,  -- 10041968 invoiceheader.AP_INVOICES_VENDOR_ID 
    CASE invoicedistribution.AP_INVOICE_DISTRIBUTIONS_MATCH_STATUS_FLAG
    WHEN 'A' THEN 'APPROVED'
    WHEN 'N' THEN 'NEEDS REAPPROVAL'
    ELSE 'NEVER APPROVED'
    END  AS MATCH_STATUS_CODE,   -- APPROVED
    UPPER(case  when not  invoiceline.AP_INVOICE_LINES_ALL_MATCH_TYPE like '%CORR%' then nvl(match_type.MEANING, invoiceline.AP_INVOICE_LINES_ALL_MATCH_TYPE) END) AS MATCH_TYPE_CODE,
    invoiceheader.AP_INVOICES_INVOICE_AMOUNT   AS INVOICE_AMOUNT,  -- 48.1
    invoicedistribution.AP_INVOICE_DISTRIBUTIONS_TOTAL_DIST_AMOUNT AS TOTAL_DISTRIBUTION_AMOUNT,
    supplier.PARTY_PARTY_NAME as SUPPLIER_NAME,  
    sourcepayableslookup.DISPLAYED_FIELD as INVOICE_SOURCE_NAME,
    nvl(pay_group_code.MEANING , invoiceheader.AP_INVOICES_PAY_GROUP_LOOKUP_CODE)  as PAY_GROUP,
    fiscalday.REPORT_DATE as ACCOUNTING_DATE,
    invoiceheader.AP_INVOICES_DESCRIPTION AS INVOICE_DESC,
    nvl(term_id_code.code_name, to_char(invoiceheader.AP_INVOICES_TERMS_ID)) as PAYMENT_TERMS,
    invoiceheader.AP_INVOICES_CREATION_DATE AS INV_CREATION_DATE,
    invoiceheader.AP_INVOICES_TERMS_ID TERM_ID,
    invoiceheader.AP_INVOICES_ORG_ID AS ORG_ID,
    invoiceheader.AP_INVOICES_LEGAL_ENTITY_ID AS LEGAL_ENT_ID,
    invoiceheader.AP_INVOICES_SET_OF_BOOKS_ID LEDGER_ID,
    fiscalday.GL_CALENDARS_CALENDAR_ID * 10000000000 + TO_NUMBER(TO_CHAR(fiscalday.REPORT_DATE, 'yyyy'), '9999') * 1000000 + TO_NUMBER(TO_CHAR(fiscalday.REPORT_DATE, 'MM'), '99') * 
    10000 + TO_NUMBER(TO_CHAR(fiscalday.REPORT_DATE, 'dd'), '99') * 100 + fiscalday.FISCAL_PERIOD_NUMBER AS FISCAL_YEAR_ID_1, 
    fiscalday.FISCAL_YEAR_NUMBER * 10000 + fiscalday.GL_CALENDARS_CALENDAR_ID * 100000000 + fiscalday.FISCAL_QUARTER_NUMBER* 100 +       fiscalday.FISCAL_PERIOD_NUMBER  AS    FISCAL_YEAR_ID_2,
    invoiceheader.AP_INVOICES_LAST_UPDATE_DATE as AP_INVOICES_LAST_UPDATE_DATE,
GREATEST(NVL(invoiceheader.AP_INVOICES_LAST_UPDATE_DATE,to_timestamp('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')),NVL(invoicedistribution.AP_INVOICE_DISTRIBUTIONS_LAST_UPDATE_DATE,to_timestamp('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')),NVL(supplier.SUPPLIER_LAST_UPDATE_DATE,to_timestamp('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS'))) AS      INCREMENTAL_LATEST_DATE,
    invoicedistribution.AP_INVOICE_DISTRIBUTIONS_POSTED_FLAG AS POSTED_FLAG,
    invoicedistribution.AP_INVOICE_DISTRIBUTIONS_REVERSAL_FLAG AS REVERSAL_FLAG ,
    supplier.SUPPLIER_LAST_UPDATE_DATE as SUPPLIER_LATEST_DATE,
    supplier.SUPP_INV_DIST_VENDOR_ID as SUPPLIER_DIST_VENDOR_ID
FROM 
CES_ERP.FSCM_PROD_FINEXTRACT_APBICCEXTRACT.INVOICE_DISTRIBUTION_EXTRACT_PVO invoicedistribution
JOIN CES_ERP.FSCM_PROD_FINEXTRACT_APBICCEXTRACT.INVOICE_LINE_EXTRACT_PVO invoiceline 
ON invoicedistribution.AP_INVOICE_DISTRIBUTIONS_INVOICE_ID = invoiceline.AP_INVOICE_LINES_ALL_INVOICE_ID AND invoicedistribution.AP_INVOICE_DISTRIBUTIONS_INVOICE_LINE_NUMBER = invoiceline.AP_INVOICE_LINES_ALL_LINE_NUMBER
JOIN CES_ERP.FSCM_PROD_FINEXTRACT_APBICCEXTRACT.INVOICE_HEADER_EXTRACT_PVO invoiceheader 
ON invoiceline.AP_INVOICE_LINES_ALL_INVOICE_ID = invoiceheader.AP_INVOICES_INVOICE_ID
LEFT JOIN ( select * from purchaseorder) purchaseorder 
ON invoiceheader.AP_INVOICES_PO_HEADER_ID = purchaseorder.PURCHASING_DOCUMENT_HEADER_PO_HEADER_ID 
JOIN CES_ERP.FSCM_PROD_FINEXTRACT_GLBICCEXTRACT.LEDGER_EXTRACT_PVO ledgerinvdist 
ON invoicedistribution.AP_INVOICE_DISTRIBUTIONS_SET_OF_BOOKS_ID = ledgerinvdist.LEDGER_LEDGER_ID
LEFT JOIN CES_ERP.FSCM_PROD_PRCPOZPUBLICVIEW.SUPPLIER_PVO supplier 
ON invoiceheader.AP_INVOICES_VENDOR_ID = supplier.SUPP_INV_DIST_VENDOR_ID
LEFT JOIN CES_ERP.FSCM_PROD_FINEXTRACT_XLEBICCEXTRACT.LEGAL_ENTITY_EXTRACT_PVO legalentity 
ON invoiceheader.AP_INVOICES_LEGAL_ENTITY_ID = legalentity.LEGAL_ENTITY_LEGAL_ENTITY_ID
LEFT JOIN CES_ERP.FSCM_PROD_PRCPOZPUBLICVIEW.SUPPLIER_SITE_PVO suppliersite  
ON invoiceheader.AP_INVOICES_VENDOR_SITE_ID  = suppliersite.VENDOR_SITE_ID
LEFT JOIN CES_ERP.FSCM_PROD_FINAPSHAREDCORE.SOURCE_LOOKUP_PVO sourcepayableslookup  
ON invoiceheader.AP_INVOICES_SOURCE  = sourcepayableslookup.LOOKUP_CODE
LEFT JOIN CES_ERP.FSCM_PROD_FINAPSHAREDCORE.INVOICE_TYPE_LOOKUP_PVO invpayableslookup  
ON invoiceheader.AP_INVOICES_INVOICE_TYPE_LOOKUP_CODE =  invpayableslookup.LOOKUP_CODE
LEFT JOIN CES_ERP.FSCM_PROD_FINGLCALACC.FISCAL_DAY_PVO fiscalday  
ON invoiceheader.AP_INVOICES_INVOICE_DATE = fiscalday.REPORT_DATE   AND    'N' = fiscalday.FISCAL_PERIOD_ADJUSTMENT_PERIOD_FLAG   AND invoiceheader.AP_INVOICES_SET_OF_BOOKS_ID = fiscalday.LEDGER_ID
JOIN (select * from organizationunit)  organizationunit  
ON invoiceheader.AP_INVOICES_ORG_ID =  organizationunit.organization_id_1 
JOIN CES_ERP.FSCM_PROD_FINEXTRACT_GLBICCEXTRACT.LEDGER_EXTRACT_PVO ledger ON invoiceheader.AP_INVOICES_SET_OF_BOOKS_ID =  ledger.LEDGER_LEDGER_ID 
LEFT JOIN (SELECT 
biflexfieldeo.CODE_COMBINATION_CODE_COMBINATION_ID   AS s_g_0,
biflexfieldeo.CODE_COMBINATION_CHART_OF_ACCOUNTS_ID   AS s_g_1,
CASE biflexfieldeo.CODE_COMBINATION_CHART_OF_ACCOUNTS_ID
        WHEN 2001 THEN biflexfieldeo.CODE_COMBINATION_SEGMENT_3
        WHEN 18063 THEN biflexfieldeo.CODE_COMBINATION_SEGMENT_3
        WHEN 23063 THEN biflexfieldeo.CODE_COMBINATION_SEGMENT_3
        WHEN 3001 THEN biflexfieldeo.CODE_COMBINATION_SEGMENT_3
        WHEN 7037 THEN biflexfieldeo.CODE_COMBINATION_SEGMENT_3
        ELSE NULL
    END AS fa_cost_ctr_,
  CASE biflexfieldeo.CODE_COMBINATION_CHART_OF_ACCOUNTS_ID
    WHEN 2001 THEN 'Cost Center Scheme Ledger'
    WHEN 18063 THEN 'Cost Center Scheme VIC Ledger'
    WHEN 23063 THEN 'Cost Center Scheme VIC NOP Ledger'
    WHEN 3001 THEN 'Cost Center Service Co Ledger'
    WHEN 7037 THEN 'Cost Center WARRRL WA Ledger'
    ELSE NULL
END AS fa_cost_ctr_c,   
CASE biflexfieldeo.CODE_COMBINATION_CHART_OF_ACCOUNTS_ID
    WHEN 2001 THEN biflexfieldeo.CODE_COMBINATION_SEGMENT_4
    WHEN 18063 THEN biflexfieldeo.CODE_COMBINATION_SEGMENT_4
    WHEN 23063 THEN biflexfieldeo.CODE_COMBINATION_SEGMENT_4
    WHEN 3001 THEN biflexfieldeo.CODE_COMBINATION_SEGMENT_4
    WHEN 7037 THEN biflexfieldeo.CODE_COMBINATION_SEGMENT_4
    ELSE NULL
END AS gl_account_,          
 CASE biflexfieldeo.CODE_COMBINATION_CHART_OF_ACCOUNTS_ID
    WHEN 2001 THEN 'Account Scheme Ledger'
    WHEN 18063 THEN 'Account Scheme VIC Ledger'
    WHEN 23063 THEN 'Account Scheme VIC NOP Ledger'
    WHEN 3001 THEN 'Account Service Co Ledger'
    WHEN 7037 THEN 'Account WARRRL WA Ledger'
    ELSE NULL
END AS gl_account_c,   
   CASE biflexfieldeo.CODE_COMBINATION_CHART_OF_ACCOUNTS_ID
    WHEN 2001 THEN biflexfieldeo.CODE_COMBINATION_SEGMENT_1
    WHEN 18063 THEN biflexfieldeo.CODE_COMBINATION_SEGMENT_1
    WHEN 23063 THEN biflexfieldeo.CODE_COMBINATION_SEGMENT_1
    WHEN 3001 THEN biflexfieldeo.CODE_COMBINATION_SEGMENT_1
    WHEN 7037 THEN biflexfieldeo.CODE_COMBINATION_SEGMENT_1
    ELSE NULL
END AS gl_balancing_,   
 CASE biflexfieldeo.CODE_COMBINATION_CHART_OF_ACCOUNTS_ID
    WHEN 2001 THEN 'Company Scheme Ledger'
    WHEN 18063 THEN 'Company Scheme VIC Ledger'
    WHEN 23063 THEN 'Company Scheme VIC NOP Ledger'
    WHEN 3001 THEN 'Company Service Co Ledger'
    WHEN 7037 THEN 'Company WARRRL WA Ledger'
    ELSE NULL
END AS gl_balancing_c,   
 CASE biflexfieldeo.CODE_COMBINATION_CHART_OF_ACCOUNTS_ID
    WHEN 2001 THEN biflexfieldeo.CODE_COMBINATION_SEGMENT_5
    WHEN 18063 THEN biflexfieldeo.CODE_COMBINATION_SEGMENT_5
    WHEN 23063 THEN biflexfieldeo.CODE_COMBINATION_SEGMENT_5
    WHEN 3001 THEN biflexfieldeo.CODE_COMBINATION_SEGMENT_5
    WHEN 7037 THEN biflexfieldeo.CODE_COMBINATION_SEGMENT_5
    ELSE NULL
END AS gl_intercompany_,              
 CASE biflexfieldeo.CODE_COMBINATION_CHART_OF_ACCOUNTS_ID
    WHEN 2001 THEN 'Company Scheme Ledger'
    WHEN 18063 THEN 'Company Scheme VIC Ledger'
    WHEN 23063 THEN 'Company Scheme VIC NOP Ledger'
    WHEN 3001 THEN 'Company Service Co Ledger'
    WHEN 7037 THEN 'Company WARRRL WA Ledger'
    ELSE NULL
END AS gl_intercompany_c,
CASE biflexfieldeo.CODE_COMBINATION_CHART_OF_ACCOUNTS_ID
    WHEN 2001 THEN biflexfieldeo.CODE_COMBINATION_SEGMENT_2
    WHEN 18063 THEN biflexfieldeo.CODE_COMBINATION_SEGMENT_2
    WHEN 23063 THEN biflexfieldeo.CODE_COMBINATION_SEGMENT_2
    WHEN 7037 THEN biflexfieldeo.CODE_COMBINATION_SEGMENT_2
    ELSE NULL
END AS gl_mat_type_,
CASE biflexfieldeo.CODE_COMBINATION_CHART_OF_ACCOUNTS_ID
    WHEN 2001 THEN 'Mat Type Scheme Ledger'
    WHEN 18063 THEN 'Mat Type Scheme VIC Ledger'
    WHEN 23063 THEN 'Mat Type Scheme VIC NOP Ledger'
    WHEN 7037 THEN 'Mat Type WARRRL WA Ledger'
    ELSE NULL
END AS gl_mat_type_c,
CASE biflexfieldeo.CODE_COMBINATION_CHART_OF_ACCOUNTS_ID
    WHEN 3001 THEN biflexfieldeo.CODE_COMBINATION_SEGMENT_2
    ELSE NULL
END AS gl_scheme_, 
CASE biflexfieldeo.CODE_COMBINATION_CHART_OF_ACCOUNTS_ID
    WHEN 3001 THEN 'Scheme Service Co Ledger'
    ELSE NULL
END AS gl_scheme_c,
CASE biflexfieldeo.CODE_COMBINATION_CHART_OF_ACCOUNTS_ID
    WHEN 2001 THEN biflexfieldeo.CODE_COMBINATION_SEGMENT_6
    WHEN 18063 THEN biflexfieldeo.CODE_COMBINATION_SEGMENT_6
    WHEN 23063 THEN biflexfieldeo.CODE_COMBINATION_SEGMENT_6
    WHEN 3001 THEN biflexfieldeo.CODE_COMBINATION_SEGMENT_6
    WHEN 7037 THEN biflexfieldeo.CODE_COMBINATION_SEGMENT_6
    ELSE NULL
END AS gl_spare_,
CASE biflexfieldeo.CODE_COMBINATION_CHART_OF_ACCOUNTS_ID
    WHEN 2001 THEN 'Spare Scheme Ledger'
    WHEN 18063 THEN 'Spare Scheme VIC Ledger'
    WHEN 23063 THEN 'Spare Scheme VIC NOP Ledger'
    WHEN 3001 THEN 'Spare Service Co Ledger'
    WHEN 7037 THEN 'Spare WARRRL WA Ledger'
    ELSE NULL
END AS gl_spare_c,
CASE biflexfieldeo.CODE_COMBINATION_CHART_OF_ACCOUNTS_ID
    WHEN 2001 
    THEN biflexfieldeo.CODE_COMBINATION_SEGMENT_1 || '-' || biflexfieldeo.CODE_COMBINATION_SEGMENT_2 || '-' || biflexfieldeo.CODE_COMBINATION_SEGMENT_3 || '-' || biflexfieldeo.CODE_COMBINATION_SEGMENT_4 || '-' || biflexfieldeo.CODE_COMBINATION_SEGMENT_5 || '-' || biflexfieldeo.CODE_COMBINATION_SEGMENT_6
    WHEN 18063 
    THEN biflexfieldeo.CODE_COMBINATION_SEGMENT_1 || '-' || biflexfieldeo.CODE_COMBINATION_SEGMENT_2 || '-' || biflexfieldeo.CODE_COMBINATION_SEGMENT_3 || '-' || biflexfieldeo.CODE_COMBINATION_SEGMENT_4 || '-' || biflexfieldeo.CODE_COMBINATION_SEGMENT_5 || '-' || biflexfieldeo.CODE_COMBINATION_SEGMENT_6
    WHEN 23063 
    THEN biflexfieldeo.CODE_COMBINATION_SEGMENT_1 || '-' || biflexfieldeo.CODE_COMBINATION_SEGMENT_2 || '-' || biflexfieldeo.CODE_COMBINATION_SEGMENT_3 || '-' || biflexfieldeo.CODE_COMBINATION_SEGMENT_4 || '-' || biflexfieldeo.CODE_COMBINATION_SEGMENT_5 || '-' || biflexfieldeo.CODE_COMBINATION_SEGMENT_6
    WHEN 3001 
    THEN biflexfieldeo.CODE_COMBINATION_SEGMENT_1 || '-' || biflexfieldeo.CODE_COMBINATION_SEGMENT_2 || '-' || biflexfieldeo.CODE_COMBINATION_SEGMENT_3 || '-' || biflexfieldeo.CODE_COMBINATION_SEGMENT_4 || '-' || biflexfieldeo.CODE_COMBINATION_SEGMENT_5 || '-' || biflexfieldeo.CODE_COMBINATION_SEGMENT_6
    WHEN 7037 
    THEN biflexfieldeo.CODE_COMBINATION_SEGMENT_1 || '-' || biflexfieldeo.CODE_COMBINATION_SEGMENT_2 || '-' || biflexfieldeo.CODE_COMBINATION_SEGMENT_3 || '-' || biflexfieldeo.CODE_COMBINATION_SEGMENT_4 || '-' || biflexfieldeo.CODE_COMBINATION_SEGMENT_5 || '-' || biflexfieldeo.CODE_COMBINATION_SEGMENT_6
    ELSE NULL
END AS concat_values
FROM CES_ERP.FSCM_PROD_FINEXTRACT_GLBICCEXTRACT.CODE_COMBINATION_EXTRACT_PVO biflexfieldeo) biflexfieldeo_a  
ON invoicedistribution.AP_INVOICE_DISTRIBUTIONS_DIST_CODE_COMBINATION_ID   = biflexfieldeo_a.s_g_0  AND  ledgerinvdist.LEDGER_CHART_OF_ACCOUNTS_ID =  biflexfieldeo_a.s_g_1
LEFT JOIN (select * from biflexfieldeo_b ) biflexfieldeo_b  ON invoiceline.AP_INVOICE_LINES_ALL_INVOICE_ID =   biflexfieldeo_b.s_k_5000
LEFT JOIN ( SELECT A.MEANING, A.LOOKUP_CODE from CES_ERP.FSCM_PROD_ANALYTICSSERVICE.LOOKUP_VALUES_TLPVO A
WHERE ((( A.LOOKUP_TYPE   = 'YES_NO_REQUIRED' )) AND (( A.VIEW_APPLICATION_ID = 200 )) AND (( A.SET_ID  = 0 )) AND (( A.LANGUAGE  = 'US' ))) ) posted_flag_code 
ON invoicedistribution.AP_INVOICE_DISTRIBUTIONS_POSTED_FLAG = posted_flag_code.LOOKUP_CODE 
LEFT JOIN( SELECT B.MEANING, B.LOOKUP_CODE from CES_ERP.FSCM_PROD_ANALYTICSSERVICE.LOOKUP_VALUES_TLPVO B
WHERE ((( B.LOOKUP_TYPE   = 'YES_NO_REQUIRED' )) AND (( B.VIEW_APPLICATION_ID = 200 )) AND (( B.SET_ID  = 0 )) AND (( B.LANGUAGE  = 'US' ))) ) reversal_flag_code 
ON invoicedistribution.AP_INVOICE_DISTRIBUTIONS_REVERSAL_FLAG = reversal_flag_code.LOOKUP_CODE 
LEFT JOIN ( SELECT C.MEANING, C.LOOKUP_CODE from CES_ERP.FSCM_PROD_ANALYTICSSERVICE.LOOKUP_VALUES_TLPVO C
WHERE ((( C.LOOKUP_TYPE   = 'NLS TRANSLATION' )) AND (( C.VIEW_APPLICATION_ID = 200 )) AND (( C.SET_ID  = 0 )) AND (( C.LANGUAGE  = 'US' ))) ) inv_dist_match 
ON  CASE invoicedistribution.AP_INVOICE_DISTRIBUTIONS_MATCH_STATUS_FLAG WHEN 'A' THEN 'APPROVED' WHEN 'N' THEN 'NEEDS REAPPROVAL' ELSE 'NEVER APPROVED' END = inv_dist_match.LOOKUP_CODE
LEFT JOIN (SELECT D.MEANING, D.LOOKUP_CODE from CES_ERP.FSCM_PROD_ANALYTICSSERVICE.LOOKUP_VALUES_TLPVO D
WHERE ((( D.LOOKUP_TYPE   = 'INVOICE LINE MATCH TYPE' )) AND (( D.VIEW_APPLICATION_ID = 200 )) AND (( D.SET_ID  = 0 )) AND (( D.LANGUAGE  = 'US' ))) ) match_type 
ON invoiceline.AP_INVOICE_LINES_ALL_MATCH_TYPE = match_type.LOOKUP_CODE
LEFT JOIN (SELECT E.MEANING, E.LOOKUP_CODE from CES_ERP.FSCM_PROD_ANALYTICSSERVICE.LOOKUP_VALUES_TLPVO E
WHERE ((( E.LOOKUP_TYPE   = 'PAY GROUP' )) AND (( E.VIEW_APPLICATION_ID = 200 )) AND (( E.SET_ID  = 0 )) AND (( E.LANGUAGE  = 'US' ))) ) pay_group_code 
ON invoiceheader.AP_INVOICES_PAY_GROUP_LOOKUP_CODE = pay_group_code.LOOKUP_CODE
LEFT JOIN( SELECT F.PAYMENT_TERM_HEADER_TRANSLATION_NAME code_name, F.PAYMENT_TERM_HEADER_TRANSLATION_TERM_ID term_id FROM CES_ERP.FSCM_PROD_FINEXTRACT_APBICCEXTRACT.PAYMENT_TERM_HEADER_TRANSLATION_EXTRACT_PVO F
WHERE    ( ( ( F.PAYMENT_TERM_HEADER_TRANSLATION_LANGUAGE = 'US' ))) ) term_id_code 
ON invoiceheader.AP_INVOICES_TERMS_ID = term_id_code.term_id
  --( biflexfieldeo_a.concat_values is not null )  AND

{% if is_incremental() %}
WHERE
    GREATEST(COALESCE(invoiceheader.AP_INVOICES_LAST_UPDATE_DATE,to_timestamp('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')), NVL(invoicedistribution.AP_INVOICE_DISTRIBUTIONS_LAST_UPDATE_DATE,current_date),COALESCE(supplier.SUPPLIER_LAST_UPDATE_DATE,to_timestamp('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS'))) >= (SELECT DATE(dateadd(days, {{var('erp_delta_load_days')}}, LAST_UPDATED_TIMESTAMP)) FROM  COMMON_{{target.name.upper()}}.ERP.CONTROL_TIME_INCREMENTAL_LOAD WHERE TABLE_NAME = '{{trimmed_source_name}}' )
{% endif %}

) X 
WHERE CONCATENATED_SEGMENTS IS NOT NULL
    GROUP BY
    CONCATENATED_SEGMENTS,
    ENTITY_CODE,
    COST_CENTRE_CODE,
    ACCOUNT_CODE,
    INTERCOMPANY_CODE,
    MATERIAL_TYPE_CODE,
    SCHEME_CODE,
    PROJECT_CODE,
    IDENTIFYING_PO,
    INVOICE_DATE,
    INVOICE_ID,
    INVOICE_NUM,
    INVOICE_TYPE_CODE,
    INVOICE_TYPE_NAME,
    INVOICES_DATE_LAST_UPDATED,
    INVOICES_REVISION_DATE,
    INVOICES_REVISION_NUMBER,
    INVOICES_WITHHELD_TAX_AMOUNT,
    TERMS_DATE,
    INV_DIST_ACCOUNTING_DATE,
    DISTRIBUTION_DESC,
    DISTRIBUTION_LINE_NUM,
    DISTRIBUTION_UNIT_PRICE,
    INV_DIST_POSTING_STATUS,
    INV_DIST_REVERSAL_STATUS,
    MATCH_STATUS,
    INVOICE_CURRENCY,
    INV_LINE_LAST_UPDATE_DATE,
    LINE_NUMBER,
    MATCH_TYPE,
    QUANTITY_INVOICED,
    UNIT_PRICE,
    BUSINESS_UNIT_NAME,
    FISCAL_PERIOD,
    LEDGER_NAME,
    LEGAL_ENTITY_NAME,
    SUPPLIER_SITE_CODE,
    SUPPLIER_NUMBER,
    MATCH_STATUS_CODE,
    MATCH_TYPE_CODE,
    INVOICE_AMOUNT,
    SUPPLIER_NAME,
    INVOICE_SOURCE_NAME,
    PAY_GROUP,
    ACCOUNTING_DATE,
    INVOICE_DESC,
    PAYMENT_TERMS,
    INV_CREATION_DATE,
    TERM_ID,
    ORG_ID,
    LEGAL_ENT_ID,
    LEDGER_ID,
    FISCAL_YEAR_ID_1, 
    FISCAL_YEAR_ID_2,
    POSTED_FLAG,
    REVERSAL_FLAG,
    AP_INVOICES_LAST_UPDATE_DATE,
    INV_DIST_LAST_UPDATE_DATE,
    SUPPLIER_LATEST_DATE,
    INCREMENTAL_LATEST_DATE,
    SUPPLIER_DIST_VENDOR_ID  
), VIEW_B AS( 
SELECT 
    IDENTIFYING_PO,
    INVOICE_DATE,
    INVOICE_ID,
    INVOICE_NUM,
    INVOICE_TYPE_CODE,
    INVOICE_TYPE_NAME,
    INVOICES_DATE_LAST_UPDATED,
    INVOICES_REVISION_DATE,
    INVOICES_REVISION_NUMBER,
    INVOICES_WITHHELD_TAX_AMOUNT,
    TERMS_DATE,
    INVOICE_CURRENCY,
    BUSINESS_UNIT_NAME,
    FISCAL_PERIOD,
    LEDGER_NAME,
    LEGAL_ENTITY_NAME,
    SUPPLIER_SITE_CODE,
    SUPPLIER_NUMBER,
    SUM(INVOICE_AMOUNT) AS INVOICE_AMOUNT,
    SUPPLIER_NAME,
    INVOICE_SOURCE_NAME,
    PAY_GROUP,
    ACCOUNTING_DATE,
    INVOICE_DESC,
    PAYMENT_TERMS,
    INV_CREATION_DATE,
    TERM_ID,
    ORG_ID,
    LEGAL_ENT_ID,
    LEDGER_ID,
    FISCAL_YEAR_ID_1,
    FISCAL_YEAR_ID_2,
    AP_INVOICES_LAST_UPDATE_DATE
FROM (
SELECT
purchaseorder.PURCHASING_DOCUMENT_HEADER_SEGMENT_1 IDENTIFYING_PO,
invoiceheader.AP_INVOICES_INVOICE_DATE  INVOICE_DATE,
CAST(invoiceheader.AP_INVOICES_INVOICE_ID as  VARCHAR ( 100 ) )  INVOICE_ID,
invoiceheader.AP_INVOICES_INVOICE_NUM AS INVOICE_NUM,
invoiceheader.AP_INVOICES_INVOICE_TYPE_LOOKUP_CODE AS INVOICE_TYPE_CODE,  -- invoiceheader.AP_INVOICES_INVOICE_TYPE_LOOKUP_CODE
invoicepayableslookup.DISPLAYED_FIELD AS INVOICE_TYPE_NAME,  -- invpayableslookup.DISPLAYED_FIELD 
biflexfieldeo.datelastupdated_  AS  INVOICES_DATE_LAST_UPDATED,
biflexfieldeo.revisiondate_  AS  INVOICES_REVISION_DATE,
biflexfieldeo.revisionnumber_ AS INVOICES_REVISION_NUMBER ,
biflexfieldeo.withheld_tax_amount_  AS  INVOICES_WITHHELD_TAX_AMOUNT,
invoiceheader.AP_INVOICES_TERMS_DATE  AS TERMS_DATE,
invoiceheader.AP_INVOICES_INVOICE_CURRENCY_CODE  AS INVOICE_CURRENCY,
organizationunit.name AS BUSINESS_UNIT_NAME,
fiscalday.FISCAL_PERIOD_NAME AS FISCAL_PERIOD,
ledger.LEDGER_NAME AS LEDGER_NAME,
legalentity.LEGAL_ENTITY_NAME  as LEGAL_ENTITY_NAME,
suppliersite.SUPPLIER_SITE_VENDOR_SITE_CODE  as SUPPLIER_SITE_CODE,
supplier.SUPPLIER_SEGMENT_1 as SUPPLIER_NUMBER, --   invoiceheader.AP_INVOICES_VENDOR_ID
invoiceheader.AP_INVOICES_INVOICE_AMOUNT as INVOICE_AMOUNT,
supplier.PARTY_PARTY_NAME as SUPPLIER_NAME,
sourcepayableslookup.DISPLAYED_FIELD  as INVOICE_SOURCE_NAME,  -- sourcepayableslookup.DISPLAYED_FIELD 
nvl(pay_code_desc.code_desc , invoiceheader.AP_INVOICES_PAY_GROUP_LOOKUP_CODE) as PAY_GROUP,
fiscalday.REPORT_DATE AS ACCOUNTING_DATE,
invoiceheader.AP_INVOICES_DESCRIPTION AS INVOICE_DESC,
nvl(term_id_desc.term_desc, to_char(invoiceheader.AP_INVOICES_TERMS_ID)) AS PAYMENT_TERMS,
invoiceheader.AP_INVOICES_CREATION_DATE AS INV_CREATION_DATE,
invoiceheader.AP_INVOICES_TERMS_ID TERM_ID,
invoiceheader.AP_INVOICES_ORG_ID AS ORG_ID,
invoiceheader.AP_INVOICES_LEGAL_ENTITY_ID AS LEGAL_ENT_ID,
invoiceheader.AP_INVOICES_SET_OF_BOOKS_ID LEDGER_ID,
fiscalday.GL_CALENDARS_CALENDAR_ID * 10000000000 + TO_NUMBER(TO_CHAR(fiscalday.REPORT_DATE, 'yyyy'), '9999') * 1000000 + TO_NUMBER(TO_CHAR(fiscalday.REPORT_DATE, 'MM'), '99') * 10000 + 
TO_NUMBER(TO_CHAR(fiscalday.REPORT_DATE, 'dd'), '99') * 100 + fiscalday.FISCAL_PERIOD_NUMBER as FISCAL_YEAR_ID_1,
fiscalday.FISCAL_YEAR_NUMBER * 10000 + fiscalday.GL_CALENDARS_CALENDAR_ID * 100000000 + fiscalday.FISCAL_QUARTER_NUMBER * 100 + fiscalday.FISCAL_PERIOD_NUMBER as FISCAL_YEAR_ID_2,
invoiceheader.AP_INVOICES_LAST_UPDATE_DATE as AP_INVOICES_LAST_UPDATE_DATE
FROM
CES_ERP.FSCM_PROD_FINEXTRACT_APBICCEXTRACT.INVOICE_HEADER_EXTRACT_PVO invoiceheader  -- V184988491
LEFT JOIN (select * from purchaseorder) purchaseorder
ON invoiceheader.AP_INVOICES_PO_HEADER_ID = purchaseorder.PURCHASING_DOCUMENT_HEADER_PO_HEADER_ID
LEFT JOIN CES_ERP.FSCM_PROD_PRCPOZPUBLICVIEW.SUPPLIER_PVO supplier ON invoiceheader.AP_INVOICES_VENDOR_ID = supplier.VENDOR_ID   -- V448314251
LEFT JOIN CES_ERP.FSCM_PROD_FINEXTRACT_XLEBICCEXTRACT.LEGAL_ENTITY_EXTRACT_PVO legalentity ON invoiceheader.AP_INVOICES_LEGAL_ENTITY_ID = legalentity.LEGAL_ENTITY_LEGAL_ENTITY_ID  -- V286822520
LEFT JOIN CES_ERP.FSCM_PROD_PRCPOZPUBLICVIEW.SUPPLIER_SITE_PVO suppliersite ON invoiceheader.AP_INVOICES_VENDOR_SITE_ID= suppliersite.VENDOR_SITE_ID  --V250398895
LEFT JOIN CES_ERP.FSCM_PROD_FINAPSHAREDCORE.SOURCE_LOOKUP_PVO sourcepayableslookup ON invoiceheader.AP_INVOICES_SOURCE = sourcepayableslookup.LOOKUP_CODE   --V42749189
LEFT JOIN CES_ERP.FSCM_PROD_FINGLCALACC.FISCAL_DAY_PVO fiscalday 
ON invoiceheader.AP_INVOICES_INVOICE_DATE = fiscalday.REPORT_DATE 
AND 'N'   = fiscalday.FISCAL_PERIOD_ADJUSTMENT_PERIOD_FLAG 
AND invoiceheader.AP_INVOICES_SET_OF_BOOKS_ID= fiscalday.LEDGER_ID -- V518783208
JOIN  (select * from organizationunit) organizationunit 
ON  invoiceheader.AP_INVOICES_ORG_ID = organizationunit.organization_id_1 -- V220364535  
JOIN CES_ERP.FSCM_PROD_FINEXTRACT_GLBICCEXTRACT.LEDGER_EXTRACT_PVO ledger ON invoiceheader.AP_INVOICES_SET_OF_BOOKS_ID = ledger.LEDGER_LEDGER_ID  -- V498378102
LEFT JOIN  CES_ERP.FSCM_PROD_FINAPSHAREDCORE.INVOICE_TYPE_LOOKUP_PVO invoicepayableslookup ON invoiceheader.AP_INVOICES_INVOICE_TYPE_LOOKUP_CODE = invoicepayableslookup.LOOKUP_CODE    -- V527471652
LEFT JOIN (select * from biflexfieldeo_b)  biflexfieldeo 
ON invoiceheader.AP_INVOICES_INVOICE_ID = biflexfieldeo.s_k_5000  -- V194542889
LEFT JOIN (  SELECT
        v72673585.MEANING             AS Code_Desc,
        v72673585.LOOKUP_CODE         AS Lookup_Code
        FROM CES_ERP.FSCM_PROD_ANALYTICSSERVICE.LOOKUP_VALUES_TLPVO v72673585
         WHERE
        ( ( ( v72673585.LOOKUP_TYPE = 'PAY GROUP' ) )
          AND ( ( v72673585.VIEW_APPLICATION_ID = 200 ) )
          AND ( ( v72673585.SET_ID   = 0 ) )
          AND ( ( v72673585.LANGUAGE  = 'US' ) ) ) 
          ) pay_code_desc  -- 27. pay_group_lookup_code
ON  invoiceheader.AP_INVOICES_PAY_GROUP_LOOKUP_CODE = pay_code_desc.Lookup_Code
LEFT JOIN ( SELECT
            v106358286.PAYMENT_TERM_HEADER_TRANSLATION_NAME     AS term_desc,
            v106358286.PAYMENT_TERM_HEADER_TRANSLATION_TERM_ID  AS term_id
            FROM
            CES_ERP.FSCM_PROD_FINEXTRACT_APBICCEXTRACT.PAYMENT_TERM_HEADER_TRANSLATION_EXTRACT_PVO v106358286
            WHERE
            ( ( ( v106358286.PAYMENT_TERM_HEADER_TRANSLATION_LANGUAGE = 'US' ) ) ) 
            ) term_id_desc  --23. term_id
    ON invoiceheader.AP_INVOICES_TERMS_ID  = term_id_desc.term_id
    ) X
    group by 
    IDENTIFYING_PO,
    INVOICE_DATE,
    INVOICE_ID,
    INVOICE_NUM,
    INVOICE_TYPE_CODE,
    INVOICE_TYPE_NAME,
    INVOICES_DATE_LAST_UPDATED,
    INVOICES_REVISION_DATE,
    INVOICES_REVISION_NUMBER,
    INVOICES_WITHHELD_TAX_AMOUNT,
    TERMS_DATE,
    INVOICE_CURRENCY,
    BUSINESS_UNIT_NAME,
    FISCAL_PERIOD,
    LEDGER_NAME,
    LEGAL_ENTITY_NAME,
    SUPPLIER_SITE_CODE,
    SUPPLIER_NUMBER,
    SUPPLIER_NAME,
    INVOICE_SOURCE_NAME,
    PAY_GROUP,
    ACCOUNTING_DATE,
    INVOICE_DESC,
    PAYMENT_TERMS,
    INV_CREATION_DATE,
    TERM_ID,
    ORG_ID,
    LEGAL_ENT_ID,
    LEDGER_ID,
    FISCAL_YEAR_ID_1,
    FISCAL_YEAR_ID_2,
    AP_INVOICES_LAST_UPDATE_DATE
    ) ,
VIEW_C AS( 
SELECT 
A.CONCATENATED_SEGMENTS||'-'||COALESCE(A.INVOICE_ID, A.INVOICE_ID)||'-'||A.DISTRIBUTION_LINE_NUM||'-'||A.LINE_NUMBER AS ID,	
A.CONCATENATED_SEGMENTS,	
A.ENTITY_CODE,
A.COST_CENTRE_CODE,	
A.ACCOUNT_CODE,
A.INTERCOMPANY_CODE	,
A.MATERIAL_TYPE_CODE,	
A.SCHEME_CODE,	
A.PROJECT_CODE,	
COALESCE(A.IDENTIFYING_PO, A.IDENTIFYING_PO) AS IDENTIFYING_PO,--	X
COALESCE(A.INVOICE_DATE, A.INVOICE_DATE) AS INVOICE_DATE,--	X
COALESCE(A.INVOICE_ID, A.INVOICE_ID) AS INVOICE_ID,--	X
COALESCE(A.INVOICE_NUM, A.INVOICE_NUM) AS INVOICE_NUM,--	X
COALESCE(A.INVOICE_TYPE_CODE, A.INVOICE_TYPE_CODE) AS INVOICE_TYPE_CODE,--	X
COALESCE(A.INVOICE_TYPE_NAME, A.INVOICE_TYPE_NAME) AS INVOICE_TYPE_NAME,--	X
COALESCE(A.INVOICES_DATE_LAST_UPDATED, A.INVOICES_DATE_LAST_UPDATED) AS INVOICES_DATE_LAST_UPDATED,--	X
COALESCE(A.INVOICES_REVISION_DATE, A.INVOICES_REVISION_DATE) AS INVOICES_REVISION_DATE,--	X
COALESCE(A.INVOICES_REVISION_NUMBER, A.INVOICES_REVISION_NUMBER) AS INVOICES_REVISION_NUMBER,--	X
COALESCE(A.INVOICES_WITHHELD_TAX_AMOUNT, A.INVOICES_WITHHELD_TAX_AMOUNT) AS INVOICES_WITHHELD_TAX_AMOUNT,--	X
COALESCE(A.TERMS_DATE, A.TERMS_DATE) AS TERMS_DATE,--	X
INV_DIST_ACCOUNTING_DATE,	
A.DISTRIBUTION_DESC,
A.DISTRIBUTION_LINE_NUM,	
A.DISTRIBUTION_UNIT_PRICE,
A.INV_DIST_LAST_UPDATE_DATE,	
A.INV_DIST_POSTING_STATUS,	
A.INV_DIST_REVERSAL_STATUS,	
A.MATCH_STATUS,	
COALESCE(A.INVOICE_CURRENCY, A.INVOICE_CURRENCY) AS INVOICE_CURRENCY,--	X
A.INV_LINE_LAST_UPDATE_DATE,	
A.LINE_NUMBER,
A.MATCH_TYPE,
A.QUANTITY_INVOICED,	
A.UNIT_PRICE,
COALESCE(A.BUSINESS_UNIT_NAME, B.BUSINESS_UNIT_NAME) AS BUSINESS_UNIT_NAME,---	X
COALESCE(A.FISCAL_PERIOD, B.FISCAL_PERIOD) AS FISCAL_PERIOD,--X
COALESCE(A.LEDGER_NAME, B.LEDGER_NAME) AS LEDGER_NAME,--X
COALESCE(A.LEGAL_ENTITY_NAME, B.LEGAL_ENTITY_NAME) AS LEGAL_ENTITY_NAME,--X
COALESCE(A.SUPPLIER_SITE_CODE, B.SUPPLIER_SITE_CODE) AS SUPPLIER_SITE_CODE,--X
COALESCE(A.SUPPLIER_NUMBER, B.SUPPLIER_NUMBER) AS SUPPLIER_NUMBER,--X
A.MATCH_STATUS_CODE,	 --     v453273660.inv_dist_match_status  
A.MATCH_TYPE_CODE,--	
B.INVOICE_AMOUNT,--X
A.TOTAL_DISTRIBUTION_AMOUNT,	
COALESCE(A.SUPPLIER_NAME, B.SUPPLIER_NAME) AS SUPPLIER_NAME,--X
COALESCE(A.INVOICE_SOURCE_NAME, B.INVOICE_SOURCE_NAME) AS INVOICE_SOURCE_NAME,--X
COALESCE(A.PAY_GROUP, B.PAY_GROUP) AS PAY_GROUP,--X
COALESCE(A.ACCOUNTING_DATE, B.ACCOUNTING_DATE) AS ACCOUNTING_DATE,--X
COALESCE(A.INVOICE_DESC, B.INVOICE_DESC) AS INVOICE_DESC,--X
COALESCE(A.PAYMENT_TERMS, B.PAYMENT_TERMS) AS PAYMENT_TERMS,--X
COALESCE(A.INV_CREATION_DATE, B.INV_CREATION_DATE) AS INV_CREATION_DATE,--X
COALESCE(A.TERM_ID, B.TERM_ID) AS TERM_ID,--X
COALESCE(A.ORG_ID, B.ORG_ID) AS ORG_ID,--X
COALESCE(A.LEGAL_ENT_ID, B.LEGAL_ENT_ID) AS LEGAL_ENT_ID,--X
COALESCE(A.LEDGER_ID, B.LEDGER_ID) AS LEDGER_ID,--X
COALESCE(A.FISCAL_YEAR_ID_1, B.FISCAL_YEAR_ID_1) AS FISCAL_YEAR_ID_1,	
COALESCE(A.FISCAL_YEAR_ID_2,B.FISCAL_YEAR_ID_2)	AS FISCAL_YEAR_ID_2,
A.POSTED_FLAG,
A.REVERSAL_FLAG,
B.AP_INVOICES_LAST_UPDATE_DATE,
A.INCREMENTAL_LATEST_DATE,
A.SUPPLIER_LATEST_DATE,
ROW_NUMBER() OVER (PARTITION BY A.ENTITY_CODE,A.COST_CENTRE_CODE,A.ACCOUNT_CODE,A.INTERCOMPANY_CODE,A.MATERIAL_TYPE_CODE,A.SCHEME_CODE,A.PROJECT_CODE,COALESCE(A.IDENTIFYING_PO,A.IDENTIFYING_PO),COALESCE(A.INVOICE_DATE, B.INVOICE_DATE),COALESCE(A.INVOICE_ID, B.INVOICE_ID),COALESCE(A.INVOICE_NUM, B.INVOICE_NUM),COALESCE(A.INVOICE_TYPE_CODE, B.INVOICE_TYPE_CODE),COALESCE(A.INVOICE_TYPE_NAME, B.INVOICE_TYPE_NAME),COALESCE(A.INVOICES_WITHHELD_TAX_AMOUNT, B.INVOICES_WITHHELD_TAX_AMOUNT),COALESCE(A.TERMS_DATE, B.TERMS_DATE),A.INV_DIST_ACCOUNTING_DATE,A.DISTRIBUTION_DESC,A.DISTRIBUTION_LINE_NUM,A.DISTRIBUTION_UNIT_PRICE,A.INV_DIST_LAST_UPDATE_DATE,COALESCE(A.FISCAL_YEAR_ID_2,B.FISCAL_YEAR_ID_2),A.POSTED_FLAG,A.INV_DIST_POSTING_STATUS,A.INV_DIST_REVERSAL_STATUS,A.MATCH_STATUS,COALESCE(A.INVOICE_CURRENCY,B.INVOICE_CURRENCY),A.INV_LINE_LAST_UPDATE_DATE,A.LINE_NUMBER,A.MATCH_TYPE,A.QUANTITY_INVOICED,A.UNIT_PRICE,COALESCE(A.BUSINESS_UNIT_NAME, B.BUSINESS_UNIT_NAME),COALESCE(A.FISCAL_PERIOD, B.FISCAL_PERIOD),COALESCE(A.LEDGER_NAME, B.LEDGER_NAME),COALESCE(A.LEGAL_ENTITY_NAME,B.LEGAL_ENTITY_NAME),COALESCE(A.SUPPLIER_SITE_CODE,B.SUPPLIER_SITE_CODE),COALESCE(A.SUPPLIER_NUMBER, B.SUPPLIER_NUMBER),A.MATCH_STATUS_CODE,A.MATCH_TYPE_CODE,B.INVOICE_AMOUNT,A.TOTAL_DISTRIBUTION_AMOUNT,COALESCE(A.SUPPLIER_NAME, B.SUPPLIER_NAME),COALESCE(A.INVOICE_SOURCE_NAME, B.INVOICE_SOURCE_NAME),COALESCE(A.PAY_GROUP, B.PAY_GROUP),COALESCE(A.ACCOUNTING_DATE, B.ACCOUNTING_DATE),COALESCE(A.INVOICE_DESC, B.INVOICE_DESC),COALESCE(A.PAYMENT_TERMS, B.PAYMENT_TERMS),COALESCE(A.INV_CREATION_DATE, B.INV_CREATION_DATE),COALESCE(B.TERM_ID, A.TERM_ID),COALESCE(B.ORG_ID, A.ORG_ID),COALESCE(A.LEGAL_ENT_ID,B.LEGAL_ENT_ID),COALESCE(A.LEDGER_ID, B.LEDGER_ID),COALESCE(A.FISCAL_YEAR_ID_1, B.FISCAL_YEAR_ID_1)
ORDER BY A.ENTITY_CODE ASC,A.COST_CENTRE_CODE ASC,A.ACCOUNT_CODE ASC,A.INTERCOMPANY_CODE ASC,A.MATERIAL_TYPE_CODE ASC,A.SCHEME_CODE ASC,A.PROJECT_CODE ASC,COALESCE(A.IDENTIFYING_PO, B.IDENTIFYING_PO) ASC,COALESCE(A.INVOICE_DATE, B.INVOICE_DATE) ASC,COALESCE(A.INVOICE_ID, B.INVOICE_ID) ASC,COALESCE(A.INVOICE_NUM, B.INVOICE_NUM) ASC,COALESCE(A.INVOICE_TYPE_CODE, B.INVOICE_TYPE_CODE) ASC,COALESCE(A.INVOICE_TYPE_NAME, B.INVOICE_TYPE_NAME) ASC,COALESCE(A.INVOICES_WITHHELD_TAX_AMOUNT, B.INVOICES_WITHHELD_TAX_AMOUNT) ASC,COALESCE(A.TERMS_DATE, B.TERMS_DATE) ASC,A.INV_DIST_ACCOUNTING_DATE ASC,A.DISTRIBUTION_DESC ASC,A.DISTRIBUTION_LINE_NUM ASC,A.DISTRIBUTION_UNIT_PRICE ASC,A.INV_DIST_LAST_UPDATE_DATE ASC, COALESCE(A.FISCAL_YEAR_ID_2,B.FISCAL_YEAR_ID_2) ASC,A.POSTED_FLAG ASC,A.INV_DIST_POSTING_STATUS ASC,A.INV_DIST_REVERSAL_STATUS ASC,A.MATCH_STATUS ASC,COALESCE(A.INVOICE_CURRENCY, B.INVOICE_CURRENCY) ASC,A.INV_LINE_LAST_UPDATE_DATE ASC,A.LINE_NUMBER ASC,A.MATCH_TYPE ASC,A.QUANTITY_INVOICED ASC,A.UNIT_PRICE ASC,COALESCE(A.BUSINESS_UNIT_NAME, B.BUSINESS_UNIT_NAME) ASC,COALESCE(A.FISCAL_PERIOD, B.FISCAL_PERIOD) ASC,COALESCE(A.LEDGER_NAME, B.LEDGER_NAME) ASC,COALESCE(A.LEGAL_ENTITY_NAME, B.LEGAL_ENTITY_NAME) ASC,COALESCE(A.SUPPLIER_SITE_CODE, B.SUPPLIER_SITE_CODE) ASC,COALESCE(A.SUPPLIER_NUMBER, B.SUPPLIER_NUMBER) ASC,A.MATCH_STATUS_CODE ASC,A.MATCH_TYPE_CODE ASC,B.INVOICE_AMOUNT ASC,A.TOTAL_DISTRIBUTION_AMOUNT ASC,COALESCE(A.SUPPLIER_NAME, B.SUPPLIER_NAME) ASC,COALESCE(A.INVOICE_SOURCE_NAME, B.INVOICE_SOURCE_NAME) ASC,COALESCE(A.PAY_GROUP,B.PAY_GROUP) ASC,COALESCE(A.ACCOUNTING_DATE, B.ACCOUNTING_DATE) ASC,COALESCE(A.INVOICE_DESC, B.INVOICE_DESC) ASC,COALESCE(A.PAYMENT_TERMS, B.PAYMENT_TERMS) ASC,COALESCE(A.INV_CREATION_DATE, B.INV_CREATION_DATE) ASC,COALESCE(A.TERM_ID, B.TERM_ID) ASC,COALESCE(A.ORG_ID, B.ORG_ID) ASC,COALESCE(A.LEGAL_ENT_ID, B.LEGAL_ENT_ID) ASC,COALESCE(A.LEDGER_ID, B.LEDGER_ID) ASC,COALESCE(A.FISCAL_YEAR_ID_1, B.FISCAL_YEAR_ID_1) ASC ) as Duplicate_Check
    FROM VIEW_A A 
    LEFT OUTER JOIN VIEW_B B ON  
    EQUAL_NULL(A.SUPPLIER_NUMBER ,B.SUPPLIER_NUMBER) AND
    EQUAL_NULL(A.SUPPLIER_NAME ,B.SUPPLIER_NAME) AND
    EQUAL_NULL(A.SUPPLIER_SITE_CODE ,B.SUPPLIER_SITE_CODE) AND
    EQUAL_NULL(A.INVOICE_SOURCE_NAME ,B.INVOICE_SOURCE_NAME) AND
    EQUAL_NULL(A.LEGAL_ENT_ID ,B.LEGAL_ENT_ID) AND
    EQUAL_NULL(A.FISCAL_YEAR_ID_1 ,B.FISCAL_YEAR_ID_1) AND
    EQUAL_NULL(A.INVOICES_REVISION_NUMBER ,B.INVOICES_REVISION_NUMBER) AND
    EQUAL_NULL(A.INVOICES_REVISION_DATE ,B.INVOICES_REVISION_DATE) AND
    EQUAL_NULL(A.INVOICES_DATE_LAST_UPDATED ,B.INVOICES_DATE_LAST_UPDATED) AND
    EQUAL_NULL(A.INVOICE_ID ,B.INVOICE_ID) AND
    EQUAL_NULL(A.INVOICES_WITHHELD_TAX_AMOUNT ,B.INVOICES_WITHHELD_TAX_AMOUNT) AND
    EQUAL_NULL(A.INVOICE_DATE ,B.INVOICE_DATE) AND
    EQUAL_NULL(A.INV_CREATION_DATE ,B.INV_CREATION_DATE) AND
    EQUAL_NULL(A.TERMS_DATE ,B.TERMS_DATE) AND
    EQUAL_NULL(A.PAY_GROUP ,B.PAY_GROUP) AND
    EQUAL_NULL(A.IDENTIFYING_PO ,B.IDENTIFYING_PO) AND
    EQUAL_NULL(A.INVOICE_NUM ,B.INVOICE_NUM) AND
    EQUAL_NULL(A.TERM_ID ,B.TERM_ID) AND
    EQUAL_NULL(A.ORG_ID ,B.ORG_ID) AND
    EQUAL_NULL(A.LEDGER_ID ,B.LEDGER_ID) AND
    EQUAL_NULL(A.INVOICE_TYPE_NAME ,B.INVOICE_TYPE_NAME) AND
    EQUAL_NULL(A.INVOICE_TYPE_CODE ,B.INVOICE_TYPE_CODE) AND
    EQUAL_NULL(A.INVOICE_CURRENCY ,B.INVOICE_CURRENCY) AND
    EQUAL_NULL(A.INVOICE_DESC ,B.INVOICE_DESC) 
    ) 
    SELECT 
c.ID,
c.CONCATENATED_SEGMENTS,
c.ENTITY_CODE,
c.COST_CENTRE_CODE AS COST_CENTER_CODE,
c.ACCOUNT_CODE,
c.INTERCOMPANY_CODE,
c.MATERIAL_TYPE_CODE,
c.SCHEME_CODE,
c.PROJECT_CODE,
c.IDENTIFYING_PO,
c.INVOICE_DATE,
c.INVOICE_ID,
c.INVOICE_NUM,
c.INVOICE_TYPE_CODE,
c.INVOICE_TYPE_NAME,
c.INVOICES_DATE_LAST_UPDATED,
c.INVOICES_REVISION_DATE,
c.INVOICES_REVISION_NUMBER,
c.INVOICES_WITHHELD_TAX_AMOUNT,
c.TERMS_DATE,
c.INV_DIST_ACCOUNTING_DATE,
c.DISTRIBUTION_DESC,
c.DISTRIBUTION_LINE_NUM,
c.DISTRIBUTION_UNIT_PRICE,
c.INV_DIST_POSTING_STATUS,
c.INV_DIST_REVERSAL_STATUS,
c.MATCH_STATUS,
c.INVOICE_CURRENCY,
c.INV_LINE_LAST_UPDATE_DATE,
c.LINE_NUMBER,
c.MATCH_TYPE,
c.QUANTITY_INVOICED,
c.UNIT_PRICE,
c.BUSINESS_UNIT_NAME,
c.FISCAL_PERIOD,
c.LEDGER_NAME,
c.LEGAL_ENTITY_NAME,
c.SUPPLIER_SITE_CODE,
c.SUPPLIER_NUMBER,
c.MATCH_STATUS_CODE,
c.MATCH_TYPE_CODE,
c.INVOICE_AMOUNT,
c.TOTAL_DISTRIBUTION_AMOUNT,
c.SUPPLIER_NAME,
c.INVOICE_SOURCE_NAME,
c.PAY_GROUP,
c.ACCOUNTING_DATE,
c.INVOICE_DESC,
c.PAYMENT_TERMS,
c.INV_CREATION_DATE,
c.AP_INVOICES_LAST_UPDATE_DATE,
c.INV_DIST_LAST_UPDATE_DATE,
c.SUPPLIER_LATEST_DATE,
c.INCREMENTAL_LATEST_DATE
FROM VIEW_C c
WHERE Duplicate_Check = 1
