version: 2

models:
  - name: CRP_COLLECTION_HDR
    description: This is the collections header
    columns:
      - name: LINK_ID
        description: This is the primary key for this table.
        tests:
          - unique:
                config:
                  severity: warn
          - not_null:
                config:
                  severity: warn
      - name: MULTI_SCHEME_ID
        tests:
          - accepted_values:
              values: [10000,10001,100020001,100020002,100020003]
              severity: error
  - name: CRP_COLLECTION_DTL
    description: This is the collections details table.
    columns:
      - name: ID
        description: This is the primary key for this table.
        tests:
          - unique
          - not_null
      - name: MULTI_SCHEME_ID
        tests:
          - accepted_values:
              values: [10000,10001,100020001,100020002,100020003]