version: 2

models:
  - name: ORDER_HEADER
    description: Order header table
    columns:
      - name: RECORD_ID
        description: Primary key for the table
        tests:
          - unique:
              config:
                severity: warn
          - not_null:
              config:
                severity: warn
      - name: PROGRAM_CODE
        tests:
          - accepted_values:
              values: [20001, 20002, 20010001, 20010002, 20020001]
              severity: error
  - name: ORDER_DETAILS
    description: Order details table
    columns:
      - name: DETAIL_ID
        description: Primary key for the table
        tests:
          - unique
          - not_null
      - name: PROGRAM_CODE
        tests:
          - accepted_values:
              values: [20001, 20002, 20010001, 20010002, 20020001]