table Dates
	lineageTag: 3da93e4e-d175-4159-b464-212045f1e738

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: df16d36c-3dcc-48f7-8f47-5be87fa39229
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 9537902a-784b-400c-b19e-db541bd27b77
			defaultHierarchy: LocalDateTable_07d2ecb9-ec85-4ddf-9b62-0c89a18884b8.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 5e1b36ad-45a3-4e4a-abda-96c11f782e32
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month_Num
		dataType: int64
		formatString: 0
		lineageTag: c07330b4-cd23-47d4-b95c-05467e4f6d0e
		summarizeBy: sum
		sourceColumn: Month_Num

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: 41c34158-32de-41cf-8336-a35ca03f6471
		summarizeBy: none
		sourceColumn: Month
		sortByColumn: Month_Num

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Month_Short
		dataType: string
		lineageTag: 2788da25-67b8-4fe0-a9d1-5414617d29e3
		summarizeBy: none
		sourceColumn: Month_Short
		sortByColumn: Month_Num

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Day
		dataType: int64
		formatString: 0
		lineageTag: 6a989b25-af18-426d-b10b-cff0d6ff4510
		summarizeBy: sum
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column Weekday
		dataType: int64
		formatString: 0
		lineageTag: 76ee5de7-f98e-4273-b6f5-268c7776ba11
		summarizeBy: sum
		sourceColumn: Weekday

		annotation SummarizationSetBy = Automatic

	column Day_of_Week
		dataType: string
		lineageTag: 24bb23e2-a885-4976-b65a-29429f6fbb08
		summarizeBy: none
		sourceColumn: Day_of_Week

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Month_Year
		dataType: string
		lineageTag: 90b541d4-74be-4a6b-86fc-a1e06d8e13d6
		summarizeBy: none
		sourceColumn: Month_Year
		sortByColumn: Year_Month

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Year_Month
		dataType: string
		lineageTag: a463ac14-fa0d-4217-adde-4d2363846bbe
		summarizeBy: none
		sourceColumn: Year_Month

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	partition Dates-61aceaac-44cc-419e-91d2-ebd50e8f1926 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\seanc\OneDrive\Desktop\Udacity\Course\2020_12_09_Course_Datasets.xlsx"), null, true),
				    Dates_Sheet = Source{[Item="Dates",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Dates_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Year", Int64.Type}, {"Month_Num", Int64.Type}, {"Month", type text}, {"Month_Short", type text}, {"Day", Int64.Type}, {"Weekday", Int64.Type}, {"Day_of_Week", type text}, {"Month_Year", type text}, {"Year_Month", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

