

/****** CREATE PRIMARY KEY EXAMPLE ******/
ALTER TABLE [QLIK_EXT_E1].[F4211] ADD  CONSTRAINT [F4211_F4211_PK] PRIMARY KEY NONCLUSTERED 
(
	[SDDOCO] ASC,
	[SDDCTO] ASC,
	[SDKCOO] ASC,
	[SDLNID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = ON, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO




/****** CREATE CLUSTERED COLUMNSTORE INDEX FOR BIG TABLES ******/
CREATE CLUSTERED COLUMNSTORE INDEX [QLIK_EXT_E1_F4211] ON [QLIK_EXT_E1].[F4211] WITH (DROP_EXISTING = OFF, COMPRESSION_DELAY = 0) ON [PRIMARY]
GO




/****** INDEX FOR TABLE IN A RECURSION, EXAMPLE ******/
CREATE CLUSTERED INDEX CDX_#Item_Lvl ON #Item ([lvl])   --- WHERE LEVEL KEEPS ON INCREASING IT'S VALUE IN THE RECURSION
CREATE NONCLUSTERED INDEX NDX_#Item_ItemID ON #Item (ItemID)  -- WHERE ITEMID IS KEY

