

/*QUERY TO COMPARE UNIT DIFFERENCE ACCOUNTLEDGER_NBL SOLUTION VS QLIK F0911 TABLE ON FULL_DATE**/

DECLARE @FISCAL_YEAR AS VARCHAR(50) = '2023'
DECLARE @FISCAL_PERIOD AS INT =  3

PRINT @FISCAL_YEAR
PRINT @FISCAL_PERIOD

SELECT 

NEW.GL_FULL_DATE_NBL,
NEW.Units_Sum_NBL,
F911.UNITS_911,
(F911.UNITS_911 - NEW.Units_Sum_NBL)  as "Variance 911 V NBL"

FROM(
SELECT
X.GL_FULL_DATE GL_FULL_DATE_NBL,
SUM(X.units) Units_Sum_NBL,
SUM(X.amount) Amount_Sum_NBL
FROM (
SELECT f.GL_FULL_DATE,
f.DOC_NUM,d.FIS_YEAR, 
d.FIS_MONTH_NUM_IN_YEAR, 
o.OBJECT_SUBSIDIARY,
b.ADDR_BOOK_KEY DIM_ADDR_KEY, 
f.ADDR_BOOK_KEY FACT_ADDR_KEY,  
b.ADDR_NUM, 
p.ITEM_KEY DIM_ITEM_KEY, 
f.ITEM_KEY FACT_ITEM_KEY,  
p.ITEM_NUM_2, 
u.BUSINESS_UNIT,
d.FULL_DATE, 
f.QTY_IN_UOM, 
f.UOM_DESC, 
f.JRNL_EXPLA, 
p.BOTTLE_SIZE, 
f.AMT_IN_LOCAL, 
u.EXT_BUDGET_HOLDER_CODE, 
p.BRAND_CODE, 
u.EXT_BUDGET_HOLDER_DESC, 
f.AMT_IN_LOCAL_YTD as amount, 
f.QTY_IN_UOM  as units
FROM [DWH_FINANCE].[V_FT_AccountLedgerTransaction_NBL] f
left join DWH_SHARED.V_D_Date_NBL d
on f.GL_DATE_KEY = d.DATE_KEY 
left join DWH_SHARED.V_D_ObjectAccount_NBL o
on f.OBJECT_ACCOUNT_KEY = o.OBJECT_ACCOUNT_KEY
left join DWH_SHARED.V_D_Product_NBL p
on f.ITEM_KEY = p.ITEM_KEY
left join DWH_SHARED.V_D_AddressBook_NBL b
on f.ADDR_BOOK_KEY = b.ADDR_BOOK_KEY
left join [DWH_SHARED].[V_D_BusinessUnit_NBL] u
on f.BUSINESS_UNIT_KEY = u.BUSINESS_UNIT_KEY
where f.FIS_YEAR = @FISCAL_YEAR
and d.FIS_MONTH_NUM_IN_YEAR IN (@FISCAL_PERIOD)
--and u.BUSINESS_DIVISION_CODE  IN ('PRNZ','PRA')
--and o.OBJECT_SUBSIDIARY = '3010001'

)X
  
GROUP BY
X.GL_FULL_DATE 

) NEW



LEFT JOIN (
SELECT
X.FULL_DATE_1,
SUM(X.Units) UNITS_911

FROM
(
SELECT 
D_Date_NBL_1.FULL_DATE FULL_DATE_1,
D_Date_NBL_2.FULL_DATE FULL_DATE_2,
D_Date_NBL_1.FIS_YEAR,
D_Date_NBL_1.FIS_MONTH_NUM_IN_YEAR,
D_Company_NBL.[COMPANY_KEY] AS [DOC_COMPANY_KEY],
ISNULL(D_OrderType_NBL.[ORDER_TYPE_KEY], '-1') AS [DOC_TYPE_KEY],
F0911.[GLDCT] AS [DOC_TYPE_CODE],
CONVERT(INT,CAST(F0911.[GLDOC] AS DECIMAL)) AS [DOC_NUM],
ISNULL(D_Date_NBL_1.[DATE_KEY], '-1') AS [GL_DATE_KEY],
CAST(F0911.[GLJELN] AS DECIMAL(18,2)) AS [JRNL_ENTRY_LINE_NUM],	
F0911.[GLEXTL] AS [LINE_EXT_CODE],	
ISNULL(D_LedgerType_NBL.[LEDGER_TYPE_KEY], '-1')  AS [LEDGER_TYPE_KEY],	
cast(CONVERT(DOUBLE PRECISION,F0911.[GLU])/100 as numeric(16,2)) AS Units,
cast(CONVERT(DOUBLE PRECISION,F0911.[GLAA])/100 as numeric(16,2)) AS Amount

FROM QLIK_EXT_E1.F0911 
LEFT JOIN DWH.D_Company_NBL  ON  F0911.GLKCO = D_Company_NBL.COMPANY_CODE
LEFT JOIN DWH.D_OrderType_NBL  ON D_OrderType_NBL.ORDER_TYPE_CODE = F0911.GLDCT
LEFT JOIN DWH.D_Date_NBL D_Date_NBL_1  on CAST(EXT_E1.Julian2Date(F0911.GLDGJ) AS DATETIME) = D_Date_NBL_1.FULL_DATE
LEFT JOIN DWH.D_Date_NBL D_Date_NBL_2  on  CAST(EXT_E1.Julian2Date(F0911.GLDSVJ) AS DATETIME) = D_Date_NBL_2.FULL_DATE
LEFT JOIN DWH.D_LedgerType_NBL  ON D_LedgerType_NBL.LEDGER_TYPE_CODE = F0911.GLLT
LEFT JOIN DWH.D_BusinessUnit_NBL  ON D_BusinessUnit_NBL.BUSINESS_UNIT = F0911.GLMCU
LEFT JOIN DWH.D_ObjectAccount_NBL  ON D_ObjectAccount_NBL.OBJECT_SUBSIDIARY = CONCAT(F0911.GLOBJ, F0911.GLSUB)
LEFT JOIN DWH.D_SubledgerType_NBL ON D_SubledgerType_NBL.SUBLEDGER_TYPE_CODE = F0911.GLSBLT
LEFT JOIN DWH.D_GLClass_NBL on F0911.GLGLC = D_GLClass_NBL.GL_CLASS_CODE
LEFT JOIN DWH.D_Item_NBL ON D_Item_NBL.ITEM_NUM_2 =  F0911.GLEXR
LEFT JOIN DWH.D_CostObject_NBL  on F0911.GLABR1 = D_CostObject_NBL.COST_OBJECT_CODE AND F0911.GLABT1 = D_CostObject_NBL.COST_OBJECT_TYPE_CODE
LEFT JOIN DWH.D_Currency_NBL  on F0911.GLBCRC = D_Currency_NBL.CURRENCY_CODE
LEFT JOIN DWH.D_UnitOfMeasure_NBL ON F0911.GLUM = D_UnitOfMeasure_NBL.UOM_CODE
LEFT JOIN DWH_SHARED.V_REF_SupplementalData  on F0911.GLITM = V_REF_SupplementalData.ITEM_NUM
LEFT JOIN DWH.D_Currency_NBL C on F0911.GLCRCD = C.CURRENCY_CODE
LEFT JOIN DWH.D_AddressBook_NBL D_AddressBook_NBL_1 on cast(cast(F0911.GLAN8 as decimal(10,0)) as nvarchar(50)) = D_AddressBook_NBL_1.ADDR_NUM
LEFT JOIN DWH.D_AddressBook_NBL D_AddressBook_NBL_2 ON cast(F0911.GLSBL as nvarchar(50))  = D_AddressBook_NBL_2.ADDR_NUM AND F0911.GLSBLT = 'A'
WHERE 
 D_Date_NBL_1.FIS_YEAR = @FISCAL_YEAR
and D_Date_NBL_1.FIS_MONTH_NUM_IN_YEAR IN (@FISCAL_PERIOD)
--and D_ObjectAccount_NBL.OBJECT_SUBSIDIARY = '3010001'
and F0911.[GLLT] = 'AA'

) X

GROUP BY
FULL_DATE_1

) F911

ON F911.FULL_DATE_1 = NEW.GL_FULL_DATE_NBL



GROUP BY 
NEW.GL_FULL_DATE_NBL,
NEW.Units_Sum_NBL,
F911.UNITS_911

ORDER BY NEW.GL_FULL_DATE_NBL


/*QUERY TO COMPARE AMOUNT DIFFERENCE ACCOUNTLEDGER_NBL SOLUTION VS QLIK F0911 TABLE ON FULL_DATE**/



SELECT 

NEW.GL_FULL_DATE_NBL,
NEW.Amount_Sum_NBL,
F911.Amount_911,
(F911.Amount_911 - NEW.Amount_Sum_NBL)  as "Variance 911 V NBL"

FROM(
SELECT
X.GL_FULL_DATE GL_FULL_DATE_NBL,
SUM(X.units) Units_Sum_NBL,
SUM(X.Amount) Amount_Sum_NBL
FROM (
SELECT f.GL_FULL_DATE,
f.DOC_NUM,d.FIS_YEAR, 
d.FIS_MONTH_NUM_IN_YEAR, 
o.OBJECT_SUBSIDIARY,
b.ADDR_BOOK_KEY DIM_ADDR_KEY, 
f.ADDR_BOOK_KEY FACT_ADDR_KEY,  
b.ADDR_NUM, 
p.ITEM_KEY DIM_ITEM_KEY, 
f.ITEM_KEY FACT_ITEM_KEY,  
p.ITEM_NUM_2, 
u.BUSINESS_UNIT,
d.FULL_DATE, 
f.QTY_IN_UOM, 
f.UOM_DESC, 
f.JRNL_EXPLA, 
p.BOTTLE_SIZE, 
f.AMT_IN_LOCAL, 
u.EXT_BUDGET_HOLDER_CODE, 
p.BRAND_CODE, 
u.EXT_BUDGET_HOLDER_DESC, 
f.AMT_IN_LOCAL_YTD as amount, 
f.QTY_IN_UOM  as units
FROM [DWH_FINANCE].[V_FT_AccountLedgerTransaction_NBL] f
left join DWH_SHARED.V_D_Date_NBL d
on f.GL_DATE_KEY = d.DATE_KEY 
left join DWH_SHARED.V_D_ObjectAccount_NBL o
on f.OBJECT_ACCOUNT_KEY = o.OBJECT_ACCOUNT_KEY
left join DWH_SHARED.V_D_Product_NBL p
on f.ITEM_KEY = p.ITEM_KEY
left join DWH_SHARED.V_D_AddressBook_NBL b
on f.ADDR_BOOK_KEY = b.ADDR_BOOK_KEY
left join [DWH_SHARED].[V_D_BusinessUnit_NBL] u
on f.BUSINESS_UNIT_KEY = u.BUSINESS_UNIT_KEY
where f.FIS_YEAR = @FISCAL_PERIOD
and d.FIS_MONTH_NUM_IN_YEAR IN (@FISCAL_PERIOD)
--and u.BUSINESS_DIVISION_CODE  IN ('PRNZ','PRA')
--and o.OBJECT_SUBSIDIARY = '3010001'

)X
  
GROUP BY
X.GL_FULL_DATE 

) NEW



LEFT JOIN (
SELECT
X.FULL_DATE_1,
SUM(X.Units) UNITS_911,
SUM(X.Amount) Amount_911

FROM
(
SELECT 
D_Date_NBL_1.FULL_DATE FULL_DATE_1,
D_Date_NBL_2.FULL_DATE FULL_DATE_2,
D_Date_NBL_1.FIS_YEAR,
D_Date_NBL_1.FIS_MONTH_NUM_IN_YEAR,
D_Company_NBL.[COMPANY_KEY] AS [DOC_COMPANY_KEY],
ISNULL(D_OrderType_NBL.[ORDER_TYPE_KEY], '-1') AS [DOC_TYPE_KEY],
F0911.[GLDCT] AS [DOC_TYPE_CODE],
CONVERT(INT,CAST(F0911.[GLDOC] AS DECIMAL)) AS [DOC_NUM],
ISNULL(D_Date_NBL_1.[DATE_KEY], '-1') AS [GL_DATE_KEY],
CAST(F0911.[GLJELN] AS DECIMAL(18,2)) AS [JRNL_ENTRY_LINE_NUM],	
F0911.[GLEXTL] AS [LINE_EXT_CODE],	
ISNULL(D_LedgerType_NBL.[LEDGER_TYPE_KEY], '-1')  AS [LEDGER_TYPE_KEY],	
cast(CONVERT(DOUBLE PRECISION,F0911.[GLU])/100 as numeric(16,2)) AS Units,
cast(CONVERT(DOUBLE PRECISION,F0911.[GLAA])/100 as numeric(16,2)) AS Amount

FROM QLIK_EXT_E1.F0911 
LEFT JOIN DWH.D_Company_NBL  ON  F0911.GLKCO = D_Company_NBL.COMPANY_CODE
LEFT JOIN DWH.D_OrderType_NBL  ON D_OrderType_NBL.ORDER_TYPE_CODE = F0911.GLDCT
LEFT JOIN DWH.D_Date_NBL D_Date_NBL_1  on CAST(EXT_E1.Julian2Date(F0911.GLDGJ) AS DATETIME) = D_Date_NBL_1.FULL_DATE
LEFT JOIN DWH.D_Date_NBL D_Date_NBL_2  on  CAST(EXT_E1.Julian2Date(F0911.GLDSVJ) AS DATETIME) = D_Date_NBL_2.FULL_DATE
LEFT JOIN DWH.D_LedgerType_NBL  ON D_LedgerType_NBL.LEDGER_TYPE_CODE = F0911.GLLT
LEFT JOIN DWH.D_BusinessUnit_NBL  ON D_BusinessUnit_NBL.BUSINESS_UNIT = F0911.GLMCU
LEFT JOIN DWH.D_ObjectAccount_NBL  ON D_ObjectAccount_NBL.OBJECT_SUBSIDIARY = CONCAT(F0911.GLOBJ, F0911.GLSUB)
LEFT JOIN DWH.D_SubledgerType_NBL ON D_SubledgerType_NBL.SUBLEDGER_TYPE_CODE = F0911.GLSBLT
LEFT JOIN DWH.D_GLClass_NBL on F0911.GLGLC = D_GLClass_NBL.GL_CLASS_CODE
LEFT JOIN DWH.D_Item_NBL ON D_Item_NBL.ITEM_NUM_2 =  F0911.GLEXR
LEFT JOIN DWH.D_CostObject_NBL  on F0911.GLABR1 = D_CostObject_NBL.COST_OBJECT_CODE AND F0911.GLABT1 = D_CostObject_NBL.COST_OBJECT_TYPE_CODE
LEFT JOIN DWH.D_Currency_NBL  on F0911.GLBCRC = D_Currency_NBL.CURRENCY_CODE
LEFT JOIN DWH.D_UnitOfMeasure_NBL ON F0911.GLUM = D_UnitOfMeasure_NBL.UOM_CODE
LEFT JOIN DWH_SHARED.V_REF_SupplementalData  on F0911.GLITM = V_REF_SupplementalData.ITEM_NUM
LEFT JOIN DWH.D_Currency_NBL C on F0911.GLCRCD = C.CURRENCY_CODE
LEFT JOIN DWH.D_AddressBook_NBL D_AddressBook_NBL_1 on cast(cast(F0911.GLAN8 as decimal(10,0)) as nvarchar(50)) = D_AddressBook_NBL_1.ADDR_NUM
LEFT JOIN DWH.D_AddressBook_NBL D_AddressBook_NBL_2 ON cast(F0911.GLSBL as nvarchar(50))  = D_AddressBook_NBL_2.ADDR_NUM AND F0911.GLSBLT = 'A'
WHERE 
 D_Date_NBL_1.FIS_YEAR = @FISCAL_YEAR
and D_Date_NBL_1.FIS_MONTH_NUM_IN_YEAR IN (@FISCAL_PERIOD)
--and D_ObjectAccount_NBL.OBJECT_SUBSIDIARY = '3010001'
and F0911.[GLLT] = 'AA'

) X

GROUP BY
FULL_DATE_1

) F911

ON F911.FULL_DATE_1 = NEW.GL_FULL_DATE_NBL



GROUP BY 
NEW.GL_FULL_DATE_NBL,
NEW.Amount_Sum_NBL,
F911.Amount_911

ORDER BY NEW.GL_FULL_DATE_NBL
