/****** CREATE PRIMARY KEY EXAMPLE ******/
ALTER TABLE [DATA_HUB].[ORDER_DETAILS] 
ADD CONSTRAINT [ORDER_DETAILS_PK] PRIMARY KEY NONCLUSTERED 
(
    [ORDER_NUM] ASC,
    [ORDER_TYPE] ASC,
    [COMPANY_CODE] ASC,
    [LINE_NUM] ASC
)
WITH (
    STATISTICS_NORECOMPUTE = OFF, 
    IGNORE_DUP_KEY = ON, 
    ONLINE = OFF, 
    OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF
) ON [PRIMARY];
GO

/****** CREATE CLUSTERED COLUMNSTORE INDEX FOR LARGE TABLES ******/
CREATE CLUSTERED COLUMNSTORE INDEX [DATA_HUB_ORDER_DETAILS_CCI] 
ON [DATA_HUB].[ORDER_DETAILS] 
WITH (
    DROP_EXISTING = OFF, 
    COMPRESSION_DELAY = 0
) ON [PRIMARY];
GO

/****** INDEX FOR TEMP TABLE IN RECURSIVE QUERY ******/
CREATE CLUSTERED INDEX CDX_#Temp_Recurse 
ON #TempRecords ([depth]); -- Where depth increments in recursion
CREATE NONCLUSTERED INDEX NDX_#Temp_Recurse_RecordID 
ON #TempRecords ([RecordID]); -- Where RecordID is the key
GO