



SELECT

CONVERT(varchar, DATEFROMPARTS(YEAR([PERIOD]),MONTH([PERIOD]),1),112) AS [PERIOD],
IPG,
CUSTOMER_GROUP,
WAREHOUSE,
SUM((
    CASE WHEN OBJECT_SUBSIDIARY IN ('3010001') THEN UNITS END 
  ))/100*-1 AS UNITS,
SUM(GSV)*-1 AS GSV,
SKY_KEY

FROM (
SELECT 
EXT_E1.Julian2Date(X.[GLDGJ])	AS PERIOD
,CAST(F4102.IBSRP6 AS VARCHAR) AS IPG 
,CG.CUSTOMER_GROUP AS CUSTOMER_GROUP
,X.WAREHOUSE
,CAST(X.[GLU] as float) AS UNITS 
,CAST(X.[GLAA] /100 AS NUMERIC(38,2))	AS GSV
,[GLBCRC]		AS CURRENCY	
,IIF(DB.[MCRP25] IN('OW','PRPRS'),	'SKY_PRW_PRWAU-0001'
	,IIF(DB.[MCRP25] = 'PRA',			'SKY_PRW_PRA-0001'
		,IIF(DB.[MCRP25] = 'PRPTR',		'SKY_PRW_PTRAU-0001'
			,IIF(DB.[MCRP16] = '100',			'SKY_PRW_PRNZ-0001'
				,IIF(DB.[MCRP16] IN ('200','300'),	'SKY_PRW_PRWNZ-0001'
					,IIF(DB.[MCRP16] = '400',			'SKY_PRW_PTRNZ-0001'
,NULL)))))) AS SKY_KEY
,X.BUSINESS_DIVISION_CODE
,X.PRISMA_REP_UNIT_DESC2
,X.OBJECT_ACCOUNT
,X.OBJECT_SUBSIDIARY
,X.COMPANY_CODE


FROM(

SELECT 
F0911.* 
,BPLANT.BUSINESS_UNIT  AS WAREHOUSE
,BU.[BUSINESS_DIVISION_CODE] AS [BUSINESS_DIVISION_CODE] --PRA FOR 910 
,BU.[PRISMA_REP_UNIT_DESC2]  AS [PRISMA_REP_UNIT_DESC2]  --DISTRIBUTOR FOR 960
,OACCT.OBJECT_SUBSIDIARY
,OACCT.OBJECT_ACCOUNT
,COMP.COMPANY_CODE



FROM [QLIK_EXT_E1].[F0911] F0911

LEFT JOIN (
			SELECT
			INVOICE_NUM
			,BUSINESS_UNIT

			FROM (
					  SELECT DISTINCT
  
					  NULLIF(CAST(F4211.SDDOC AS INT),0) AS [INVOICE_NUM]
					 ,TRIM(F4211.SDMCU) AS [BUSINESS_UNIT]
					 ,ROW_NUMBER() OVER(PARTITION BY NULLIF(CAST(F4211.SDDOC AS INT),0) ORDER BY SUM(CAST(F4211.SDSOQS as float)/10000) DESC) AS BRANCH_RANK
					  FROM [QLIK_EXT_E1].[F4211] F4211
					  WHERE CASE WHEN F4211.SDIVD = 0 then NULL else [EXT_E1].[Julian2Date](F4211.SDIVD) END >= DATEADD(year,-5,GETDATE())
	
					  GROUP BY
					  NULLIF(CAST(F4211.SDDOC AS INT),0),
					 TRIM(F4211.SDMCU)
				)X 

				WHERE BRANCH_RANK = 1

			) BPLANT
ON BPLANT.INVOICE_NUM = NULLIF(CAST(F0911.GLDOC AS INT),0)

LEFT JOIN [DWH_SHARED].[V_D_BusinessUnit] BU 
ON BU.BUSINESS_UNIT = F0911.GLMCU

LEFT JOIN [DWH_SHARED].[V_D_ObjectAccount] OACCT
ON OACCT.OBJECT_SUBSIDIARY = CONCAT(F0911.GLOBJ, F0911.GLSUB)

LEFT JOIN [DWH].[D_Company] COMP 
ON  F0911.GLKCO = COMP.COMPANY_CODE

WHERE 
( F0911.GLKCO IN ('00960','00910')  
  AND OACCT.OBJECT_ACCOUNT IN ( '3010') 
  AND OACCT.OBJECT_SUBSIDIARY NOT IN ('3010005','3010009')
  )

AND CAST(F0911.[GLFY] AS INT) = 21  --GL DATE = FY PERIOD      
   
AND ([GLAA] <> 0  OR [GLU] <> 0)  --EXCLUDE ZEROS, Amount Local & Units

AND ([GLAA] IS NOT NULL  OR [GLU] IS NOT NULL)  --EXCLUDE NULL, Amount Local & Units

) X

LEFT JOIN [QLIK_EXT_E1].[F4102] AS F4102 
	ON  CAST(trim(F4102.IBLITM)as varchar) = CAST(trim(X.GLEXR) as varchar)  AND TRIM(F4102.IBMCU) = X.WAREHOUSE
LEFT JOIN [QLIK_EXT_E1].[F0006] DB
	  ON X.[GLMCU] = DB.MCMCU
LEFT JOIN [DWH_SUPPLYCHAIN].[D_Address_CustomerGroup] CG
	  ON X.[GLAN8] = CG.ADDR_NUM
LEFT JOIN [DWH].[D_AddressBook] AS  DA1
	  ON CAST(floor(X.[GLAN8]) AS varchar) = DA1.ADDR_NUM
LEFT JOIN [DWH].[V_AddressBook] AS  DA2
	  ON CAST(floor(X.[GLAN8]) AS varchar) = DA2.ADDR_NUM
LEFT JOIN [QLIK_EXT_E1].[F41021] IM
	  ON X.[GLITM] = [LIITM]


) Y

WHERE SKY_KEY IS NOT NULL

GROUP BY

[PERIOD],
IPG,
CUSTOMER_GROUP,
WAREHOUSE,
SKY_KEY

