

UPDATE  [ZZINT_ANAPLAN].[D_Address_CustGroup]

SET ADDR_NAME = VAB.ADDR_NAME

FROM  [ZZINT_ANAPLAN].[D_Address_CustGroup] ACG
LEFT JOIN [DWH_SHARED].[V_D_AddressBook] VAB
ON VAB.ADDR_NUM = ACG.ADDR_NUM


