apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: homarr-data
    namespace: homarr
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 500Mi
