table Date_Table
	lineageTag: e95fb0da-6360-4d6c-8ddc-b7ba4377753f

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: f2c0a7a6-6325-4914-8a9f-ac2a6dec1f30
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 64846357-975f-4036-b43e-d28628fefa44
			defaultHierarchy: LocalDateTable_54ac25b0-e9cf-4d8a-9ffb-1ad68417786c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: string
		lineageTag: a3296549-fe51-4d65-8945-1cac3d5bb6f2
		summarizeBy: none
		sourceColumn: Year

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Month_Num
		dataType: int64
		formatString: 0
		lineageTag: 1c633342-1795-4655-8e60-5dba0889f39e
		summarizeBy: sum
		sourceColumn: Month_Num

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: d6c48d54-8570-48a0-85ca-2f8cea97ad5f
		summarizeBy: none
		sourceColumn: Month
		sortByColumn: Month_Num

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Month_Short
		dataType: string
		lineageTag: feec8102-208f-4324-ac73-f68572b51a38
		summarizeBy: none
		sourceColumn: Month_Short
		sortByColumn: Month_Num

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Day
		dataType: int64
		formatString: 0
		lineageTag: 2075dafc-5c94-4f05-b447-942081b8ce9d
		summarizeBy: sum
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column Weekday
		dataType: int64
		formatString: 0
		lineageTag: 8ae6b4b9-89fd-4bbd-a439-b39036f97d5d
		summarizeBy: sum
		sourceColumn: Weekday

		annotation SummarizationSetBy = Automatic

	column Day_of_Week
		dataType: string
		lineageTag: d14e584c-7d4b-4b02-af6f-ad9a8b60f76e
		summarizeBy: none
		sourceColumn: Day_of_Week

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Month_Year
		dataType: string
		lineageTag: 72c42918-6555-4290-a015-2ad3cea92de5
		summarizeBy: none
		sourceColumn: Month_Year
		sortByColumn: Year_Month

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Year_Month
		dataType: string
		lineageTag: f0e580e2-4ca7-4bd9-a53b-405f999c7f11
		summarizeBy: none
		sourceColumn: Year_Month

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column QNum = ROUNDUP(MONTH(Date_Table[Date])/3,0)
		formatString: 0
		lineageTag: 5137f13d-9d40-4c8f-8bf4-71e11039071d
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column YNum = Year(Date_Table[Date])
		formatString: 0
		lineageTag: dc1ef7f7-9b76-49b3-8a08-8976addafdb0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Qrtr_Sort = Date_Table[YNum]&Date_Table[QNum]
		lineageTag: 4c152b65-eae0-46ed-b5b0-d45d49817621
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column Qrtr = Date_Table[YNum]&"-"&"Q"&Date_Table[QNum]
		lineageTag: 8d364525-4e77-440b-8a11-d1333978ff75
		summarizeBy: none
		sortByColumn: Qrtr_Sort

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	partition Date_Table-a4ed9e5f-783c-48ee-bbb8-e80532c0d933 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\seanc\OneDrive\Desktop\Udacity\Project\Sample_Datasets_for_PBI.xlsx"), null, true),
				    Date_Table_Sheet = Source{[Item="Date_Table",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Date_Table_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Year", Int64.Type}, {"Month_Num", Int64.Type}, {"Month", type text}, {"Month_Short", type text}, {"Day", Int64.Type}, {"Weekday", Int64.Type}, {"Day_of_Week", type text}, {"Month_Year", type text}, {"Year_Month", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

