apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: EKS-test-cluster-data-team
  region: ap-southeast-2

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 3
    ssh: # use existing EC2 key
      publicKeyName: cli-admin
cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator"]
    #enableTypes: ["*"] #for all types to be included