apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: EKS-test-cluster
  region: ap-southeast-2

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 3
    ssh: # use existing EC2 key
      publicKeyName: cli-admin
  - name: ng-mixed
    minSize: 3
    maxSize: 5
    instancesDistribution:
      maxPrice: 0.2
      instanceTypes: ["t2.small", "t3.small"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 50
    ssh: # use existing EC2 key
      publicKeyName: cli-admin



