-- Example: Creating and Applying a Masking Policy for Sensitive Account Numbers

-- SET THE WORKING DATABASE AND SCHEMA
USE DATABASE REF_DB;
USE SCHEMA FINANCE;

-- CREATE A MASKING POLICY FOR ACCOUNT NUMBERS
CREATE OR REPLACE MASKING POLICY MASK_ACCOUNT_NUMBER AS
(
    val STRING
) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('SYSADMIN', 'ACCOUNTADMIN', 'SECURITYADMIN', 'DATA_SEC_ROLE', 'DATA_ENGINEER_ROLE') THEN val
        ELSE CONCAT(REPEAT('X', LENGTH(val) - 4), SUBSTRING(val, -4))
    END;

-- CREATE A TABLE USING THE MASKING POLICY
USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE TABLE REF_DB.FINANCE.ACCOUNT_MAPPING (
    ACCOUNT_NUM STRING MASKING POLICY MASK_ACCOUNT_NUMBER,
    SCHEME_ID STRING,
    COMMENTS STRING
);

-- INSERT SAMPLE DATA
INSERT INTO REF_DB.FINANCE.ACCOUNT_MAPPING (ACCOUNT_NUM, SCHEME_ID, COMMENTS)
VALUES
    ('123456789', 'SCHEME_A', ''),
    ('987654321', 'SCHEME_B', ''),
    ('111122223', 'SCHEME_C', '');

-- GRANT PRIVILEGES TO ROLE
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA FINANCE TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA FINANCE TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA FINANCE TO ROLE SYSADMIN;

-- TEST WITH A NON-PRIVILEGED ROLE
USE ROLE DATA_ANALYST;

SELECT * FROM REF_DB.FINANCE.ACCOUNT_MAPPING;

-- TEST WITH A PRIVILEGED ROLE
USE ROLE SYSADMIN;

SELECT * FROM REF_DB.FINANCE.ACCOUNT_MAPPING;

-- CHECK MASKING POLICIES IN ACCOUNT
SELECT * 
FROM SNOWFLAKE.ACCOUNT_USAGE.MASKING_POLICIES;
