--DATA SAMPLING

USE OUR_FIRST_DB;


ALTER SESSION SET USE_CACHED_RESULT = FALSE;  --when repoeating a query I will get the same result and not getting it just from the cache

CREATE OR REPLACE VIEW OUR_FIRST_DB.PUBLIC.ADDRESS_SAMPLE
AS 
SELECT  COUNT(*) AS COUNT_COLUMN FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL_OLD.CUSTOMER_ADDRESS 
SAMPLE ROW (1) ;

SELECT COUNT(*) FROM ADDRESS_SAMPLE;


SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL_OLD.CUSTOMER_ADDRESS 
SAMPLE SYSTEM (1);