USE ROLE INGESTION_ROLE;

ALTER TABLE LANDING_DB.KAFKA_SCHEMA.CONSUMER_WATCHLIST_EVENT SET CHANGE_TRACKING = TRUE;

USE ROLE TRANSFORM_ROLE;

CREATE STREAM IF NOT EXISTS LANDING_DB.KAFKA_SCHEMA.CONSUMER_WATCHLIST_STREAM ON TABLE LANDING_DB.KAFKA_SCHEMA.CONSUMER_WATCHLIST_EVENT;
