\-- SNOWFLAKE ACCOUNT USAGE QUERIES FOR MONITORING AND POWER BI REPORTING

USE DATABASE SNOWFLAKE;
USE SCHEMA ACCOUNT_USAGE;

-- PIPE ACTIVITY
SELECT * FROM ACCOUNT_USAGE.PIPE_USAGE_HISTORY LIMIT 100;

-- SNOWFLAKE BACKGROUND SERVICES
SELECT * FROM ACCOUNT_USAGE.SERVICES LIMIT 100;

-- OBJECT INVENTORY FROM INFORMATION SCHEMA
SELECT * FROM INFORMATION_SCHEMA.TABLES LIMIT 100;
SELECT * FROM INFORMATION_SCHEMA.VIEWS LIMIT 100;
SELECT * FROM INFORMATION_SCHEMA.STAGES LIMIT 100;
SELECT * FROM INFORMATION_SCHEMA.PIPES LIMIT 100;

-- STAGE STORAGE HISTORY
SELECT * FROM ACCOUNT_USAGE.STAGE_STORAGE_USAGE_HISTORY LIMIT 100;

-- CURRENT STAGE INVENTORY (Filter internal stages)
SELECT * 
FROM ACCOUNT_USAGE.STAGES 
WHERE DELETED IS NULL 
LIMIT 100;

-- TABLE STORAGE METRICS (Active Tables Only)
SELECT * 
FROM ACCOUNT_USAGE.TABLE_STORAGE_METRICS 
WHERE ACTIVE_BYTES > 0 AND TABLE_DROPPED IS NULL 
LIMIT 10;

-- DAILY STORAGE USAGE SNAPSHOT
SELECT USAGE_DATE, STORAGE_BYTES, STAGE_BYTES, FAILSAFE_BYTES 
FROM ACCOUNT_USAGE.STORAGE_USAGE 
LIMIT 100;

-- OPTIONAL DATE DIMENSION JOIN
-- SELECT * FROM COMMON_PROD.DWH.REF_DATE;

-- DAILY BREAKDOWN OF WAREHOUSE USAGE (FLATTENED FOR VISUALIZATION)

WITH date_difference AS (
    SELECT
        DATE(START_TIME) AS START_DATE,
        DATE(END_TIME) AS END_DATE,
        WAREHOUSE_ID,
        WAREHOUSE_NAME,
        CREDITS_USED,
        CREDITS_USED_CLOUD_SERVICES, 
        CREDITS_USED_COMPUTE,
        DATEDIFF(day, DATE(START_TIME), DATE(END_TIME)) + 1 AS DIFFERENCE
    FROM
        ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY 
    WHERE 
        START_TIME >= DATEADD(year, -1, CURRENT_DATE)
),
recursive_dates AS (
    SELECT
        START_DATE,
        END_DATE,
        WAREHOUSE_ID,
        WAREHOUSE_NAME,
        CREDITS_USED,
        CREDITS_USED_CLOUD_SERVICES, 
        CREDITS_USED_COMPUTE,
        DIFFERENCE,
        START_DATE AS DATE,
        1 AS LEVEL
    FROM date_difference
    UNION ALL
    SELECT
        rd.START_DATE,
        rd.END_DATE,
        rd.WAREHOUSE_ID,
        rd.WAREHOUSE_NAME,
        rd.CREDITS_USED,
        rd.CREDITS_USED_CLOUD_SERVICES, 
        rd.CREDITS_USED_COMPUTE,
        rd.DIFFERENCE,
        DATEADD(day, 1, rd.DATE),
        rd.LEVEL + 1
    FROM recursive_dates rd
    WHERE rd.LEVEL < rd.DIFFERENCE
),
date_result AS (
    SELECT
        DATE,
        WAREHOUSE_ID,
        WAREHOUSE_NAME,
        DIFFERENCE,
        LEVEL,
        START_DATE,
        END_DATE,
        CREDITS_USED / DIFFERENCE AS CREDITS_USED,
        CREDITS_USED_CLOUD_SERVICES / DIFFERENCE AS CREDITS_USED_CLOUD_SERVICES,
        CREDITS_USED_COMPUTE / DIFFERENCE AS CREDITS_USED_COMPUTE
    FROM recursive_dates
)
SELECT
    DATE,
    WAREHOUSE_ID,
    WAREHOUSE_NAME,
    SUM(CREDITS_USED) AS CREDITS_USED,
    SUM(CREDITS_USED_CLOUD_SERVICES) AS CREDITS_USED_CLOUD_SERVICES,
    SUM(CREDITS_USED_COMPUTE) AS CREDITS_USED_COMPUTE
FROM date_result
GROUP BY
    DATE,
