-- CREATE A SIMPLE DATE DIMENSION TABLE
CREATE OR REPLACE TABLE ANALYTICS_DB.SHARED.DIM_DATE (
    DATE_KEY INT PRIMARY KEY,
    DATE DATE NOT NULL,
    YEAR INT NOT NULL,
    QUARTER INT NOT NULL,
    MONTH INT NOT NULL,
    DAY INT NOT NULL,
    DAY_OF_WEEK VARCHAR(10) NOT NULL
);

-- INSERT SAMPLE DATA
INSERT INTO ANALYTICS_DB.SHARED.DIM_DATE (
    DATE_KEY, DATE, YEAR, QUARTER, MONTH, DAY, DAY_OF_WEEK
) VALUES
    (20230101, '2023-01-01', 2023, 1, 1, 1, 'Sunday'),
    (20230102, '2023-01-02', 2023, 1, 1, 2, 'Monday'),
    (20230103, '2023-01-03', 2023, 1, 1, 3, 'Tuesday');

-- ALTER TABLE TO ADD MULTI_SCHEME_ID COLUMN
ALTER TABLE ANALYTICS_DB.SHARED.DIM_DATE 
    ADD COLUMN MULTI_SCHEME_ID NUMBER(38,0);

-- VIEW DATA
SELECT * FROM ANALYTICS_DB.SHARED.DIM_DATE;

-- SETUP FOR DATABASE REPLICATION
USE ROLE ACCOUNTADMIN;

-- CREATE A REPLICATION GROUP
CREATE REPLICATION GROUP analytics_replication_group
    OBJECT_TYPES = DATABASES
    ALLOWED_DATABASES = ANALYTICS_DB
    ALLOWED_ACCOUNTS = ORG123.ACC456  -- replace with your actual org/account ID
    REPLICATION_SCHEDULE = 'USING CRON 0 9,21 * * * UTC'
    IGNORE EDITION CHECK;

-- MODIFY THE REPLICATION SCHEDULE
ALTER REPLICATION GROUP analytics_replication_group 
    SET REPLICATION_SCHEDULE = '5 MINUTE';

-- ENABLE DATABASE FOR REPLICATION TO A TARGET ACCOUNT
ALTER DATABASE ANALYTICS_DB 
    ENABLE REPLICATION TO ACCOUNTS ORG123.ACC456 
    IGNORE EDITION CHECK;

-- OPTIONALLY DISABLE REPLICATION
ALTER DATABASE ANALYTICS_DB 
    DISABLE REPLICATION TO ACCOUNTS ORG123.ACC456;

-- FORCE SUSPENSION OF REPLICATION GROUP (e.g. for maintenance)
ALTER REPLICATION GROUP IF EXISTS analytics_replication_group SUSPEND IMMEDIATE;

-- RESUME REPLICATION
ALTER REPLICATION GROUP IF EXISTS analytics_replication_group RESUME;

-- TO REFRESH REPLICA MANUALLY (on target)
ALTER DATABASE ANALYTICS_DB REFRESH;

-- CREATE A REPLICA DATABASE IN THE TARGET ACCOUNT
-- run in the target account
CREATE DATABASE ANALYTICS_DB 
    AS REPLICA OF ORG123.ACC789.ANALYTICS_DB;

-- CREATE REPLICATION GROUP REPLICA
CREATE REPLICATION GROUP analytics_replication_group 
    AS REPLICA OF ORG123.ACC789.analytics_replication_group;

-- CHECK REPLICATION OBJECTS
SHOW REPLICATION GROUPS;
SHOW REPLICATION ACCOUNTS;
SHOW ACCOUNTS;

-- ENABLE ACCOUNT-LEVEL REPLICATION (run as ORGADMIN)
USE ROLE ORGADMIN;

SELECT SYSTEM$GLOBAL_ACCOUNT_SET_PARAMETER(
    'ORG123.ACC456', 
    'ENABLE_ACCOUNT_DATABASE_REPLICATION', 
    'true'
);

-- QUERY FROM REPLICATED TABLE
SELECT * FROM ANALYTICS_DB.SHARED.SOME_STAGE_TABLE
LIMIT 10;
