USE ROLE ACCOUNTADMIN;

-- Drop and recreate the SAML2 security integration
DROP SECURITY INTEGRATION IF EXISTS AZUREAD_SSO;

CREATE SECURITY INTEGRATION AZUREAD_SSO
TYPE = SAML2
ENABLED = TRUE
SAML2_ISSUER = 'https://sts.windows.net/<tenant-id>/'
SAML2_SSO_URL = 'https://login.microsoftonline.com/<tenant-id>/saml2'
SAML2_PROVIDER = 'CUSTOM'
SAML2_X509_CERT = '<your-saml-cert>'
SAML2_SP_INITIATED_LOGIN_PAGE_LABEL = 'AzureADSSO'
SAML2_ENABLE_SP_INITIATED = TRUE;


-- For PrivateLink deployments:
ALTER SECURITY INTEGRATION AZUREAD_SSO 
  SET SAML2_SNOWFLAKE_ACS_URL = 'https://<privatelink-account>.snowflakecomputing.com/fed/login';

ALTER SECURITY INTEGRATION AZUREAD_SSO 
  SET SAML2_SNOWFLAKE_ISSUER_URL = 'https://<privatelink-account>.snowflakecomputing.com';

-- For standard public URL deployments:
-- ALTER SECURITY INTEGRATION AZUREAD_SSO 
--   SET SAML2_SNOWFLAKE_ACS_URL = 'https://<account>.snowflakecomputing.com/fed/login';
-- ALTER SECURITY INTEGRATION AZUREAD_SSO 
--   SET SAML2_SNOWFLAKE_ISSUER_URL = 'https://<account>.snowflakecomputing.com';


-- Create role used by SCIM provisioning
CREATE OR REPLACE ROLE AAD_PROVISIONER;

GRANT CREATE USER ON ACCOUNT TO ROLE AAD_PROVISIONER;
GRANT CREATE ROLE ON ACCOUNT TO ROLE AAD_PROVISIONER;
GRANT ROLE AAD_PROVISIONER TO ROLE ACCOUNTADMIN;

-- Create SCIM security integration
CREATE OR REPLACE SECURITY INTEGRATION AAD_PROVISIONING
  TYPE = SCIM
  SCIM_CLIENT = 'AZURE'
  RUN_AS_ROLE = 'AAD_PROVISIONER';

-- Generate SCIM token to use in Azure AD
SELECT SYSTEM$GENERATE_SCIM_ACCESS_TOKEN('AAD_PROVISIONING');


DROP NETWORK RULE IF EXISTS AZURE_AD_WHITELIST;

CREATE NETWORK RULE AZURE_AD_WHITELIST
  TYPE = IPV4
  VALUE_LIST = (
    '13.64.151.161/32',
    '20.50.76.176/28',
    '20.51.9.80/28',
    '20.195.56.102/32'
    -- <add trimmed list as needed>
  )
  COMMENT = 'Azure AD IP ranges for SAML/SCIM';


ALTER SECURITY INTEGRATION AAD_PROVISIONING 
  SET NETWORK_POLICY = 'AZURE_AD_WHITELIST';



-- View configured integrations
SHOW INTEGRATIONS;

-- View configuration of SAML/SCIM integrations
DESC SECURITY INTEGRATION AZUREAD_SSO;
DESC SECURITY INTEGRATION AAD_PROVISIONING;

-- Get Snowflake PrivateLink settings (if using PrivateLink)
SELECT SYSTEM$GET_PRIVATELINK_CONFIG();
SELECT SYSTEM$GET_PRIVATELINK_AUTHORIZED_ENDPOINTS();

-- View SAML configuration at account level
SHOW PARAMETERS LIKE '%SAML_IDENTITY_PROVIDER%' IN ACCOUNT;
