/* IMPORT SHARE IN SNOWFLAKE INSTANCE */

/* Ensure the target roles are already created, such as: 
   REPORTING_RO or DATA_ADMIN 
*/

USE ROLE ACCOUNTADMIN;

-- View available shares
SHOW SHARES;

-- Describe a shared object (dummy example)
DESC SHARE ORG123.PROD456.SHARED_DB;

-- Drop and re-import the shared database (for demo purposes)
DROP DATABASE IF EXISTS SHARED_DATA;

CREATE OR REPLACE DATABASE SHARED_DATA 
  FROM SHARE ORG123.PROD456.SHARED_DB;

-- Grant access to appropriate roles
GRANT DATABASE ROLE SHARED_DATA.DATA_ADMIN TO ROLE SYSADMIN;
GRANT DATABASE ROLE SHARED_DATA.DATA_ADMIN TO ROLE REPORTING_RO;
GRANT DATABASE ROLE SHARED_DATA.DATA_ADMIN TO ROLE DATA_ADMIN;

-- Optional: View current database roles and grants
SHOW DATABASE ROLES IN DATABASE SHARED_DATA;
SHOW GRANTS ON DATABASE SHARED_DATA;

-- Query example data
SELECT TOP 100 * FROM SHARED_DATA.DOMAIN.DIM_SAMPLE_TABLE;

-- ROLE MANAGEMENT EXAMPLES (USE ONLY AS NEEDED)
-- CREATE ROLE REPORTING_RO;
-- DROP ROLE DATA_ADMIN;
-- GRANT ROLE DATA_ADMIN TO USER "demo.user@example.com";
-- GRANT ROLE REPORTING_RO TO USER "demo.user@example.com";
-- GRANT DATABASE ROLE SHARED_DATA.DATA_ADMIN TO USER "demo.user@example.com";

-- SHARE PRIVILEGE GRANTING EXAMPLES
-- GRANT IMPORT SHARE ON ACCOUNT TO ROLE EXTERNAL_SA;
-- GRANT IMPORTED PRIVILEGES ON DATABASE SHARED_DATA TO ROLE ANALYTICS_RO;
-- REVOKE IMPORTED PRIVILEGES ON DATABASE SHARED_DATA FROM ROLE ANALYTICS_RO;
