create security integration 

;
USE ROLE ACCOUNTADMIN ; 




CREATE USER IF NOT EXISTS ADF_CES_DEV
PASSWORD = 'adfPassword123'
LOGIN_NAME = 'adf_ces_dev'
MUST_CHANGE_PASSWORD = FALSE
DEFAULT_WAREHOUSE = 'RAW_DEV'
DEFAULT_ROLE= 'ADF_CES'
COMMENT = 'User for ADF DEV tests' ;


GRANT ROLE ADF_CES TO USER ADF_CES_DEV ;


describe user adf_ces_dev ;

ALTER USER ADF_CES_DEV SET DEFAULT_WAREHOUSE = ANALYTICS_CES ;



alter user adf_ces_dev unset password ; 


CREATE USER IF NOT EXISTS KADA_CATALOG_USER_TEST
PASSWORD = 'kada123'
LOGIN_NAME = 'KADA_CATALOG_USER_TEST'
MUST_CHANGE_PASSWORD = FALSE
DEFAULT_WAREHOUSE = 'SNOWFLAKE'
DEFAULT_ROLE= 'CATALOG_READ_ONLY'
COMMENT = 'User for KADA collector tests' ;

GRANT ROLE CATALOG_READ_ONLY TO USER KADA_CATALOG_USER_TEST ;
GRANT ROLE CATALOG_READ_ONLY TO USER "DANIEL.AGUAYO@COEXSERVICES.COM.AU" ;

ALTER USER ADF_CES_DEV UNSET RSA_PUBLIC_KEY;

ALTER USER ADF_CES_SEC set rsa_public_key='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApp+8OChFssAcsxlAzkWR
KBO8gl0zwT5KxKlvGLEdPCO7aaSg1GeBs4sLFiCqR7+TTGrIaGLceBVJ+v7lfDEi
uyqWZ7kyoUWmM7EX3Xoy/+CvmpYM18/jCzebeaxZws4yPBKrVAWUlWIh8kT1rmzd
0S8LVuwtBmDbg8BGHzu/MSaHOUfmpboeLr1xown7K4V5kzfuDmsqAVs9x8nQ2s20
7sZ9VRDZ+SIbvru5axtwIe6UDvADavlkj0W4K2fIOW6xRu8OOYb11XyQRkw4sg1N
HNR5gF/J3VTnsz+jiUAKOBNXFufv4t2IngNg5xfYAXerp7LqniM09k6CPXo0kmYU
qQIDAQAB' ;

;

/pUBLIC FINGERPRINT*/

;
DESC USER ADF_CES_DEV;
SELECT TRIM((SELECT "value" FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
  WHERE "property" = 'RSA_PUBLIC_KEY_FP'), 'SHA256:');
  
Pz86LWkpPT90P0c/WEg/Pz83Dz8/P0ExRTk/Pz8/PwMNCg==
9at9HaT/HuS5ZiqDo58f5VkKr3AtiyEQf8KSzAOV/Nw=

;
SHOW USERS
; 
WARRRL_REF.CGR_API_DATA
WARRRL_REF.CGR_API_DATA

;
SELECT LOWER(CONCAT_WS('-', CURRENT_ORGANIZATION_NAME(), CURRENT_ACCOUNT_NAME())) AS account_identifier;

GRANT USAGE ON WAREHOUSE ETL_CES_ADF TO ROLE ADF_CES_SEC ;
GRANT OPERATE ON WAREHOUSE ETL_CES_ADF TO ROLE ADF_CES_SEC ; 
