/*Query History */

select * from  LANDING.JIRA_CES.ISSUE
;




SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE QUERY_TEXT LIKE '%GRANT%' AND QUERY_TEXT LIKE '%JIRA%'AND START_TIME >= '2024-07-01' AND DATABASE_NAME = 'RAW_PROD'
ORDER BY start_time;