
/*IMPORT SHARE IN SCHEME  SNOWFLAKE INSTANCE */

-- MAKE SURE YOU HAVE CREATED THE ADMIN DEFAULT ROLES TO SHARE TO LIKE: TAS_REPORTING_RO OR TAS_ADMIN ;

--CREATE SHARE AND IMPORT PRIVILEGES TO ROLES

USE ROLE  ACCOUNTADMIN ;

SHOW SHARES;
DESC SHARE BP43112.HR73515.SCHEME_TAS_SHARE;
DROP DATABASE CES;

CREATE OR REPLACE DATABASE CES FROM SHARE BP43112.HR73515.SCHEME_TAS_SHARE ;

DROP DATABASE CES ;

GRANT DATABASE ROLE CES.SCHEME_ADMIN TO ROLE SYSADMIN ;
GRANT DATABASE ROLE CES.SCHEME_ADMIN TO ROLE TAS_ADMIN ;
GRANT DATABASE ROLE CES.SCHEME_ADMIN TO ROLE TAS_REPORTING_RO ;




SHOW DATABASE ROLES IN DATABASE CES;

SHOW GRANTS ON DATABASE CES ;


SELECT TOP 100 * FROM CES.SUPPLIER.DIM_PARTICIPANT_REGISTRATION;



-- CREATE ROLE TAS_REPORTING;
-- DROP ROLE TAS_ADMIN;
-- DROP ROLE TAS_REPORTING;
-- GRANT ROLE TAS_ADMIN TO USER "DANIEL.AGUAYO@CESYSTEMS.COM" ;
-- GRANT ROLE REPORTING_TAS TO USER "DANIEL.AGUAYO@CESYSTEMS.COM" ;
--GRANT DATABASE ROLE CES.TAS_ADMIN TO USER "DANIEL.AGUAYO@CESYSTEMS.COM" ;
-- GRANT IMPORT SHARE ON ACCOUNT TO DBT_CES_SA;
-- GRANT IMPORTED PRIVILEGES ON DATABASE DBT_TEST to role r2;
-- use role r2;
-- grant imported privileges on database snow_sales to role r3;
-- revoke imported privileges on database snow_sales from role r3;
-- GRANT ROLE TAS_REPORTING_RO TO USER POWERBI_SA ;


