


WITH  CRP_HDR AS (

    SELECT 
    HDR.* 
    ,CASE WHEN HDR.MULTI_SCHEME_ID <> CON.MULTI_SCHEME_ID THEN HDR.CONSUMER || '002' ELSE HDR.CONSUMER END AS CONSUMER_CROSS_SCHEME
    ,CASE WHEN HDR.MULTI_SCHEME_ID <> CON_RECIP.MULTI_SCHEME_ID THEN HDR.RECIPIENT_CONSUMER_ID || '002' ELSE HDR.RECIPIENT_CONSUMER_ID END AS RECIPIENT_CONSUMER_ID_CROSS_SCHEME
    FROM 
    --Txn
    RAW_DEV.CES_MSCM_ORACLE.CRP_REFUND_TXN_HDR AS HDR
    --Consumer and recipient consumer to resolve cross scheme refunds
    LEFT JOIN RAW_DEV.CES_MSCM_ORACLE.MDT_PARTICIPANT_SITES AS CON ON HDR.CONSUMER = CON.SITE_NUMBER
    LEFT JOIN RAW_DEV.CES_MSCM_ORACLE.MDT_PARTICIPANT_SITES AS CON_RECIP ON HDR.RECIPIENT_CONSUMER_ID = CON_RECIP.SITE_NUMBER
     
    

), CRP_DTL AS (

    SELECT
        C.MULTI_SCHEME_ID,
        C.TRANSACTION_ID,
        SUM(C.QUANTITY) AS QUANTITY,
        SUM(C.GROSS_AMOUNT) AS GROSS_AMOUNT,
        SUM(C.GST_AMOUNT) AS GST_AMOUNT,
        SUM(C.TAXABLE_AMOUNT) AS TAXABLE_AMOUNT,
        SUM(CASE WHEN C.MATERIAL_TYPE_ID NOT LIKE '%INELIGIBLE%' THEN C.QUANTITY ELSE 0 END) AS ELIGIBLE_QUANTITY,
        SUM(CASE WHEN C.MATERIAL_TYPE_ID NOT LIKE '%INELIGIBLE%' THEN C.GROSS_AMOUNT ELSE 0 END) AS ELIGIBLE_GROSS_AMOUNT,
        SUM(CASE WHEN C.MATERIAL_TYPE_ID NOT LIKE '%INELIGIBLE%' THEN C.GST_AMOUNT ELSE 0 END) AS ELIGIBLE_GST_AMOUNT,
        SUM(CASE WHEN C.MATERIAL_TYPE_ID NOT LIKE '%INELIGIBLE%' THEN C.TAXABLE_AMOUNT ELSE 0 END) AS ELIGIBLE_TAXABLE_AMOUNT,
        SUM(CASE WHEN C.MATERIAL_TYPE_ID LIKE '%INELIGIBLE%' THEN C.QUANTITY ELSE 0 END) AS INELIGIBLE_QUANTITY
    FROM RAW_DEV.CES_MSCM_ORACLE.CRP_REFUND_TXN_DTL AS C
    
    
    GROUP BY C.MULTI_SCHEME_ID, C.TRANSACTION_ID


), CRP_COLLECTION AS (

    SELECT
    --Natural Key
     HDR.ID
    --Attributes
    ,HDR.MULTI_SCHEME_ID
    ,SCHEME.NAME AS SCHEME
    ,SCHEME.TIMEZONE
    ,HDR.POS_DEVICE_ID
    ,PD.NAME AS POS_DEVICE_NAME
    ,PU.POS_USER_NAME
    ,CS.PARTICIPANT_ID AS CONSUMER_ID
    ,HDR.CONSUMER
    ,HDR.CONSUMER_CROSS_SCHEME
    ,R_TT.VALUE AS CONSUMER_TYPE
    ,CS.SITE_NAME AS CONSUMER_NAME
    ,CS.POST_CODE AS CONSUMER_POSTCODE
    ,RTS.VALUE AS REFUND_TXN_SURVEY_POSTCODE
    ,CP.PARTICIPANT_GROUP_ID CONSUMER_GROUP_ID
    ,HDR.PHOTO_ID
    ,HDR.PHOTO_ID_TYPE
    ,PIT.NAME AS PHOTO_ID_TYPE_NAME
    ,HDR.PHOTO_ID_NAME
    ,HDR.PHOTO_ID_NUMBER
    ,HDR.PAYMENT_METHOD
    ,HDR.CUSTOMER_DECLARATION
    ,HDR.BAG_LABEL_ID
    ,HDR.BAG_ISSUE_TYPE
    ,HDR.TRANSACTED_ON AS TRANSACTION_UTC_DATETIME
    ,CONVERT_TIMEZONE('UTC',SCHEME.TIMEZONE,CAST(HDR.TRANSACTED_ON AS TIMESTAMP)) AS TRANSACTION_LOCAL_DATETIME
    ,TO_CHAR(CONVERT_TIMEZONE('UTC',SCHEME.TIMEZONE,CAST(HDR.TRANSACTED_ON AS TIMESTAMP)),'YYYYMMDD') AS TRANSACTION_LOCAL_DATE_ID
    ,TO_CHAR(CONVERT_TIMEZONE('UTC',SCHEME.TIMEZONE,CAST(HDR.TRANSACTED_ON AS TIMESTAMP)),'HHMISS') AS TRANSACTION_LOCAL_TIME_ID
    ,HDR.NOTIFIED
    ,HDR.MSC_CONSUMER_SITE_ID
    ,HDR.PHYSICAL_CONTAINER_RETURN_POINT
    ,HDR.REFUND_CRP AS SITE_NUMBER
    ,PD.CRP_ID AS SITE_NUMBER_POS
    ,PS.SITE_NAME AS SITE_NAME
    ,PS.POST_CODE AS SITE_POSTCODE
    ,P.PARTICIPANT_ID AS SUPPLIER_ID
    ,P.PARTICIPANT_NUMBER AS SUPPLIER_NUMBER
    ,P.PARTICIPANT_NAME AS SUPPLIER_NAME
    ,HDR.CONSUMER_ALIAS
    ,HDR.RECIPIENT_ALIAS
    ,HDR.RECIPIENT_CONSUMER_ID
    ,HDR.RECIPIENT_CONSUMER_ID_CROSS_SCHEME
    ,HDR.MSC_RECIPIENT_SITE_ID
    --Metrics
    ,DTL.QUANTITY
    ,DTL.GROSS_AMOUNT
    ,DTL.GST_AMOUNT
    ,DTL.TAXABLE_AMOUNT
    ,DTL.ELIGIBLE_QUANTITY
    ,DTL.ELIGIBLE_GROSS_AMOUNT
    ,DTL.ELIGIBLE_GST_AMOUNT
    ,DTL.ELIGIBLE_TAXABLE_AMOUNT
    ,DTL.INELIGIBLE_QUANTITY
    --Metadata Attributes
    ,HDR.TRANSACTED_BY
    ,HDR.CREATED_BY
    ,HDR.CREATED_ON AS CREATED_ON_UTC_DATETIME
    ,HDR.LAST_MODIFIED_BY
    ,HDR.LAST_MODIFIED_ON AS LAST_MODIFIED_ON_UTC_DATETIME
    
    FROM 
    --TXN Tables
    CRP_HDR AS HDR
    LEFT JOIN CRP_DTL DTL ON HDR.ID=DTL.TRANSACTION_ID and HDR.MULTI_SCHEME_ID=DTL.MULTI_SCHEME_ID
    --Scheme
    INNER JOIN RAW_DEV.CES_MSCM_ORACLE.SCHEME AS SCHEME ON HDR.MULTI_SCHEME_ID = SCHEME.MULTI_SCHEME_ID
    --POS
    LEFT JOIN RAW_DEV.CES_MSCM_ORACLE.POS_DEVICE AS PD ON HDR.POS_DEVICE_ID = PD.ID
    LEFT JOIN RAW_DEV.CES_MSCM_ORACLE.POS_USER AS PU ON HDR.TRANSACTED_BY = PU.ID
    --CRP site details
    LEFT JOIN RAW_DEV.CES_MSCM_ORACLE.MDT_PARTICIPANT_SITES AS PS ON NVL(NULLIF(HDR.REFUND_CRP,''),PD.CRP_ID) = PS.SITE_NUMBER
    LEFT JOIN RAW_DEV.CES_MSCM_ORACLE.MDT_PARTICIPANTS AS P ON PS.PARTICIPANT_ID = P.PARTICIPANT_ID
    --Consumer details
    LEFT JOIN RAW_DEV.CES_MSCM_ORACLE.MDT_PARTICIPANT_SITES AS CS ON HDR.CONSUMER_CROSS_SCHEME = CS.SITE_NUMBER
    LEFT JOIN RAW_DEV.CES_MSCM_ORACLE.MDT_PARTICIPANTS AS CP ON CS.PARTICIPANT_ID = CP.PARTICIPANT_ID
    --Other
    LEFT JOIN RAW_DEV.CES_MSCM_ORACLE.PHOTO_ID_TYPE AS PIT ON HDR.PHOTO_ID_TYPE = PIT.ID
    LEFT JOIN RAW_DEV.CES_MSCM_ORACLE.REFUND_TXN_SURVEY AS RTS ON HDR.ID = RTS.REFUND_TXN_ID AND RTS.SURVEY_TYPE = 'POSTCODE'
    LEFT JOIN RAW_DEV.CES_MSCM_ORACLE.SCHEME_REF_CODES AS R_TT ON CS.TAXONOMY_TYPE_ID = R_TT.SCHEME_REF_CODES_ID

)
SELECT * FROM CRP_COLLECTION

;


select * from COMMON_DEV.TEST.CRP_REFUND_TXN_HDR_DT_STG; 

ALTER DYNAMIC TABLE COMMON_DEV.TEST.CRP_REFUND_TXN_HDR_DT_STG REFRESH;

SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, CLUSTERING_KEY 
  FROM COMMON_DEV.INFORMATION_SCHEMA.TABLES
 WHERE CLUSTERING_KEY IS NOT NULL;


 

 SELECT *
FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_HISTORY
WHERE SERVICE_TYPE = 'AUTO_CLUSTERING'
ORDER BY START_TIME DESC;
