USE DATABASE CES_REF ;
USE SCHEMA CES_FINANCE ;

CREATE OR REPLACE MASKING POLICY BTR_ACCOUNT_NUMBER AS
(
    val STRING
) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('SYSADMIN','ACCOUNTADMIN','SECURITYADMIN','DBT_CES_SEC_SA','DBT_CES_SA') THEN val
        ELSE CONCAT(REPEAT('X', LENGTH(val) - 4), SUBSTRING(val, -4))
    END;

USE ROLE ACCOUNTADMIN;
    CREATE OR REPLACE TABLE CES_REF.CES_FINANCE.BANK_REC_ACCOUNT_MAPPING (
    ACCOUNT_NUM STRING MASKING POLICY BTR_ACCOUNT_NUMBER, 
    MULTI_SCHEME_ID STRING,
    COMMENTS STRING
);



INSERT INTO CES_REF.CES_FINANCE.BANK_REC_ACCOUNT_MAPPING (ACCOUNT_NUM, MULTI_SCHEME_ID, COMMENTS)
VALUES
    ('837898801','10000',''),
    ('838210896', '10001', ''),
    ('838532895', '100020001','');


    
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA CES_FINANCE TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA CES_FINANCE TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA CES_FINANCE TO ROLE SYSADMIN;


USE ROLE SF_DEV_CES ;

SELECT * FROM CES_REF.CES_FINANCE.BANK_REC_ACCOUNT_MAPPING
;

USE ROLE SYSADMIN ;
SELECT * FROM CES_REF.CES_FINANCE.BANK_REC_ACCOUNT_MAPPING

;


SELECT * 
FROM SNOWFLAKE.ACCOUNT_USAGE.MASKING_POLICIES ;
