/*CREATE SHARE, LINK TO DATABASES AND DB ROLE*/
USE ROLE SYSADMIN; 
SHOW SHARES;
--BEFORE DOING THIS STEP MAKE SURE TO REMOVE THE EXISING IMPORT OF SHARE IN THE SCHEME SNOWFLAKE INSTANCE
CREATE OR REPLACE SHARE SCHEME_TAS_SHARE;  
SHOW SHARES;  -- VALIDATE
--MAKE SURE DATABASE ROLE IS IN 
SHOW DATABASE ROLES IN DATABASE SHARE_TAS_UAT;
GRANT USAGE ON DATABASE SHARE_TAS_UAT TO SHARE SCHEME_TAS_SHARE;
GRANT  DATABASE ROLE SHARE_TAS_UAT.SCHEME_ADMIN TO SHARE SCHEME_TAS_SHARE;
GRANT REFERENCE_USAGE ON DATABASE COMMON_UAT TO SHARE SCHEME_TAS_SHARE;
SHOW SHARES; -- VALIDATE
/* LINK TAS ACCOUNT TO SHARE */
USE ROLE ACCOUNTADMIN ;
ALTER SHARE SCHEME_TAS_SHARE ADD 
ACCOUNTS=BP43112.TASRECYCLE ;
SHOW SHARES; -- VALIDATE







/*IMPORT SHARE IN SCHEME  SNOWFLAKE INSTANCE */

-- MAKE SURE YOU HAVE CREATED THE ADMIN DEFAULT ROLES TO SHARE TO LIKE: TAS_REPORTING_RO OR TAS_ADMIN ;

--CREATE SHARE AND IMPORT PRIVILEGES TO ROLES

USE ROLE  ACCOUNTADMIN ;  --ACCOUNT ADMIN IS THE DEFAULT ROLE ALLOWED TO CREATE DB FROM SHARE

SHOW SHARES; --SHOW SHARES
DESC SHARE XXXXXX.XXXXXX.SCHEME_XXXX_SHARE; --MAKE SURE DATABASE ROLE IS IN
CREATE OR REPLACE DATABASE CES FROM SHARE BP43112.HR73515.SCHEME_TAS_SHARE ;


/*GRANT DATABSE ROLE TO ROLES TO ALLOW READ ACCESS */  -- ACCOUNTADMIN NEEDED
GRANT DATABASE ROLE CES.SCHEME_ADMIN TO ROLE SYSADMIN ;
GRANT DATABASE ROLE CES.SCHEME_ADMIN TO ROLE TAS_ADMIN ;
GRANT DATABASE ROLE CES.SCHEME_ADMIN TO ROLE TAS_REPORTING_RO ;

/* CHECK THAT YOUR DATABASE HAS THE RIGHT GRANTS */
USE ROLE SYSADMIN; 
SHOW DATABASE ROLES IN DATABASE CES;
SHOW GRANTS ON DATABASE CES ;

/*TEST A ROLE */
USE ROLE TAS_REPORTING_RO ;
SELECT TOP 100 * FROM CES.SUPPLIER.DIM_PARTICIPANT_REGISTRATION;