

select * from RAW_UAT.CES_MSCM_ORACLE.IDCS_USER_GROUPS_A ;


select  * from LANDING_ORACLE.ORACLE_UAT.AWS_RDS_STAGE_CES_MSCM  where METADATA:"table-name"::string = 'INVOICE_AP_TXN_DTL' ;  




USE DATABASE RAW_DEV; 

USE SCHEMA TEST;


create materialized view MSCM_ORACLE_UAT_MV_TEST   --
COMMENT = 'TEST VIEW'
as

select 

  METADATA:"operation"::STRING AS operation,
  METADATA:"partition-key-type"::STRING as partition_key_type,
  METADATA:"record-type"::STRING as record_name,
  METADATA:"schema-name"::STRING as schema_name,
  METADATA:"table-name"::STRING as table_name,
  METADATA:"timestamp"::TIMESTAMP as metadata_timestamp,
  DATA

  from  LANDING_ORACLE.ORACLE_UAT.AWS_RDS_STAGE_CES_MSCM ;

ALTER MATERIALIZED VIEW MSCM_ORACLE_UAT_MV_TEST DROP CLUSTERING KEY ;

DROP MATERIALIZED VIEW MSCM_ORACLE_UAT_MV_TEST ;

SELECT TOP 10 
TABLE_NAME, 
TO_DATE(METADATA_TIMESTAMP)
FROM  MSCM_ORACLE_UAT_MV_TEST ;


ALTER MATERIALIZED VIEW MSCM_ORACLE_UAT_MV_TEST  CLUSTER BY (TABLE_NAME,TO_DATE(METADATA_TIMESTAMP)) ;

select SYSTEM$CLUSTERING_INFORMATION('MSCM_ORACLE_UAT_MV_TEST') ;
 select SYSTEM$CLUSTERING_DEPTH( 'MSCM_ORACLE_UAT_MV_TEST', '(TABLE_NAME,TO_DATE(METADATA_TIMESTAMP)') ;

-- "{
--   ""cluster_by_keys"" : ""LINEAR(TABLE_NAME,TO_DATE(METADATA_TIMESTAMP))"",
--   ""total_partition_count"" : 738,
--   ""total_constant_partition_count"" : 0,
--   ""average_overlaps"" : 737.0,
--   ""average_depth"" : 738.0,
--   ""partition_depth_histogram"" : {
--     ""00000"" : 0,
--     ""00001"" : 0,
--     ""00002"" : 0,
--     ""00003"" : 0,
--     ""00004"" : 0,
--     ""00005"" : 0,
--     ""00006"" : 0,
--     ""00007"" : 0,
--     ""00008"" : 0,
--     ""00009"" : 0,
--     ""00010"" : 0,
--     ""00011"" : 0,
--     ""00012"" : 0,
--     ""00013"" : 0,
--     ""00014"" : 0,
--     ""00015"" : 0,
--     ""00016"" : 0,
--     ""01024"" : 738
--   },
--   ""clustering_errors"" : [ ]
-- }"




/* TEST WITH DATA IN CURRENT PARTITION */   

-- X-SMALL -- 3.8 m rows  --- 1 m 49 secs
-- SMALL -- 3.8 M rows    --- 58 secs

WITH SOURCE AS (
    SELECT
        *
    FROM
        LANDING_ORACLE.ORACLE_UAT.AWS_RDS_STAGE_CES_MSCM
    WHERE METADATA:"table-name"='CONSUMER_REFUND_TXN_DTL' AND DATA is not null
)

SELECT
    N.DATA:ID::string as ID,
    N.DATA:TRANSACTION_ID::string as TRANSACTION_ID,
    N.DATA:MATERIAL_TYPE_ID::string as MATERIAL_TYPE_ID,
    N.DATA:QUANTITY::bigint as QUANTITY,
    N.DATA:REFUND_PER_UNIT::bigint as REFUND_PER_UNIT,
    nullif(N.DATA:GROSS_AMOUNT,'')::float as GROSS_AMOUNT,
    nullif(N.DATA:TAXABLE_AMOUNT,'')::float as TAXABLE_AMOUNT,
    nullif(N.DATA:GST_AMOUNT,'')::float as GST_AMOUNT,
    nullif(N.DATA:CREATED_BY,'')::string as CREATED_BY,
    nullif(N.DATA:CREATED_ON,'')::TIMESTAMP_NTZ as CREATED_ON,
    N.DATA:LAST_MODIFIED_BY::string as LAST_MODIFIED_BY,
    N.DATA:LAST_MODIFIED_ON::TIMESTAMP_NTZ as LAST_MODIFIED_ON,
    nullif(N.DATA:MULTI_SCHEME_ID,'')::bigint as MULTI_SCHEME_ID,
    nullif(N.DATA:SHIPPER_UNIT_ID,'')::bigint as SHIPPER_UNIT_ID,
    TO_TIMESTAMP(N.METADATA:timestamp::string) as METADATA_TIMESTAMP,
    N.METADATA:operation::string as METADATA_OPERATION
FROM SOURCE as N
  ;



/* TEST WITH DATA IN MATERIALIZED VIEW */   

-- X-SMALL -- 3.8 m rows  --- 14 secs
-- SMALL -- 3.8 M rows    --- 8 secs

WITH SOURCE AS (
    SELECT
        *
    FROM
        RAW_DEV.TEST.MSCM_ORACLE_UAT_MV_TEST
    WHERE TABLE_NAME ='CONSUMER_REFUND_TXN_DTL' AND DATA is not null
)

SELECT
    N.DATA:ID::string as ID,
    N.DATA:TRANSACTION_ID::string as TRANSACTION_ID,
    N.DATA:MATERIAL_TYPE_ID::string as MATERIAL_TYPE_ID,
    N.DATA:QUANTITY::bigint as QUANTITY,
    N.DATA:REFUND_PER_UNIT::bigint as REFUND_PER_UNIT,
    nullif(N.DATA:GROSS_AMOUNT,'')::float as GROSS_AMOUNT,
    nullif(N.DATA:TAXABLE_AMOUNT,'')::float as TAXABLE_AMOUNT,
    nullif(N.DATA:GST_AMOUNT,'')::float as GST_AMOUNT,
    nullif(N.DATA:CREATED_BY,'')::string as CREATED_BY,
    nullif(N.DATA:CREATED_ON,'')::TIMESTAMP_NTZ as CREATED_ON,
    N.DATA:LAST_MODIFIED_BY::string as LAST_MODIFIED_BY,
    N.DATA:LAST_MODIFIED_ON::TIMESTAMP_NTZ as LAST_MODIFIED_ON,
    nullif(N.DATA:MULTI_SCHEME_ID,'')::bigint as MULTI_SCHEME_ID,
    nullif(N.DATA:SHIPPER_UNIT_ID,'')::bigint as SHIPPER_UNIT_ID,
    TO_TIMESTAMP(N.METADATA_TIMESTAMP) as METADATA_TIMESTAMP,
    N.OPERATION as METADATA_OPERATION
FROM SOURCE as N
  ;


  


ALTER MATERIALIZED VIEW MSCM_ORACLE_UAT_MV_TEST  CLUSTER BY (TABLE_NAME) ;


select SYSTEM$CLUSTERING_INFORMATION('MSCM_ORACLE_UAT_MV_TEST') ;

-- "{
--   ""cluster_by_keys"" : ""LINEAR(TABLE_NAME)"",
--   ""total_partition_count"" : 1823,
--   ""total_constant_partition_count"" : 1703,
--   ""average_overlaps"" : 0.7756,
--   ""average_depth"" : 1.4838,
--   ""partition_depth_histogram"" : {
--     ""00000"" : 0,
--     ""00001"" : 1703,
--     ""00002"" : 0,
--     ""00003"" : 0,
--     ""00004"" : 2,
--     ""00005"" : 6,
--     ""00006"" : 8,
--     ""00007"" : 14,
--     ""00008"" : 36,
--     ""00009"" : 20,
--     ""00010"" : 24,
--     ""00011"" : 10,
--     ""00012"" : 0,
--     ""00013"" : 0,
--     ""00014"" : 0,
--     ""00015"" : 0,
--     ""00016"" : 0
--   },
--   ""clustering_errors"" : [ ]
-- }"


 select SYSTEM$CLUSTERING_DEPTH( 'MSCM_ORACLE_UAT_MV_TEST', '(TABLE_NAME,TO_DATE(METADATA_TIMESTAMP)') ;



 /* TEST WITH DATA IN MATERIALIZED VIEW */   

-- X-SMALL -- 3.8 m rows  --- 13 secs
-- SMALL -- 3.8 M rows    --- 8 secs

WITH SOURCE AS (
    SELECT
        *
    FROM
        RAW_DEV.TEST.MSCM_ORACLE_UAT_MV_TEST
    WHERE TABLE_NAME ='CONSUMER_REFUND_TXN_DTL' AND DATA is not null
)

SELECT
    N.DATA:ID::string as ID,
    N.DATA:TRANSACTION_ID::string as TRANSACTION_ID,
    N.DATA:MATERIAL_TYPE_ID::string as MATERIAL_TYPE_ID,
    N.DATA:QUANTITY::bigint as QUANTITY,
    N.DATA:REFUND_PER_UNIT::bigint as REFUND_PER_UNIT,
    nullif(N.DATA:GROSS_AMOUNT,'')::float as GROSS_AMOUNT,
    nullif(N.DATA:TAXABLE_AMOUNT,'')::float as TAXABLE_AMOUNT,
    nullif(N.DATA:GST_AMOUNT,'')::float as GST_AMOUNT,
    nullif(N.DATA:CREATED_BY,'')::string as CREATED_BY,
    nullif(N.DATA:CREATED_ON,'')::TIMESTAMP_NTZ as CREATED_ON,
    N.DATA:LAST_MODIFIED_BY::string as LAST_MODIFIED_BY,
    N.DATA:LAST_MODIFIED_ON::TIMESTAMP_NTZ as LAST_MODIFIED_ON,
    nullif(N.DATA:MULTI_SCHEME_ID,'')::bigint as MULTI_SCHEME_ID,
    nullif(N.DATA:SHIPPER_UNIT_ID,'')::bigint as SHIPPER_UNIT_ID,
    TO_TIMESTAMP(N.METADATA_TIMESTAMP) as METADATA_TIMESTAMP,
    N.OPERATION as METADATA_OPERATION
FROM SOURCE as N
  ;




ALTER MATERIALIZED VIEW MSCM_ORACLE_UAT_MV_TEST  CLUSTER BY (TABLE_NAME,OPERATION,TO_DATE(METADATA_TIMESTAMP)) ;

select SYSTEM$CLUSTERING_INFORMATION('MSCM_ORACLE_UAT_MV_TEST') ;

-- "{
--   ""cluster_by_keys"" : ""LINEAR(TABLE_NAME,OPERATION,TO_DATE(METADATA_TIMESTAMP))"",
--   ""total_partition_count"" : 1820,
--   ""total_constant_partition_count"" : 1425,
--   ""average_overlaps"" : 9.0659,
--   ""average_depth"" : 9.0352,
--   ""partition_depth_histogram"" : {
--     ""00000"" : 0,
--     ""00001"" : 1425,
--     ""00002"" : 0,
--     ""00003"" : 0,
--     ""00004"" : 0,
--     ""00005"" : 10,
--     ""00006"" : 6,
--     ""00007"" : 3,
--     ""00008"" : 18,
--     ""00009"" : 13,
--     ""00010"" : 5,
--     ""00011"" : 29,
--     ""00012"" : 23,
--     ""00013"" : 8,
--     ""00014"" : 0,
--     ""00015"" : 21,
--     ""00016"" : 0,
--     ""00032"" : 77,
--     ""00064"" : 57,
--     ""00128"" : 125
--   },
--   ""clustering_errors"" : [ ]
--}"





/* TEST WITH DATA IN MATERIALIZED VIEW */   

-- X-SMALL -- 3.8 m rows  --- 13 secs
-- SMALL -- 3.8 M rows    --- 7.5 secs

WITH SOURCE AS (
    SELECT
        *
    FROM
        RAW_DEV.TEST.MSCM_ORACLE_UAT_MV_TEST

        RAW_DEV.TEST.MSCM_ORACLE_UAT_MV_TEST
    WHERE TABLE_NAME ='CONSUMER_REFUND_TXN_DTL' AND DATA is not null
)

SELECT
    N.DATA:ID::string as ID,
    N.DATA:TRANSACTION_ID::string as TRANSACTION_ID,
    N.DATA:MATERIAL_TYPE_ID::string as MATERIAL_TYPE_ID,
    N.DATA:QUANTITY::bigint as QUANTITY,
    N.DATA:REFUND_PER_UNIT::bigint as REFUND_PER_UNIT,
    nullif(N.DATA:GROSS_AMOUNT,'')::float as GROSS_AMOUNT,
    nullif(N.DATA:TAXABLE_AMOUNT,'')::float as TAXABLE_AMOUNT,
    nullif(N.DATA:GST_AMOUNT,'')::float as GST_AMOUNT,
    nullif(N.DATA:CREATED_BY,'')::string as CREATED_BY,
    nullif(N.DATA:CREATED_ON,'')::TIMESTAMP_NTZ as CREATED_ON,
    N.DATA:LAST_MODIFIED_BY::string as LAST_MODIFIED_BY,
    N.DATA:LAST_MODIFIED_ON::TIMESTAMP_NTZ as LAST_MODIFIED_ON,
    nullif(N.DATA:MULTI_SCHEME_ID,'')::bigint as MULTI_SCHEME_ID,
    nullif(N.DATA:SHIPPER_UNIT_ID,'')::bigint as SHIPPER_UNIT_ID,
    TO_TIMESTAMP(N.METADATA_TIMESTAMP) as METADATA_TIMESTAMP,
    N.OPERATION as METADATA_OPERATION
FROM SOURCE as N
  ;

GRANT ALL PRIVILEGES ON SCHEMA RAW_DEV.TEST TO ROLE DBT_CES_SA ; 
GRANT ALL PRIVILEGES ON ALL MATERIALIZED VIEWS IN SCHEMA RAW_DEV.TEST TO ROLE DBT_CES_SA;




WITH SOURCE AS (
    SELECT
        *
    FROM
        RAW_DEV.TEST.MSCM_ORACLE_UAT_MV_TEST
    WHERE METADATA:"table-name"='ADM_FLEXFIELDS_A' AND DATA is not null
)

SELECT
    nullif(N.DATA:FLEXFIELD_ID,'')::bigint as FLEXFIELD_ID,
    nullif(N.DATA:MULTI_SCHEME_ID,'')::bigint as MULTI_SCHEME_ID,
    nullif(N.DATA:SOURCE_TABLE,'')::string as SOURCE_TABLE,
    nullif(N.DATA:COLUMN_NAME,'')::string as COLUMN_NAME,
    nullif(N.DATA:COLUMN_LABEL,'')::string as COLUMN_LABEL,
    nullif(N.DATA:DATATYPE,'')::string as DATATYPE,
    nullif(N.DATA:DEFAULT_VALUE,'')::string as DEFAULT_VALUE,
    nullif(N.DATA:MIN_VALUE,'')::string as MIN_VALUE,
    nullif(N.DATA:MAX_VALUE,'')::string as MAX_VALUE,
    nullif(N.DATA:CATEGORY,'')::string as CATEGORY,
    nullif(N.DATA:CODE,'')::string as CODE,
    nullif(N.DATA:MANDATORY_FLAG,'')::string as MANDATORY_FLAG,
    nullif(N.DATA:EFFECTIVE_DATE_FROM,'')::DATE as EFFECTIVE_DATE_FROM,
    nullif(N.DATA:EFFECTIVE_DATE_TO,'')::DATE as EFFECTIVE_DATE_TO,
    nullif(N.DATA:ACTIVE_FLAG,'')::string as ACTIVE_FLAG,
    nullif(N.DATA:CREATED_BY,'')::string as CREATED_BY,
    nullif(N.DATA:CREATED_ON,'')::TIMESTAMP_NTZ as CREATED_ON,
    N.DATA:LAST_MODIFIED_BY::string as LAST_MODIFIED_BY,
    N.DATA:LAST_MODIFIED_ON::TIMESTAMP_NTZ as LAST_MODIFIED_ON,
    nullif(N.DATA:VIEW_ROLES,'')::string as VIEW_ROLES,
    nullif(N.DATA:EDIT_ROLES,'')::string as EDIT_ROLES,
    nullif(N.DATA:MULTI_VALUES,'')::string as MULTI_VALUES,
    nullif(N.DATA:DISPLAY_ORDER,'')::bigint as DISPLAY_ORDER,
    nullif(N.DATA:MANDATORY_SCREENS,'')::string as MANDATORY_SCREENS,
    nullif(N.DATA:AUDIT_TYPE,'')::string as AUDIT_TYPE,
    nullif(N.DATA:AUDIT_DATE,'')::TIMESTAMP_NTZ as AUDIT_DATE,
    nullif(N.DATA:AUDIT_USER,'')::string as AUDIT_USER,
    nullif(N.DATA:DISPLAY_SCREENS,'')::string as DISPLAY_SCREENS,
    nullif(N.DATA:LOV_VIEW_NAME,'')::string as LOV_VIEW_NAME,
    nullif(N.DATA:DISPLAY_IF,'')::string as DISPLAY_IF,
    nullif(N.DATA:MANDATORY_IF,'')::string as MANDATORY_IF,
    TO_TIMESTAMP(N.METADATA_TIMESTAMP) as METADATA_TIMESTAMP,
    N.OPERATION as METADATA_OPERATION
FROM SOURCE as N   ;




create or replace view LANDING.CES_MSCM_ORACLE_UAT.ADM_FLEXFIELDS(
	FLEXFIELD_ID,
	MULTI_SCHEME_ID,
	SOURCE_TABLE,
	COLUMN_NAME,
	COLUMN_LABEL,
	DATATYPE,
	DEFAULT_VALUE,
	MIN_VALUE,
	MAX_VALUE,
	CATEGORY,
	CODE,
	MANDATORY_FLAG,
	EFFECTIVE_DATE_FROM,
	EFFECTIVE_DATE_TO,
	ACTIVE_FLAG,
	CREATED_BY,
	CREATED_ON,
	LAST_MODIFIED_BY,
	LAST_MODIFIED_ON,
	VIEW_ROLES,
	EDIT_ROLES,
	MULTI_VALUES,
	DISPLAY_ORDER,
	MANDATORY_SCREENS,
	DISPLAY_SCREENS,
	LOV_VIEW_NAME,
	DISPLAY_IF,
	MANDATORY_IF,
	METADATA_TIMESTAMP,
	METADATA_OPERATION
) as (
    

WITH SOURCE AS (
    SELECT
        *
    FROM
        LANDING_ORACLE.ORACLE_UAT.AWS_RDS_STAGE_CES_MSCM
    WHERE METADATA:"table-name"='ADM_FLEXFIELDS' AND DATA is not null
)

SELECT
    N.DATA:FLEXFIELD_ID::bigint as FLEXFIELD_ID,
    nullif(N.DATA:MULTI_SCHEME_ID,'')::bigint as MULTI_SCHEME_ID,
    nullif(N.DATA:SOURCE_TABLE,'')::string as SOURCE_TABLE,
    nullif(N.DATA:COLUMN_NAME,'')::string as COLUMN_NAME,
    nullif(N.DATA:COLUMN_LABEL,'')::string as COLUMN_LABEL,
    nullif(N.DATA:DATATYPE,'')::string as DATATYPE,
    nullif(N.DATA:DEFAULT_VALUE,'')::string as DEFAULT_VALUE,
    nullif(N.DATA:MIN_VALUE,'')::string as MIN_VALUE,
    nullif(N.DATA:MAX_VALUE,'')::string as MAX_VALUE,
    nullif(N.DATA:CATEGORY,'')::string as CATEGORY,
    nullif(N.DATA:CODE,'')::string as CODE,
    nullif(N.DATA:MANDATORY_FLAG,'')::string as MANDATORY_FLAG,
    nullif(N.DATA:EFFECTIVE_DATE_FROM,'')::DATE as EFFECTIVE_DATE_FROM,
    nullif(N.DATA:EFFECTIVE_DATE_TO,'')::DATE as EFFECTIVE_DATE_TO,
    nullif(N.DATA:ACTIVE_FLAG,'')::string as ACTIVE_FLAG,
    nullif(N.DATA:CREATED_BY,'')::string as CREATED_BY,
    nullif(N.DATA:CREATED_ON,'')::TIMESTAMP_NTZ as CREATED_ON,
    N.DATA:LAST_MODIFIED_BY::string as LAST_MODIFIED_BY,
    N.DATA:LAST_MODIFIED_ON::TIMESTAMP_NTZ as LAST_MODIFIED_ON,
    nullif(N.DATA:VIEW_ROLES,'')::string as VIEW_ROLES,
    nullif(N.DATA:EDIT_ROLES,'')::string as EDIT_ROLES,
    nullif(N.DATA:MULTI_VALUES,'')::string as MULTI_VALUES,
    nullif(N.DATA:DISPLAY_ORDER,'')::bigint as DISPLAY_ORDER,
    nullif(N.DATA:MANDATORY_SCREENS,'')::string as MANDATORY_SCREENS,
    nullif(N.DATA:DISPLAY_SCREENS,'')::string as DISPLAY_SCREENS,
    nullif(N.DATA:LOV_VIEW_NAME,'')::string as LOV_VIEW_NAME,
    nullif(N.DATA:DISPLAY_IF,'')::string as DISPLAY_IF,
    nullif(N.DATA:MANDATORY_IF,'')::string as MANDATORY_IF,
    TO_TIMESTAMP(N.METADATA:timestamp::string) as METADATA_TIMESTAMP,
    N.METADATA:operation::string as METADATA_OPERATION
FROM SOURCE as N
  );




/* --- DBT RUN_TIME ===  */ 

--LANDING VIEWS UAT: 1M 8 SECSDB
--LANDING VIEWS DEV: 35 secs

-- dbt run --select tag:LANDING,tag:CES_MSCM_ORACLE --exclude LANDING_ORACLE_FMT_DRIVER_CHECKS LANDING_ORACLE_FMT_LOCATIONS LANDING_ORACLE_FMT_LOCATION_DISTANCES LANDING_ORACLE_FMT_ORGANISATIONS LANDING_ORACLE_FMT_PEOPLE LANDING_ORACLE_FMT_SCHEME_REF_CODES LANDING_ORACLE_FMT_SCHEME_VEHICLE_TYPES LANDING_ORACLE_FMT_TRIPS LANDING_ORACLE_FMT_TRIP_CLAIMS LANDING_ORACLE_FMT_TRIP_CLAIM_LINES LANDING_ORACLE_FMT_TRIP_CLAIM_LINE_ADJUSTMENTS LANDING_ORACLE_FMT_TRIP_LEGS LANDING_ORACLE_FMT_TRIP_LEG_ADJUSTMENTS LANDING_ORACLE_FMT_TRIP_LEG_STATUS_LOGS LANDING_ORACLE_FMT_TRIP_STOPS LANDING_ORACLE_FMT_TRIP_UNITS LANDING_ORACLE_FMT_VEHICLES LANDING_ORACLE_FMT_VEHICLE_RATES LANDING_ORACLE_FMT_VEHICLE_TYPES LANDING_ORACLE_PYMT_BANK_ACCOUNTS LANDING_ORACLE_PYMT_BANK_ACCOUNTS_A LANDING_ORACLE_PYMT_CONTROLS LANDING_ORACLE_PYMT_CONTROLS_A LANDING_ORACLE_PYMT_PAYMENT_STATUS LANDING_ORACLE_REFUND_PHOTO_ID LANDING_ORACLE_REFUND_PHOTO_ID_A

WITH SOURCE AS (
    SELECT 
    *
    FROM
        LANDING.CES_MSCM_ORACLE_DEV.MFG_STATUTORY_DECLARATION_DISCUSSION
)
SELECT
    s.*
FROM
    source s
WHERE (1=1)    


QUALIFY row_number() OVER (PARTITION BY s. ORDER BY s.METADATA_TIMESTAMP DESC) = 1




;

