table 'SalesLT FactSalesTable'
	lineageTag: 4c8a0d33-f0c6-4eae-b841-eb096639b09c

	column SalesOrderID
		dataType: int64
		formatString: 0
		lineageTag: 4024d7ab-e788-4472-8c14-09c7d254922e
		summarizeBy: count
		sourceColumn: SalesOrderID

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 276132e8-8778-4ec1-a38f-dc8d4a80c5dd
		summarizeBy: none
		sourceColumn: OrderDate

		variation Variation
			isDefault
			relationship: aa972d0d-8be1-49d1-a970-c70571565307
			defaultHierarchy: LocalDateTable_0d670898-a12a-4c30-8700-8fc02a7bb15d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column CustomerID
		dataType: int64
		formatString: 0
		lineageTag: 3c6fdf7c-9e39-4268-acef-fa9ba8588f86
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column SalesQty
		dataType: int64
		formatString: 0
		lineageTag: 9bd2229d-aa67-428b-b157-6e83ec14a8ad
		summarizeBy: sum
		sourceColumn: SalesQty

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: int64
		formatString: 0
		lineageTag: 2ff32f65-996b-4c0c-a512-a0574c68dec6
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column NSV
		dataType: decimal
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		lineageTag: 156df996-6ff2-4e38-bf0e-584698f087e5
		summarizeBy: sum
		sourceColumn: NSV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-AU"}

	column ModifiedDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 151ca0c7-9b54-4dad-bd66-f2f8bb17e12c
		summarizeBy: none
		sourceColumn: ModifiedDate

		variation Variation
			isDefault
			relationship: 3f7db449-26df-4fd9-bd24-1e78680fd6fb
			defaultHierarchy: LocalDateTable_cd4c5be2-477d-45e4-ad22-1d0553adad69.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column CalendarID
		dataType: string
		lineageTag: 2f226a4d-b236-447a-a049-2a1aced80e93
		summarizeBy: none
		sourceColumn: CalendarID

		annotation SummarizationSetBy = Automatic

	partition 'SalesLT FactSalesTable' = m
		mode: import
		source = ```
				let
				    Source = Sql.Database("demo-db-power-bi.database.windows.net", "adventure-works-sample"),
				    SalesLT_FactSalesTable = Source{[Schema="SalesLT",Item="FactSalesTable"]}[Data],
				    #"Added Custom" = Table.AddColumn(SalesLT_FactSalesTable, "CalendarID", each Number.FromText(Text.From(Date.Year([OrderDate])) & 
				                Text.PadStart(Text.From(Date.Month([OrderDate])), 2, "0") & 
				                Text.PadStart(Text.From(Date.Day([OrderDate])), 2, "0")))
				in
				    #"Added Custom"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

