name: Check - only-dev-merges-into-main

on:
  pull_request:
    branches:
      - main
      
jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Skip check if 'autopr' label is present
        run: |
          echo "Labels found: ${{ toJson(github.event.pull_request.labels) }}"
          if echo "${{ toJson(github.event.pull_request.labels) }}" | grep -q "autopr"; then
            echo "Bypassing check due to autopr label"
            exit 0
          fi

          echo "Source branch is: ${{ github.head_ref }}"
          if [ "${{ github.head_ref }}" != "dev" ]; then
            echo "::error::Only the 'dev' branch is allowed to merge into 'main'."
            exit 1
          fi
