--############ FACT_TABLE ############--

SELECT
--Fact Key (hashed from source, no DBT Utils)
  DTL.RECORD_ID AS FACT_WAREHOUSE_STOCK_KEY

--Foreign Keys
, {{ dbt_utils.generate_surrogate_key(['HDR.PROGRAM_CODE']) }} AS DIM_PROGRAM_KEY
, {{ dbt_utils.generate_surrogate_key(['DTL.ITEM_CATEGORY_ID']) }} AS DIM_ITEM_CATEGORY_KEY
, {{ dbt_utils.generate_surrogate_key(['HDR.DEPOT_ID']) }} AS DIM_DEPOT_KEY
, {{ dbt_utils.generate_surrogate_key(['PS.VENDOR_ID']) }} AS DIM_B2B_VENDOR_KEY
, {{ dbt_utils.generate_surrogate_key(["REPLACE(HDR.CYCLE,'-','')"]) }} AS DIM_DATE_CYCLE_KEY
, {{ dbt_utils.generate_surrogate_key(["TO_CHAR(CONVERT_TIMEZONE('UTC',PROGRAM.REGION,CAST(HDR.REPORTED_DATE AS TIMESTAMP)),'YYYYMMDD')"]) }} AS DIM_DATE_REPORTED_KEY

--Natural Key
--, DTL.RECORD_ID AS RECORD_ID

--Attributes
, HDR.PROGRAM_CODE AS PROGRAM_CODE
, PROGRAM.TITLE AS PROGRAM
, HDR.RECORD_ID AS STOCK_HDR_ID
, HDR.DEPOT_ID AS DEPOT_CODE
, PS.DEPOT_NAME AS DEPOT_NAME
, PS.VENDOR_ID AS VENDOR_ID
, P.VENDOR_CODE AS VENDOR_CODE
, P.VENDOR_NAME AS VENDOR_NAME
, HDR.CYCLE AS CYCLE
, REPLACE(CYCLE,'-','') AS CYCLE_DATE_ID
, HDR.RECORD_TYPE AS RECORD_TYPE
, HDR.STATE AS STATE
, HDR.REPORTED_BY AS REPORTED_BY
, CONVERT_TIMEZONE('UTC',PROGRAM.REGION,CAST(HDR.REPORTED_DATE AS TIMESTAMP)) AS REPORTED_LOCAL_TIMESTAMP
, TO_CHAR(CONVERT_TIMEZONE('UTC',PROGRAM.REGION,CAST(HDR.REPORTED_DATE AS TIMESTAMP)),'YYYYMMDD') AS REPORTED_LOCAL_DATE_ID
, HDR.REPORTED_DATE AS REPORTED_UTC_TIMESTAMP
, DTL.ITEM_CATEGORY_ID AS ITEM_CATEGORY_ID
, IC.NAME AS ITEM_CATEGORY
, DTL.UNIT AS UNIT

--Metrics
, DTL.QUANTITY AS STOCK_QUANTITY

--Metadata Attributes
, DTL.ENTERED_BY AS ENTERED_BY
, DTL.ENTERED_ON AS ENTERED_ON_UTC_TIMESTAMP
, DTL.UPDATED_BY AS UPDATED_BY
, DTL.UPDATED_ON AS UPDATED_ON_UTC_TIMESTAMP
, SYSDATE() AS LOAD_UTC_TIMESTAMP

FROM
{{ source('DATA_HUB', 'STOCK_HEADER') }} AS HDR
INNER JOIN {{ source('DATA_HUB', 'STOCK_DETAILS') }} AS DTL
  ON HDR.RECORD_ID = DTL.STOCK_HEADER_ID
LEFT JOIN {{ source('DATA_HUB', 'VENDOR_LOCATIONS') }} AS PS
  ON HDR.DEPOT_ID = PS.DEPOT_CODE
LEFT JOIN {{ source('DATA_HUB', 'VENDORS') }} AS P
  ON PS.VENDOR_ID = P.VENDOR_ID
INNER JOIN {{ source('DATA_HUB', 'ITEM_CATEGORY') }} AS IC
  ON DTL.ITEM_CATEGORY_ID = IC.ID
INNER JOIN {{ source('DATA_HUB', 'PROGRAM') }} AS PROGRAM
  ON HDR.PROGRAM_CODE = PROGRAM.PROGRAM_CODE
INNER JOIN (
  SELECT
    H.RECORD_ID
    , ROW_NUMBER() OVER (PARTITION BY H.DEPOT_ID, H.CYCLE, H.RECORD_TYPE, H.STATE ORDER BY H.UPDATED_ON DESC) AS RN
  FROM {{ source('DATA_HUB', 'STOCK_HEADER') }} AS H
) FILTER
  ON HDR.RECORD_ID = FILTER.RECORD_ID
WHERE FILTER.RN = 1